avo-hq/avo

lib/avo/engine.rb
This PR switches `load` with `require` when engine loads AVO files.
=> fix: engine loads same files more than once

app/controllers/avo/resources_controller.rb, app/frontend/js/components/Index/ItemControls.vue, app/frontend/js/views/ResourceEdit.vue, app/frontend/js/views/ResourceShow.vue, lib/avo/app/resource.rb, spec/features/avo/resources_controller_spec.rb
Edit=true Update=true => ShowEditButtons=true ShowSaveButton=true
Edit=false Update=false => ShowEditButtons=false ShowSaveButton=false
Edit=true Update=false => ShowEditButtons=true ShowSaveButton=false
Edit=false Update=true => ShowEditButtons=false ShowSaveButton=true(won’t be accessible)
EditButtons = Edit Button on Index + Edit Button on Show
SaveButtom = Save Button on Edit
=> fix: remove save button from edit when update is restricted

app/frontend/js/components/Edit/KeyValueField.vue, app/frontend/js/components/KeyValueComponent.vue, app/frontend/js/components/KeyValueRow.vue
There were some problems with the keyvalue field.
Pressing enter in the keyvalue key or value inputs doesnt submit the form. In case of value, enter either focuses on next row(if existing) or adds a new row.
=> fix: KeyValue disable options issues

app/frontend/js/components/CodeComponent.vue, app/frontend/js/components/Edit/CodeField.vue, app/frontend/js/components/Show/CodeField.vue, lib/avo/app/fields/code_field.rb, spec/dummy/app/avo/resources/user.rb
Instead of `rows` and `auto` I thought about implementing a `height` option that will enforce the size of the field(if specified), otherwise it defaults to auto and the size will fit all content. I think it will be easier for the administrator to configure and also makes sense to default to auto. Let me know what you think about this.
=> feat: height option for Code field

app/frontend/js/components/Edit/MarkdownField.vue, lib/avo/app/fields/markdown_field.rb, spec/dummy/app/avo/resources/project.rb
Same logic as code, if not present or wrong height measure (ex: '3maini') the height of the field will be auto (expand as long as it's content). Unfortunately the MavonEditor for markdown has a minimum height of 300px that cannot be override, so for values less than 300px, the editor will have height 300px, otherwise setting more than 300px will set the height accordingly.
height: 4degetemici => auto height
height: 125px => height: 300px
height: 375px => height: 375px
height: 1cm => height: 300px
height: 10cm => height: 377.49px
=> fix: height option for Markdown field

app/frontend/js/components/Index/BooleanGroupField.vue, app/frontend/js/components/Show/BooleanGroupField.vue
let's discuss more on this
currently for `{"admin":"false","manager":"false","writer":"false"}` input it will display - because "true" is not taken as true but as string
we have the following options:
- keep dash for wrong written object as `{"admin":"false","manager":"false","writer":"false"}`
- allow true_values and false_values as boolean and always save true or false
- we can allow also strings `true` and `false` by default
- why not restrict to have options only from the configured options, because on edit we are overwriting them?
=> fix: index/show will display dash for wrong input

app/frontend/js/components/Edit/FieldWrapper.vue, app/frontend/js/components/Modals/ActionsModal.vue, app/frontend/js/components/ResourceActions.vue, app/frontend/js/components/Show/BooleanGroupField.vue, app/frontend/js/mixins/is-field-wrapper.js, lib/avo/app/action.rb, spec/dummy/app/avo/actions/make_admin.rb, spec/dummy/app/avo/actions/mark_inactive.rb, spec/dummy/app/avo/resources/user.rb, spec/system/avo/actions_spec.rb
Made the requested changes, everything should be fine now. Added the Make Admin no_confirmation: true action too.
Keep in touch that in order no_confirmation to work, no fields have to be on the action definition.
=> feature: allow no_confirmation for Actions

app/frontend/js/components/Button.vue, app/frontend/js/components/Index/ResourceFilters.vue, app/frontend/js/mixins/loads-resource.js, app/frontend/js/views/ResourceEdit.vue, app/frontend/js/views/ResourceIndex.vue, app/frontend/js/views/ResourceNew.vue, app/frontend/js/views/ResourceShow.vue, lib/avo/app/resource.rb
Loaders on `new`, `show` and `create` views are not visible. This fixes that
=> fix: loaders are not visible on some pages

app/frontend/js/components/EmptyState.vue, spec/system/avo/user_forms_spec.rb
=> fix: index pages has wrong label

app/controllers/avo/resources_controller.rb, lib/avo/app/filter.rb, spec/dummy/app/avo/filters/members_filter.rb, spec/dummy/app/avo/resources/team.rb, spec/system/avo/filters_spec.rb, spec/system/avo/has_one_field_spec.rb
=> fix: filter tests

app/views/layouts/avo/_javascript.html.erb, app/views/layouts/avo/_translations.html.erb
Avo currently does not work if you have a content security policy which blocks `unsafe-inline`.  This Pull Request uses the built-in option for `javascript_tag` to allow a nonce to mark the inline script as safe.  
This change is also safe for apps without a content_security_policy.
=> Update inline javascript tags to allow for csp nonces

lib/avo/app/fields/belongs_to.rb
`belongs_to` avo relation is broken for some two-names models (`belongs_to :team_membership`). This should fix it by providing a better way of searching for an Avo resource.
Fixes https://github.com/avo-hq/avo/issues/202
=> fix: belongs_to broken for some model names

lib/generators/avo/templates/initializer/avo.rb
Removes the default `config.current_user_method(&:current_user)` value introduced in https://github.com/avo-hq/avo/pull/205.
=> fix: remove default current user value

lib/avo/app/app.rb, lib/avo/app/fields/has_and_belongs_to_many.rb
Fixes https://github.com/avo-hq/avo/issues/236
=> fix: HABTM cant find associations with custom class_name

app/controllers/avo/actions_controller.rb, app/controllers/avo/base_controller.rb, app/controllers/avo/relations_controller.rb, app/controllers/avo/search_controller.rb, lib/avo/app/action.rb, lib/avo/app/fields/belongs_to.rb, lib/avo/app/filter.rb, lib/avo/app/resource.rb, spec/dummy/app/avo/actions/toggle_admin.rb, spec/dummy/app/avo/actions/toggle_inactive.rb, spec/dummy/app/avo/actions/toggle_published.rb, spec/dummy/app/avo/filters/featured_filter.rb, spec/dummy/app/avo/filters/members_filter.rb, spec/dummy/app/avo/filters/people_2_filter.rb, spec/dummy/app/avo/filters/people_filter.rb, spec/dummy/app/avo/filters/published_filter.rb, spec/dummy/app/avo/resources/post.rb, spec/dummy/app/avo/resources/project.rb, spec/dummy/app/avo/resources/team.rb, spec/dummy/app/avo/resources/team_membership.rb, spec/dummy/app/avo/resources/user.rb
This PR removes the `def configure` method from `Resource`, `Action` and `Filter` classes in favor of `class_attribute`s.
=> refactor: remove configure methods in favor of class attributes

app/components/avo/index/grid_item_component.rb, app/controllers/avo/actions_controller.rb, app/controllers/avo/base_controller.rb, app/views/avo/actions/show.html.erb, lib/avo/action_model.rb, lib/avo/base_action.rb, lib/avo/base_resource.rb, lib/avo/configuration.rb, lib/avo/engine.rb, lib/avo/fields/base_field.rb, lib/avo/fields/field_extensions/has_field_name.rb, lib/avo/fields_collector.rb, lib/avo/grid_collector.rb, lib/avo/has_context.rb, spec/dummy/app/avo/actions/toggle_inactive.rb, spec/dummy/app/avo/actions/toggle_published.rb, spec/dummy/app/avo/resources/post_resource.rb, spec/dummy/app/avo/resources/project_resource.rb, spec/dummy/app/avo/resources/team_membership_resource.rb, spec/dummy/app/avo/resources/team_resource.rb, spec/dummy/app/avo/resources/user_resource.rb
There are a few changes with this PR:
1. Fields get declared using `field :name, as: :text` syntax. 
2. Grid fields get declared using `grid do` block
3. Actions and filters are declared using `action` and `filter` methods
4. Action fields get passed on to the action form using an `ActiveModel` like object for better compatibility.
5. `can_see` renamed to `visible` in field declaration
Example of fields declaration👇
```ruby
class UserResource < Avo::BaseResource
self.title = :name
self.translation_key = 'avo.resource_translations.user'
self.search = [:id, :first_name, :last_name]
self.includes = [:posts, :post]
self.devise_password_optional = true
field :id,         as: :id, link_to_resource: true
field :email,      as: :gravatar, link_to_resource: true
heading 'User Information'
field …
```
=> chore: field API for declaring fields

lib/avo/app.rb
Avo assumes you have `ActiveStorage` installed and tries to use it in the `App.ini` method. We're removing that dependency.
=> chore: remove ActiveStorage dependency

app/packs/stylesheets/components/code.css
Hi Adrian,
A little fix for the CodeMirror editor on small screens as it falls under the sidebar and top navigation bar:
Before: 
After:
=> Fix CoreMirror fullscreen hiding under the sidebar

app/controllers/avo/application_controller.rb, app/controllers/avo/home_controller.rb, spec/features/avo/license_tinkering_in_application_controller_spec.rb
This fixes a bug where `/avo` path would raise an invalid license error.
=> fix: invalid license erros on /avo

lib/generators/avo/action_generator.rb, lib/generators/avo/templates/action.tt
running the generator `bin/rails generate avo:action toggle_published`
results in the following error: 
```
Could not find "action.rb" in any of your source paths. Your current source paths are: 
~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/avo-1.2.10/lib/generators/avo/templates
```
Additionally the template referenced a parent class `Action` that doesn't exist. Refactored to use `BaseAction` and removed the name spacing to satisfy Zeitwerk autoloading
=> Fix typo on action generator template name

lib/avo/base_resource.rb
Instead of rejecting custom fields if the license lacked that ability, it rejected them if the license had that ability.
=> fix: license has -> lacks ability

Gemfile.lock, avo.gemspec, gemfiles/rails_6.0_ruby_2.6.gemfile.lock, gemfiles/rails_6.0_ruby_2.7.gemfile.lock, gemfiles/rails_6.1_ruby_2.6.gemfile.lock, gemfiles/rails_6.1_ruby_2.7.gemfile.lock
Fixes https://github.com/avo-hq/avo/issues/441
=> refactor: remove ransack as a gem dependency

app/controllers/avo/application_controller.rb
Following #461 , current implementation forbids using `ActiveStorage` with UUID-based records raising a 500 error on ressources that feature a `FileField`.
In the`Avo::ApplicationController#eager_load_files` method, changing the call to `#eager_load` into `includes` solves that problem. I don't think it should affect performance in a dramatic way, but let me know what you think.
Fixes https://github.com/avo-hq/avo/issues/461
=> Allow file fields to work with UUID-based records

app/components/avo/index/resource_table_component.html.erb, app/helpers/avo/resources_helper.rb, app/packs/js/controllers/item_select_all_controller.js, app/views/avo/partials/_table_header.html.erb, lib/generators/avo/templates/locales/avo.en.yml, spec/system/avo/select_spec.rb
Simple Stimulus controller which uses JS to click all select buttons on the page at once, and additionally ensures the status of the checkbox is consistent with the row checkboxes.
The implementation isn't efficient and might get slow with very large pages, but felt like the simplest option for now that could work.
First proper PR - feedback very welcome! Happy to work on improving this as needed.
Closes #452.
=> feature: Select all on controller

app/components/avo/views/resource_show_component.html.erb
This branch adds the `edit` button to the `has_one` field.
Note that this introduces a situation wherein the `detach` and `edit` buttons are situated right next to each other, both of which are conventionally solid indigo. Not a terribly huge deal, but just thought I'd mention it.
=> Add edit link to has_one field

lib/avo/app.rb
Using as example fish resource
```ruby
class FishResource < Avo::BaseResource
self.model_class = Fish
self.title = :id
self.includes = []
field :id, as: :id
end
```
For this resources in draw_routes we need to call resource method with `fish` param, to build routes right to avo.
But the line `resource.model_class.model_name.route_key `returns fish_index, and routes were generated in the wrong way, so i change this line to use plural method from active model naming and its works.
References:
- https://api.rubyonrails.org/classes/ActiveModel/Naming.html#method-c-route_key
- https://markembling.info/2011/06/uncountable-nouns-rails-3-resource-routing
=> fix: route key for uncountable resource

lib/avo/base_resource.rb, lib/avo/fields/base_field.rb
* Supports new Resources' attribute for i18n called `translation_enable` to use translations key using convention `avo.resource_translations` and `avo.field_translations`. The goal is to avoid having to declare a translation key for each resource and field, and just use a convention.
* Fixes i18n on Fields as it's not currently working.
=> I18n resources

app/controllers/avo/actions_controller.rb, lib/avo/base_action.rb, lib/generators/avo/templates/action.tt, spec/dummy/app/avo/actions/dummy_action.rb, spec/dummy/app/avo/actions/toggle_admin.rb, spec/dummy/app/avo/actions/toggle_inactive.rb, spec/dummy/app/avo/actions/toggle_published.rb
Fixes https://github.com/avo-hq/avo/issues/541
This adds `current_user` and `resource` to actions context. 
You need to update all your actions to support the new arguments.
```diff
-  def handle(models:, fields:)
+  def handle(**args)
+    models, fields, current_user, resource = args.values_at(:models, :fields, :current_user, :resource)
```
=> feature: expose user and resource in actions

lib/generators/avo/templates/filters/boolean_filter.tt
NOTE: I didn't manage to get the tests running locally!
Boolean filter receives a hash of key-values: keys being names/strings/features/flags and values being `true` or `false` (selected or not)
Example `values`:
```rb
> values
{
"Cart Button Effects": true,
"Customer Scarcity Timer": false,
"Discount Pop": false,
"IQ Slider": false
}
```
=> Fix: Rename boolean filter argument `value` => `values`

app/controllers/avo/home_controller.rb, app/packs/entrypoints/application.js, app/views/avo/home/failed_to_load.html.erb, app/views/avo/partials/_failed_state.html.erb, config/routes.rb, lib/generators/avo/templates/locales/avo.en.yml, spec/dummy/config/locales/avo.en.yml
Before, when a frame was failing, the user didn't get any feedback.
Fixes https://github.com/avo-hq/avo/issues/583
=> chore: failed frame loading state

lib/avo/configuration.rb, lib/avo/services/authorization_service.rb, spec/requests/avo/authorization/raise_error_on_missing_policy_spec.rb
https://docs.avohq.io/1.0/authorization.html#raise-errors-when-policies-are-missing
=> refactor: raise_error_on_missing_policy

.github/PULL_REQUEST_TEMPLATE.md, app/components/avo/panel_component.html.erb, app/components/avo/panel_component.rb, app/components/avo/views/resource_edit_component.html.erb, app/components/avo/views/resource_index_component.html.erb, app/components/avo/views/resource_new_component.html.erb, app/components/avo/views/resource_show_component.html.erb, lib/avo/base_resource.rb, spec/dummy/app/avo/resources/person_resource.rb, spec/dummy/app/avo/resources/user_resource.rb, spec/features/avo/resource_description_spec.rb
Fixes #633 and https://github.com/avo-hq/avo/discussions/584
=> feature: description for resource

lib/avo/fields/key_value_field.rb
The `key_value_field` translations don't currently in some cases (haven't figured exactly when it does). But the problem is the order in which Avo is loaded (and `key_value_field` class is instantiated) and when rails loads the translations. I've found that usually, other language translations are loaded after Avo has instantiated this class, so the default English translations are assigned.
1. Step 1
1. Step 2
=> Fix key_value_field translation

app/components/avo/fields/belongs_to_field/edit_component.html.erb, spec/features/avo/belongs_to_spec.rb
Fixes a weird issue where it created a related `belongs_to` but it didn't really allow the redirect to the created resource because the belongs_to dropdown was disabled.
=> fix: related belongs to does not allow for proper resource creation

.github/PULL_REQUEST_TEMPLATE.md, app/javascript/js/controllers/fields/date_field_controller.js, spec/system/avo/date_spec.rb
Fixes https://github.com/avo-hq/avo/issues/658
1. Change the browser timezone to `America/Chicago` (or any western TZ) 
1. Go to a resource with a date field.
1. Edit that resource, save, edit, save at least twice.
1. The date you set should be the same
1. You should get the same results on an eastern TZ
=> fix: date object alters date based on timezone

README.md, app/views/avo/partials/_turbo_frame_wrap.html.erb, db/factories.rb, spec/dummy/app/avo/resources/comment_resource.rb, spec/dummy/app/models/comment.rb, spec/dummy/db/seeds.rb, spec/system/avo/has_many_spec.rb
Fixes https://github.com/avo-hq/avo/issues/661
1. Create a post with a few comments attached.
2. go to that post
3. delete a few comments
4. for each deleted comment you should have the "resource destroyed" notification
=> fix: notifications delayed in turbo frames

lib/generators/avo/templates/locales/avo.en.yml, lib/generators/avo/templates/locales/avo.nb-NO.yml, lib/generators/avo/templates/locales/avo.pt-BR.yml, lib/generators/avo/templates/locales/avo.ro.yml, spec/dummy/config/locales/avo.en.yml
When add my first "Tool", I ran into a missing i18n key.
Adding to all languages. NOTE: I don't know the other languages so this was just a lookup via google translate
=> fix: Add 'tools' key to i18n

app/components/avo/navigation_link_component.html.erb, app/components/avo/navigation_link_component.rb
While working on adding out some custom tools, some of the items I'm linking to are provided by other gems (Sidekiq, PGHero, etc.) and I'd like to pop them in new windows. This option will allow me to specify a target of `_blank`.
=> feature: Allow Avo::NavigationLinkComponent to accept an optional target param

app/controllers/avo/application_controller.rb, app/controllers/avo/base_controller.rb
This should fix a bug we introduced with the `fill_model` method.
Fixes https://github.com/avo-hq/avo/pull/612#issuecomment-1037199884
Use a `create?` policy method and test you receive a filled `record` not an empty record class.
=> fix: fill model beofre authorizing an action

app/controllers/avo/application_controller.rb
Pundit 2.2.0 changes the Module that is required to be included, which is a breaking change. Since Pundit 2.1.x is still very viable for most apps, support both options.
=> fix: Support older version of Pundit

app/javascript/avo.js, app/views/avo/partials/_turbo_frame_wrap.html.erb, spec/rails_helper.rb, spec/support/helpers.rb, spec/system/avo/app_spec.rb
Fixes https://github.com/avo-hq/avo/issues/687
You should only see one alert in the following scenarios:
1. delete a comment from the comments page
2. delete a comment from the projects has_many page
=> fix: duplicated alerts

.github/ISSUE_TEMPLATE/bug_report.md, db/factories.rb, lib/avo/base_resource.rb, lib/avo/fields/belongs_to_field.rb, spec/dummy/app/avo/resources/user_resource.rb, spec/features/avo/belongs_to_spec.rb, spec/system/avo/belongs_to_spec.rb
Fixes https://github.com/avo-hq/avo/issues/668
1. Go to a team. The reviews should not have a reviewable column
2. go to a post. the comments should not have a commendable column
3. go to a user. the comments should not have a user column
=> fix: some association fields are invisible in has_many index views

app/components/avo/navigation_link_component.rb, app/controllers/avo/base_controller.rb, spec/dummy/app/avo/resources/person_resource.rb, spec/dummy/app/models/person.rb
[This](https://github.com/avo-hq/avo/pull/685) PR introduced this bug that fully reloads a page when you click a sidebar item instead of it using Turbo.
=> fix: sidebar navigation link default  target forces reload

Gemfile.lock, app/controllers/avo/application_controller.rb, app/views/avo/partials/_profile_dropdown.html.erb, spec/support/wait_for_loaded.rb
This PR adds a `before_action` to the main `ApplicationController` that changes the `I18n.locale` and `I18n.default_locale` based on the `locale` param.
=> chore: initial locale support

app/javascript/js/controllers/modal_controller.js, app/views/avo/actions/show.html.erb, lib/avo/base_action.rb, spec/dummy/app/avo/actions/download_file.rb, spec/dummy/app/avo/resources/user_resource.rb, spec/dummy/dummy-file.txt, spec/rails_helper.rb, spec/support/download_helpers.rb, spec/system/avo/actions_spec.rb
Fixes https://github.com/avo-hq/avo/issues/700
1. Go to users
2. click Actions
3. click download file
4. click run. you should get a `dummy-content.txt` file downloaded and the modal should close
5. Open the action again and check the "read from file" checkbox. 
6. click run. you should get a `dummy-file.txt` file downloaded and the modal should close
=> fix: turbo breaks action downloads

app/components/avo/turbo_frame_wrapper_component.html.erb, app/controllers/avo/application_controller.rb
* It should render the alerts only if it is a turbo frame request.
* If it is rendered on a normal page load, for example, a redirect then it should not render the alerts again, since they are rendered from the layout.
* When turbo_frame_wrap is rendered as a part of normal page load, alerts are rendered twice leading to duplicate alerts. So rendering the AlertsComponent only when a turbo_frame is requested.
- [x ] I have performed a self-review of my own code
This bug was happening in our production app. After this fix it is not happening anymore.
=> turbo_frame_wrap: render alerts only for turbo requests

lib/avo/base_resource.rb, spec/dummy/app/models/user.rb
=> fix: missing inverse_of crashes has_many association

lib/avo/base_resource.rb, spec/features/avo/show_page_spec.rb
Because of how the `Show` panels are rendered, if a record has an empty title the default panel is hidden.
1. Create a fish with no name.
2. Visit that fish
3. the panel should be visible
=> fix: records with no title have show view broken

app/components/avo/actions_component.html.erb, app/components/avo/panel_component.html.erb, app/components/avo/panel_component.rb
Move the dropdown to the left on small screens.
=> fix: alert dropdowns on small screens

lib/avo/base_action.rb
Fixes https://github.com/avo-hq/avo/issues/738
=> fix: downloads in actions won't work for forms with data-remote=true

app/components/avo/blank_field_component.rb, lib/avo/fields/base_field.rb, spec/components/avo/blank_field_component_spec.rb
Fixes https://github.com/avo-hq/avo/issues/743.
This is a possible fix on the sporadically crashes when a lot of `has_many` turbo frames are present on the page.
Go on a page where the `has_many` turbo frame was failing sporadically. Try and see if it still does that. If it still does it, then, this doesn't fix it.
I haven't been able to trigger the crash on my end.
=> fix: has_many turbo frame crash

app/components/avo/referrer_params_component.html.erb, app/components/avo/referrer_params_component.rb, app/components/avo/views/resource_edit_component.html.erb, app/components/avo/views/resource_new_component.html.erb, app/controllers/avo/base_controller.rb, spec/components/avo/referrer_params_component_spec.rb, spec/dummy/app/models/comment.rb
Fixes https://github.com/avo-hq/avo/issues/693
1. Go to a Post
2. create a comment with the body `bb` and another with a different body. both should be attache to the that post
3. return to the post and hit edit on the second comment (not the `bb` one)
4. try to edit it and set the body to `bb`
5. the validation should fail and keep you on that page
6. when you change the body to something else the validation passes and you are redirected to that post.
=> fix: wrong redirect after validation failed when wediting a has many association

app/controllers/avo/search_controller.rb, lib/avo/base_resource.rb, spec/dummy/app/avo/resources/team_membership_resource.rb, spec/features/avo/hidden_from_global_search_spec.rb, spec/rails_helper.rb, spec/support/request_helpers.rb
Fixes https://github.com/avo-hq/avo/issues/688
[Docs](https://docs.avohq.io/2.0/search.html#hide-a-resource-from-the-global-search)
1. Go to the team memberships (http://localhost:3030/admin/resources/team_memberships) and open the resource search. That should work
2. Try researching in global search. The team memberships should be hidden from that search.
=> feature: hide resources from global search

lib/avo/fields/date_field.rb
This fixes a deprecation warning in Rails 7 where dates should be formatted using `to_formatted_s` when passing a named format type.
Tried in my existing app and everything seems fine. `to_s` simply forwarded to `to_formatted_s`, so it's a benign change.
=> Rails 7 deprecates Date#to_s in favor of Date#to_formatted_s

lib/avo/fields/date_field.rb
=> Avo 1.x Backport: Rails 7 deprecates Date#to_s in favor of Date#to_formatted_s

app/components/avo/sidebar_component.html.erb
Adds a new partial at the end of the sidebar for more customization (ie: in my case, I needed to add more items of custom reports I've created)
Description...
1. Step 1
1. Step 2
=> Add sidebar extra partial for custom sidebar elements

app/components/avo/sidebar_profile_component.html.erb
When user doesn't have a `title` and / or `avatar`, the username is misaligned.
Description...
1. Step 1
1. Step 2
=> Minor improve sidebar profile component

app/components/avo/panel_component.html.erb, lib/avo/reloader.rb
This PR also contains a tiny rename in the reloader.
=> fix: panel component title alignment

app/controllers/avo/application_controller.rb
A `before_action` broke the trix attach action
=> fix: trix attach action

app/controllers/avo/application_controller.rb
`params[:locale]` renamed to `params[:set_locale]`
Fixes https://github.com/avo-hq/avo/issues/828
We initially put the `locale` param as a temporary fix to allow users to edit multilingual content. The multilingual content editor is not really a feature yet and we'll probably tweak it when we make it a feature.
=> fix: change param from locale->set_locale

.codeclimate.yml, app/components/avo/sidebar/group_component.html.erb, app/components/avo/sidebar/heading_component.html.erb, app/components/avo/sidebar/heading_component.rb, app/components/avo/sidebar/section_component.html.erb, app/javascript/avo.js, app/javascript/js/controllers/menu_controller.js, spec/dummy/config/initializers/avo.rb
This forces Avo to use the default state for collapsable menus. That means that you'll get more control and less jitter until the local storage values are retrieved.
=> refactor: use default cllapsed state for menus

lib/avo/services/authorization_service.rb
Fixes https://github.com/avo-hq/avo/issues/851
=> fix: authorization logic error

CONTRIBUTING.MD, app/components/avo/views/resource_index_component.html.erb, app/controllers/avo/actions_controller.rb
Fix the JS error when selecting a checkbox on an Index page that has no search query defined in the resource.
Fixes # [(861)](https://github.com/avo-hq/avo/issues/861)
- [~] I have added tests that prove my fix is effective or that my feature works
1. Load the dummy app.
2. Click on the "People" resource
3. Open the JS console.
4. Click any checkbox.
5. Ensure the JS console has no errors.
6. Ensure the `data-selected-resources` element is populated with IDs that were selected.
=> WIP Fix/toggle without search query

app/components/avo/sidebar_component.html.erb, app/views/avo/partials/_footer.html.erb, app/views/avo/partials/_navbar.html.erb, lib/avo/configuration.rb, lib/generators/avo/templates/initializer/avo.tt
Not sure if it's worth adding this at this point as I think you are working on a UI revamp, but thought I would share it regardless in case you want to merge it.
When printing through the browser, it will hide the header, sidebar and footer as they are usually not required / useful.
Description...
1. Step 1
1. Step 2
=> Hide header, sidebar and footer when print in browser

app/components/avo/edit/field_wrapper_component.html.erb, app/components/avo/edit/field_wrapper_component.rb, app/components/avo/fields/belongs_to_field/autocomplete_component.html.erb, app/components/avo/fields/belongs_to_field/autocomplete_component.rb, app/components/avo/fields/belongs_to_field/edit_component.html.erb, app/components/avo/views/resource_index_component.rb, app/controllers/avo/associations_controller.rb, app/controllers/avo/search_controller.rb, app/helpers/avo/url_helpers.rb, app/javascript/js/controllers/search_controller.js, lib/avo/fields/belongs_to_field.rb, lib/avo/fields/has_base_field.rb, lib/avo/hosts/association_scope_host.rb, lib/avo/services/authorization_service.rb, spec/dummy/app/avo/resources/comment_resource.rb, spec/dummy/app/avo/resources/review_resource.rb, spec/dummy/app/avo/resources/user_resource.rb, spec/features/avo/belongs_to_spec.rb, spec/features/avo/has_many_field_spec.rb, spec/features/avo/record_passed_to_scope_spec.rb
This empowers the scope for associations by providing access to the `parent` record.
[Docs](https://docs.avohq.io/2.0/associations.html#add-scopes-to-associations)
1. Go to the review with the id of 1
2. update the body to start with the letter A
3. create a team that contains the letter A
4. create a team that doesn't contain the letter A
5. go back to that review (1)
6. search for teams
7. only the team that contains the letter A should show up in the search
=> feature: pass record to association scope

app/controllers/avo/associations_controller.rb, app/controllers/avo/search_controller.rb, lib/avo/fields/belongs_to_field.rb, lib/avo/fields/has_base_field.rb, spec/dummy/app/avo/resources/post_resource.rb, spec/dummy/app/avo/resources/review_resource.rb, spec/dummy/app/avo/resources/user_resource.rb, spec/dummy/app/models/project.rb, spec/features/avo/has_many_attach_scope_spec.rb
This PR introduces a new scope for the association attach screen. It also changes the `belongs_to` option from `scope` to `attach_scope`.
1. Go to a user
2. Click on attach post
3. attach one post
4. attach another
5. check that the initial post is not present in the list anymore
=> feature: attach_scope for associations

app/javascript/js/controllers/search_controller.js, app/views/avo/partials/_global_search.html.erb, app/views/avo/partials/_resource_search.html.erb
Fixes an issue where when you click the browser back button, the search box is broken and unusable.
1. Go to the users page
3. click on a user
4. click on the browser back button
5. after each step, check that the search works
=> fix: broken search on back action

app/components/avo/sidebar_component.html.erb
If a model name is long, it causes the sidebar to overlap with the main content of the page, setting a max width at medium fixes the issue.
Create a resource with a long class name and the sidebar no longer overlaps.
=> fix: Long model names cause the navigation labels to overlap with the main content

app/components/avo/paginator_component.html.erb
=> fix: broken pagination on per page switch

lib/avo/hosts/base_host.rb, spec/dummy/config/initializers/avo.rb, spec/features/avo/belongs_to_polymorphic_spec.rb, spec/support/wait_for_loaded.rb
Allows the user to authorize a menu item more easily.
=> feature: authorization in menus

app/components/avo/fields/has_one_field/show_component.html.erb, app/components/avo/views/resource_show_component.html.erb, app/components/avo/views/resource_show_component.rb, spec/dummy/app/avo/resources/user_resource.rb, spec/system/avo/has_one_field_name_spec.rb
Has_one field now display the chosen name in resource file
added name for has_one fields and check if appear on show page
=> return field name if field is has_one

app/assets/svgs/download-solid-reversed.svg
The 'Move record to top' button was not correctly oriented on Safari. Moving the `translate` parameter to the `path` element (and adjusting the origin accordingly) sorted this in both browsers.
Confirm that the icon is correctly oriented:
1. Visit `http://127.0.0.1:3030/admin/resources/course_links`
=> Fix rotation of move to top button

app/javascript/js/controllers/fields/tags_field_controller.js
The tags field had a hardcoded limit of 10 tags - this meant that any extra tags were being removed in the UI. Saving the record would then remove these extra tags.
I couldn't see any specific reason for the tag limit. Perhaps it would be worthwhile allowing this limit to be defined in the UI? I'm not familiar with `acts_as_taggable_on` but if a limit can be defined there (or in a validation) we could try to use that?
I was using the tags field as a simpler way to add multiple associations though, so a limit wasn't desired. This was my field definition for reference (although for bonus confusion, the association is called 'tags' 😂):
```ruby
field :tag_ids,
name: "Tags",
as: :tags,
hide_on: [:show, :index, :new],
close_on_select: false,
enforce_suggestions: true,
suggestions: -> {
record …
```
=> Remove max limit on tags field

app/controllers/avo/base_controller.rb
Fixes an issue where the breadcrumbs are not properly set when on the create screen form an association.
=> fix: show proper breadbcrumbs on associated create view

app/controllers/avo/base_controller.rb
Moving set actions after the resource is hydrated with the model allows access to the model in self.visible lambda via resource.
Also few of these lines seemed like unnecessary old code, model is available via `@model` instance variable.
Could not access the model in the visible lambda of action when determining whether an action should be shown on a particular page. With this you should be able to access it using `resource.model`.
- [ x] I have performed a self-review of my own code
=> Access resource.model in action visibility

app/javascript/js/controllers/menu_controller.js
Fixes https://github.com/avo-hq/avo/issues/939
1. Add a menu item that is collapsed
2. go and expand it
3. refresh the page
4. observe it remains expanded
=> fix: sidebar menu collapsed state

app/components/avo/alert_component.rb, app/controllers/avo/actions_controller.rb, lib/avo/base_action.rb, spec/dummy/app/avo/actions/toggle_inactive.rb
Fixes https://github.com/avo-hq/avo/issues/919
Adds the `silent` response to actions. When you call `silent` and no other messages, nothing will be displayed to the user.
=> feature: add the ability to run an action silently

app/views/avo/base/_select_filter.html.erb, app/views/avo/base/_text_filter.html.erb, spec/dummy/app/avo/filters/published_filter.rb, spec/dummy/app/avo/filters/user_names_filter.rb, spec/system/avo/filters/filters_spec.rb
Now it's possible to customize the default blank text on a select filter using the option `blank: "custom text"` or let it by default ( "-" )
- [ x ] I have performed a self-review of my own code
1. Go to file `published_filter.rb` and add  `blank: "Select status"` to `def options{ ... }`
2. Go to `/admin/resources/posts` open filters and confirm if blank changed
=> feature: custom blank text on select filter

app/views/avo/partials/_table_header.html.erb
Fixes https://github.com/avo-hq/avo/issues/934
=> fix: right align table headers

app/helpers/avo/url_helpers.rb, lib/avo/base_resource.rb, lib/avo/dynamic_router.rb, spec/dummy/app/avo/resources/membership_resource.rb, spec/dummy/app/avo/resources/team_resource.rb, spec/dummy/app/controllers/avo/memberships_controller.rb, spec/dummy/app/controllers/avo/team_memberships_controller.rb, spec/features/avo/hidden_from_global_search_spec.rb, spec/features/avo/multiple_names_model_spec.rb, spec/features/avo/resource_name_urls_spec.rb, spec/features/avo/resources_hidden_from_sidebar_spec.rb, spec/system/avo/default_field_spec.rb
Fixes https://github.com/avo-hq/avo/issues/950
Fixes https://github.com/avo-hq/avo/discussions/846
1. Go to the membership resource
2. Observe it's feeding off of the `TeamMembership` model but has the path `/memberships`, thus respecting the resource name not the model name.
=> fix: use resource name for url instead of model name

lib/avo.rb
=> chore: add generators dir to zetwerk ignore

app/components/avo/fields/belongs_to_field/edit_component.html.erb, app/components/avo/fields/belongs_to_field/edit_component.rb
Fixes a bug where the action attributes were not properly passed to the input.
Before:
```erb
<select class="appearance-none inline-flex bg-gray-25 disabled:cursor-not-allowed text-gray-600 disabled:opacity-50 rounded py-2 px-3 leading-tight border focus:border-gray-600 focus-visible:ring-0 focus:text-gray-700 border-gray-200 {} w-full"
data-resource-edit-target="reviewableBelongsToInput" 
data-action="change->belongs-to-field#changeType {:&quot;resource-edit-target&quot;=>&quot;reviewableBelongsToInput&quot;}"
data-belongs-to-field-target="select" 
name="review[reviewable_type]" 
id="review_reviewable_type"
><option value="">Choose an option</option>
<option value="Fish">Fish</option>
<option value="Post">Post</option>
<option selected="selected" value="Project">Project</option>
<option …
```
=> fix: proper action data tag for belongs to field

app/views/avo/partials/_custom_tools_alert.html.erb, lib/avo/app.rb, lib/avo/concerns/fetches_things.rb, spec/features/avo/resource_missing_model_spec.rb
Fixes an issue where Avo would crash if the developer generated a resource without a valid model.
1. Run `rails g avo:resource bad`
2. Go to Avo. Maybe refresh the page once if it doesn't show up
3. Notice the error message like in the screenshot 👆
=> chore: alert developer about missing model

app/components/avo/views/resource_edit_component.rb
Following the recent refactoring, a little authorization bug slipped through : the `can_see_the_save_button?` would call the `:edit` action, even on `:new` action. Therefore the `save` button would not appear despite correct authorization rules.
=> fix: hard-coded policy action called on ResourceEditComponent

app/components/avo/fields/date_field/edit_component.html.erb, app/components/avo/fields/date_time_field/edit_component.html.erb, app/javascript/js/controllers/fields/date_field_controller.js, lib/avo/fields/date_field.rb
Fixes #975 
1. Configure a resource with date field
2. Specify a custom format for date and set `disable_mobile` to `true`
3. Go to new/edit page in web & mobile browsers
**Example:**
```ruby
field :date, as: :date, required: true, picker_format: 'd F, Y', format: '%d %B, %Y', default: Date.today, disable_mobile: true
```
**Output:**
=> fix: date field format in mobile browsers

app/components/avo/fields/common/key_value_component.html.erb
Fixes an issue where the view used was `new` instead of `create` making the key value field inoperable in some scenarios.
https://discord.com/channels/740892036978442260/740893011994738751/992514007846105128
=> fix: key value field new->create view

lib/avo/licensing/h_q.rb, spec/features/avo/h_q_spec.rb
This gracefully catches SSL errors with avohq.io. Instead of crashing the app it keeps it still usable.
=> chore: don't crash Avo if SSL error raised

app/controllers/avo/application_controller.rb, lib/avo/app.rb, lib/avo/configuration.rb, spec/dummy/config/application.rb, spec/dummy/config/initializers/avo.rb
Fixes https://github.com/avo-hq/avo/issues/1022
[Docs](https://docs.avohq.io/2.0/localization.html#setting-the-locale)
1. De-comment the locale testing helpers in application.rb
2. Load Avo
3. Observe it uses `fr` locale
4. add the `force_locale=ro` param
5. Observe it uses the to locale
6. Navigate to another page
7. Observe it still uses `ro` and the param is still present
8. Remove the param
9. Observe it switched back to `fr`
10. Use the `set_locale=ro` param
11. Observe it uses the to param
12. Navigate to another page
13. Observe it uses to and the param is gone
=> fix: locale configuration broken

lib/avo/concerns/has_fields.rb
Fixes https://github.com/avo-hq/avo/issues/979
=> fix: inverse of crashing association screen

app/components/avo/fields/date_time_field/index_component.html.erb, app/components/avo/fields/date_time_field/show_component.html.erb, app/javascript/js/controllers/fields/date_field_controller.js, spec/dummy/app/avo/resources/project_resource.rb
Fixes https://github.com/avo-hq/avo/issues/1079
1. Set the birthday of a user to the 20th
1. set the browser timezone to `CST`
2. observer the date on index and show views is actually 20th, not 19th
3. checkt the time field to make sure it updates properly
=> fix: date field wrongly subtracts time zone offsets

app/components/avo/fields/text_field/index_component.html.erb, app/components/avo/fields/text_field/show_component.html.erb, lib/avo/fields/text_field.rb, spec/dummy/app/avo/resources/user_resource.rb
Adds the `protocol` option to the text field.
`field :email, as: :email, protocol: :mailto` to create a mailto link. Same for `tel` links.
1. Go to a user index page
2. Click a user's email
3. observe the browser opening a new window to compose an email
4. do the same on show
=> feature: protocol option for text field

bin/init
System specs won't run unless assets are compiled
(if you try, you get a lot of errors about missing
assets).
I've added commands to the init script to build
assets in the same way as the github actions test
workflow does, and this allows tests to run (after
running the init script).
1. Check out main branch in a new directory
1. Run `bin/init`
3. Run `bundle exec rspec --fail-fast spec/system`
4. Look for errors due to missing assets
5. Switch to this branch
6. Run `bin/init`
3. Run `bundle exec rspec --fail-fast spec/system`
4. There should be no errors
=> Made sure the init script builds assets

app/components/avo/fields/trix_field/edit_component.rb
There's a bug in the trix field at the moment, where the `input` attribute of the `<trix-editor>` tag can include spaces whenever you have a resource with more than one word in it's name. If you have a resource named `MyPost` then `@resource.name` will be `My post`, `@resource.name.underscore` will be `my post` and therefore `trix_id` will be `trix_my post_foo` (if the field is named `foo`).
To fix this I've changed it to use the class name instead of the human readable name, then calling underscore on that.
I couldn't figure out how to test this - the only place the trix field is tested right now is in a system spec and I couldn't see how to change the resource name there without causing a lot more changes. I think this could be tested easily in a unit test but it looks …
=> Fix trix input name for resources with more than one word in their name

app/components/avo/common_field_wrapper_component.html.erb, app/components/avo/index/field_wrapper_component.html.erb, docker/Dockerfile
Adds the ability to debug the field value by appending `?avo_debug=1` to the URL. It works on the `Index` and `Show` views.
When doing that, the raw value of a field is displayed in an HTML comment.
1. Go to `/admin/users?avo_debug=1`
2. Inspect a field value
3. See that the field value has a comment with the raw value
=> chore: add `avo_debug` param

app/javascript/js/controllers/fields/key_value_controller.js, spec/system/avo/key_value_field/key_value_field_spec.rb
Right now null values in a key value field appear as "null", but I'd expect them to appear
as "".
1. Find a resource with a key value field
1. Using the rails console, find a record for this resource and add a new key-value entry with a null value to the field
1. Edit this resource in avo
1. The new key-value entry should have a blank value, rather than "null"
=> Make sure null appears as "" in key value fields

lib/avo/concerns/has_fields.rb
Fixes [this](https://discord.com/channels/740892036978442260/740893011994738751/1001527120503251094) issue
1. Got to a fish show page
2. observe the tool comes before the fields
=> fix: allow tools to come before fields

app/components/avo/views/resource_show_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/1110
1. Go to a team page
2. ensure the admin is attached
3. see that the admin has only the main panel displayed and no other tabs
=> fix: has one field show only main panel

app/controllers/avo/base_controller.rb, app/javascript/js/controllers/fields/date_field_controller.js, lib/avo/fields/date_time_field.rb
While updating the date/date_time picking implementation, we lost the ability to set the value to empty.
Previously, there was an avo date_field_controller.js exception that was raise that would bail out of the `onChange` when the input field was empty.
-  [x] I have performed a self-review of my own code
1. Utilize a `date` or `date_time` field
2. Manually clear the input field
3. Check it works :)
=> Support `date` and `date_time` to clear the value

app/components/avo/item_switcher_component.html.erb, app/controllers/avo/application_controller.rb, app/controllers/avo/base_controller.rb, lib/avo/base_resource.rb, spec/dummy/app/avo/resources/fish_resource.rb, spec/dummy/app/models/fish.rb, spec/dummy/app/views/avo/resource_tools/_fish_information.html.erb, spec/dummy/db/migrate/20220727112241_add_type_to_fish.rb, spec/dummy/db/schema.rb, spec/features/avo/custom_fields_in_resource_tools_spec.rb
[Docs](https://docs.avohq.io/2.0/resource-tools.html#add-custom-fields-on-forms)
The idea behind this implementation is that you can add a resource tool to your new/edit screen and add the fields you need there. 
You'll have access to the `form` object. 
In your resource file, you must specify the `extra_params` option, so Rails knows to permit those params in the controller and fill them into the model.
Next, in your model file, you create the setters to take the values passed by the user and use them as you need it.
In our example `fish.rb` we just write to a different `type` field in the DB just to show that the value reaches that point, but you can do whatever you need. You may need to add some nested data and will send the data as an array and you would create your nested attributes …
=> feature: allow custom fields in resource tools

lib/avo/concerns/has_fields.rb, lib/avo/hosts/base_host.rb
Fixes https://github.com/avo-hq/avo/issues/1123
1. Configure a resource to have a `heading` as the first item in the DSL
1. Observe the show page loads
=> fix: heading can't be the first item in your resource

app/components/avo/fields/has_one_field/show_component.html.erb, app/components/avo/item_switcher_component.html.erb, app/components/avo/panel_component.rb, app/components/avo/views/resource_edit_component.html.erb, app/components/avo/views/resource_index_component.html.erb, app/components/avo/views/resource_show_component.html.erb, app/views/avo/dashboards/show.html.erb, app/views/avo/debug/index.html.erb, app/views/avo/home/index.html.erb, app/views/avo/private/design.html.erb, spec/dummy/app/views/avo/resource_tools/_fish_information.html.erb, spec/dummy/app/views/avo/resource_tools/_user_tool.html.erb, spec/dummy/app/views/avo/tools/custom_tool.html.erb
Prepare `Avo::PanelComponent` for public consumption.
=> refactor: tweak panel component

app/components/avo/fields/tags_field/show_component.rb, app/components/avo/tab_group_component.html.erb, app/components/avo/tab_switcher_component.rb, app/components/avo/views/resource_edit_component.rb, app/controllers/avo/base_controller.rb, app/views/avo/associations/new.html.erb, lib/avo/fields/base_field.rb
Fixes an issue where if you resubmitted a form (create or update), some data would be lost (actions, breadcrumbs, and some other state), and sometimes the edit screen would become the create screen.
=> fix: failed forms can't be resubmitted

app/javascript/js/controllers/menu_controller.js
The deafault `collapsed` option for menu sections was not working. The default state is correctly set, but incorrectly read in the Stimulus controller, the bug was introduced in #941.
Basically, on the first load (and if the user never interacted with the collapse feature) the `this.userState` will return `null`, because there is no such key in the local storage. `this.userState === 'collapsed'` will always return false if the user never toggled the collapse feature, making the default option useless.
The fix is using the defaultState if userState is unefined/null.
1. Create a section with  `collapsable: true, collapsed: true`
2. Delete local storage (clean cookies) to ensure there are no user preferences overriding the default
2. Check if the section appears collapsed.
=> Fix sidebar default collapsed state

app/components/avo/views/resource_show_component.html.erb, lib/avo/concerns/has_editable_controls.rb
Fixes a small issue where if you left the `show_controls` block empty, you would crash Avo.
=> refactor: allow empty show_controls block

CONTRIBUTING.MD, app/controllers/avo/base_controller.rb, spec/dummy/app/controllers/avo/courses_controller.rb, spec/dummy/app/models/course.rb, spec/features/avo/exposed_methods_base_controller_spec.rb
Besides `after_create_path` and `after_update_path` it's possible now to override the method `after_destroy_path`. This three methods gives the path to redirect after the create, update and destroy succeed.
It's also possible to customize the messages for each action (create, update and destroy) success or fail by overriding:
- Create
Success  ->    `create_success_message`
Error      ->    `create_fail_message`
- Update
Success  ->    `update_success_message`
Error      ->    `update_fail_message`
- Destroy
Success  ->    `destroy_success_message`
Error      ->    `destroy_fail_message`
Now it's possible to override completely the response of each **C**r**UD** action both on success and failure:
- Create
Success  ->    `create_success_action`
Error      ->    `create_fail_action`
- …
=> feature: Custom path and message after create update and delete

app/controllers/avo/search_controller.rb
Fixes [this issue](https://discord.com/channels/740892036978442260/740893011994738751/1010185907992801291) where the search is not paginated and Avo tries to return all the results. This causes a crash when there are too many results.
=> fix: search pagination unlimited

app/components/avo/fields/belongs_to_field/edit_component.rb, app/components/avo/fields/boolean_field/edit_component.html.erb, app/components/avo/fields/boolean_group_field/edit_component.html.erb, app/components/avo/fields/code_field/edit_component.html.erb, app/components/avo/fields/country_field/edit_component.html.erb, app/components/avo/fields/date_field/edit_component.html.erb, app/components/avo/fields/date_time_field/edit_component.html.erb, app/components/avo/fields/external_image_field/edit_component.html.erb, app/components/avo/fields/file_field/edit_component.html.erb, app/components/avo/fields/files_field/edit_component.html.erb, app/components/avo/fields/has_one_field/show_component.html.erb, app/components/avo/fields/markdown_field/edit_component.html.erb, app/components/avo/fields/markdown_field/show_component.html.erb, app/components/avo/fields/number_field/edit_component.html.erb, app/components/avo/fields/password_field/edit_component.html.erb, app/components/avo/fields/progress_bar_field/edit_component.html.erb, app/components/avo/fields/select_field/edit_component.html.erb, app/components/avo/fields/status_field/edit_component.html.erb, app/components/avo/fields/tags_field/edit_component.html.erb, app/components/avo/fields/text_field/edit_component.html.erb, app/components/avo/fields/textarea_field/edit_component.html.erb, app/components/avo/fields/trix_field/edit_component.html.erb, lib/avo/fields/base_field.rb, lib/avo/fields/concerns/is_readonly.rb, lib/generators/avo/templates/field/components/edit_component.html.erb.tt, spec/dummy/app/avo/resources/fish_resource.rb, spec/dummy/app/components/avo/fields/color_picker_field/edit_component.html.erb, spec/features/avo/readonly_takes_a_block_spec.rb, spec/features/avo/required_takes_a_block_spec.rb
This adds support for making the `readonly` field take a proc, just like required (implemented in https://github.com/avo-hq/avo/pull/955)
With support from @ncsmith24
=> feature: Callable readonly

app/javascript/js/controllers/fields/date_field_controller.js
Fixes https://github.com/avo-hq/avo/issues/1079
1. Set your browser to a western timezone (San Francisco will do)
1. Go to a user
1. observe the date from the birthday field
2. go on the edit page
3. without filling in anything, hit submit
4. check that the birthday is the same
=> fix: date value changed on direct submit

app/components/avo/fields/common/progress_bar_component.html.erb, app/components/avo/fields/common/progress_bar_component.rb, app/components/avo/fields/progress_bar_field/index_component.html.erb, app/components/avo/fields/progress_bar_field/show_component.html.erb
Tweaked the progress bar field to look a bit better.
=> refactor: progressbar component

lib/avo/services/encryption_service.rb
Fixes an issue with older apps, or apps deployed on Heroku that use `ENV['SECRET_KEY_BASE']` instead of `Rails.application.secrets.secret_key_base` for our encryption needs.
1. Go to an index page that has more than one page and see it doesn't crash.
=> fix: use secret_key_base off the env variable

app/components/avo/fields/common/single_file_viewer_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/1174
Fixes https://github.com/avo-hq/avo/issues/1187
1. Use a cloud provider for active storage
2. Make sure you can upload and display files
=> fix: broken download button for file fields

app/components/avo/fields/belongs_to_field/edit_component.html.erb
Right now polymorphic belongs to fields use the class name
for the type. That isn't very user friendly and inconsistent with
other areas. Instead I've made it use translations to get the
human-readable model name that's used elsewhere in the app.
1. Find a resource form with a polymorphic belongs to association, eg. https://avodemo.herokuapp.com/avo/resources/reviews/new
2. Note that the types in the dropdown menu use the class name
3. Add a translation for that resource to `avo.en.yml` (or whichever language you're using) under `avo.resource_translations`
4. Restart the app and confirm that the values in the dropdown are now using the translation and not the class name
=> Use translations for polymorphic class names

app/controllers/avo/base_controller.rb
There are three places in BaseController where a request parameter is constantized. Even with safe_costantize this could lead to security issues. In two of these places I don’t think we need to constantize at all, so I’ve updated the code to not do it unnecessarily.
1. Check that when creating a nested resource (eg a project has many comments) the user is redirected back to the parent resource afterwards.
=> Removed safe_constantize where not needed

app/views/layouts/avo/application.html.erb, lib/generators/avo/base_generator.rb, lib/generators/avo/eject_generator.rb, lib/generators/avo/js/install_generator.rb, lib/generators/avo/tailwindcss/install_generator.rb
Enables the developer to load custom assets before Avo's custom assets. This helps when adding a custom Tailwind CSS file to not override Avo's styles.
=> refactor: add pre_head partial

app/components/avo/views/resource_edit_component.html.erb, app/components/avo/views/resource_edit_component.rb
Fixes https://github.com/avo-hq/avo/issues/1235
Rendering the show view for the field on the edit page:
=> fix: read-only trix field

app/components/avo/resource_component.rb, lib/avo/fields/has_base_field.rb
In the `has_base_field` class, the `resource` method resorts to the `Avo::App.get_resource_by_model_name` method, which picks whatever resource that would use the same base model, instead of the one calling the given field. Using `@resource` and falling back to this method solves this problem.
Note: although this bug appeared while trying a yet to be merged feature, I believe this is still a bug that should be fixed.
Here's the setup:
```ruby
class DocumentReviewResource < Avo::BaseResource
self.model_class = Ticket
self.authorization_policy = Avo::DocumentReviewPolicy
field :unreviewed_documents, as: :has_many, use_resource: UnreviewedDocumentResource
end
```
```ruby
module Avo
class DocumentReviewPolicy < BasePolicy
def create_unreviewed_documents?
false
end
def …
```
=> fix: ensure the right resource is used in resource_component

app/components/avo/index/grid_item_component.html.erb, spec/dummy/app/avo/resources/product_resource.rb, spec/features/avo/generators/locales_generator_spec.rb, spec/features/avo/ordering_spec.rb, spec/support/wait_for_loaded.rb
Fixes https://github.com/avo-hq/avo/issues/1268
1. Go to products
1. use the grid mode
2. Observer the pink background for cover photos
=> fix: add html attributes to grid items

lib/avo/menu/builder.rb
Fixes https://github.com/avo-hq/avo/issues/1284
1. Apply [this](https://github.com/avo-hq/avodemo/commit/d24681896c3a176152c361794ce0e233584cec8a) patch
1. Observe two different resources on the sidebar
=> fix: multiple resources per model brakes sidebar

app/components/avo/actions_component.html.erb, app/components/avo/filters_component.html.erb, app/components/avo/index/ordering/buttons_component.html.erb, app/components/avo/sidebar_profile_component.html.erb
Buttons and related action components should inherit the z-index from their wrapping elements. If need be, the popups they open are the ones that should have a high z-index.
In the same vein, panels are intended to "hover" above other elements, so they should have a higher z-index than most other elements.
As part of debugging this issue I mapped the following z-index uses:
* `z-20`: Dividers, tabs, 
* `z-30`: selectAllOverlay
* `z-40`: Popovers, dropdowns
* `z-50`: Modals, dialogs, Navbar
Fixes https://github.com/avo-hq/avo/issues/1217
1. Configure a resource to have multiple sub-resources that each have one or more filters.
2. Go to the resources show page.
3. Open the topmost filter and scroll down to the filter button below - it should not be visible through the open filter dropdown. …
=> Prevent filter buttons from overlapping filter popovers

app/components/avo/tab_switcher_component.html.erb, app/javascript/js/controllers/actions_picker_controller.js, app/javascript/js/controllers/tabs_controller.js, package.json, yarn.lock
Changes:
Fixes a bug with tabs height and adds a new design to the tabbed pills.
We also take advantage of the new Turbo 7.2.0 `loaded` promise feature to better figure out when a tab frame has loaded.
=> refactor: minor tab improvements

app/components/avo/fields/belongs_to_field/show_component.html.erb
Fixes an issue created in https://github.com/avo-hq/avo/pull/1242/files that changed the navigation from turbo to regular link.
=> fix: change belongs to target to turbo frame

Gemfile, Gemfile.lock, config/i18n-tasks.yml, gemfiles/rails_6.0_ruby_3.0.3.gemfile, gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock, gemfiles/rails_6.0_ruby_3.1.0.gemfile, gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock, gemfiles/rails_6.1_ruby_3.0.3.gemfile, gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock, gemfiles/rails_6.1_ruby_3.1.0.gemfile, gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock, gemfiles/rails_7.0_ruby_3.0.3.gemfile, gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock, gemfiles/rails_7.0_ruby_3.1.0.gemfile, gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock, lib/generators/avo/templates/locales/avo.en.yml, lib/generators/avo/templates/locales/avo.fr.yml, lib/generators/avo/templates/locales/avo.nb.yml, lib/generators/avo/templates/locales/avo.nn.yml, lib/generators/avo/templates/locales/avo.pt-BR.yml, lib/generators/avo/templates/locales/avo.ro.yml, lib/generators/avo/templates/locales/avo.tr.yml, spec/system/i18n_spec.rb
The goal in this issue is normalize and fixes some missing locales, for this i have done the following tasks:
- Install i18n-tasks gem and configure for avo
- Normalize locale files
- Fixes inconsistent interpolations for tr locale
- Adds missing keys for pt-BR (my main language) and ro (I used google translate for that)
- Adds specs for no more missing keys
In this PR i do not fixes any opened issues, but we talk a little bit for this change is this PR #1216
*OBS*: I have not checked for unused translations, because there are a lot, i thinks this should be done in another PR.
1. I run i-18n-tasks and correct one by one.
2. Print for missing keys for pt-BR and ro locale
=> Normalize and fixes missing locales

.github/workflows/stale.yml, app/components/avo/panel_component.html.erb, app/components/avo/panel_component.rb, app/components/avo/tab_switcher_component.html.erb, app/components/avo/tab_switcher_component.rb, app/helpers/avo/application_helper.rb, spec/features/avo/resource_controls_placement_spec.rb
Fixes an issue where the overflow value was set to `auto` and the shadows are not visible. We also add those style to the tab switcher component.
=> refactor: white-panel-classes helper global

.gitignore, app/components/avo/fields/date_field/edit_component.html.erb, app/components/avo/fields/date_field/index_component.html.erb, app/components/avo/fields/date_field/show_component.html.erb, app/components/avo/fields/date_time_field/edit_component.html.erb, app/components/avo/fields/date_time_field/index_component.html.erb, app/components/avo/fields/date_time_field/show_component.html.erb, app/components/avo/fields/time_field/edit_component.html.erb, app/components/avo/fields/time_field/edit_component.rb, app/components/avo/fields/time_field/index_component.html.erb, app/components/avo/fields/time_field/index_component.rb, app/components/avo/fields/time_field/show_component.html.erb, app/components/avo/fields/time_field/show_component.rb, app/javascript/js/controllers/fields/date_field_controller.js, db/factories.rb, lib/avo/concerns/handles_field_args.rb, lib/avo/fields/date_field.rb, lib/avo/fields/time_field.rb, spec/dummy/app/avo/resources/course_resource.rb, spec/dummy/app/models/course.rb, spec/dummy/db/migrate/20221011150126_add_starting_at_to_courses.rb, spec/dummy/db/schema.rb, spec/system/avo/time_field_spec.rb
In this PR I added a new field called `Time` which works with the [Time Picker](https://flatpickr.js.org/examples/#:~:text=2016%2D10%2D20-,Time%20Picker,-%23) part of flatpickr to add a time to a resource. The field is similar to the `DateTime` field, but it doesn't show the calendar, only the time.
By default it looks like this 👇 
You can also add some options to the field to show a different format (for example to not show the seconds, or to have a 24-hour time picker) 👇 
It looks like this on mobile 👇 
Other than the `DateTime` field, this new field doesn't convert the time to the time of the browser, but instead leaves it to how it was created. So when a course starts at 6pm it will also say so if I am in a different timezone (I simulated this by changing my browser's timezone) 👇 
I …
=> Feature: `Time` field

app/javascript/js/controllers/search_controller.js
Algolia autocomplete.js creates duplicate search containers when navigating back to the page.
Fixes https://github.com/avo-hq/avo/issues/1331
1. Open a resource index page with resource search. 
2. Navigate to an individual resource. 
3. Go back to the index page, by clicking on the browser back button. 
4. There should be one more `search box`.
5. Repeat from step 2 to step 4 and there will be as many search boxes as the number of times you did this.
=> Reset autocomplete container before set up

app/components/avo/panel_component.html.erb, app/components/avo/views/resource_index_component.html.erb, spec/features/avo/resource_controls_placement_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1334
=> fix: the panels overflow hides the filters popup

app/components/avo/panel_component.html.erb, app/components/avo/views/resource_show_component.html.erb
Fixes an issue where the panel has a tall, empty white area when the sidebar is taller.
=> fix: panel too tall

app/controllers/avo/actions_controller.rb, app/views/avo/actions/show.html.erb, lib/avo/base_action.rb, spec/dummy/app/avo/actions/toggle_inactive.rb, spec/dummy/app/avo/actions/toggle_published.rb, spec/system/avo/actions_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1343
1. Go to a user
1. Open the "toggle inactive" action
2. Observe the default values applied
=> fix: action fileds default option broken

app/components/avo/field_wrapper_component.rb, app/components/avo/fields/edit_component.rb, app/components/avo/fields/show_component.rb, app/components/avo/item_switcher_component.html.erb, lib/avo/configuration.rb, lib/avo/fields/base_field.rb, lib/generators/avo/templates/initializer/avo.tt, spec/dummy/app/avo/resources/user_resource.rb, spec/dummy/config/initializers/avo.rb, spec/features/avo/stacked_wrapper_layout_spec.rb, spec/support/helpers.rb
It allows a developer to set some fields or all of them in a stacked layout instead of inline.
1. Go to the initializer and edit the `field_wrapper_layout` option to `:stacked`
2. See the show and edit views for a resource
3. observe that all the fields are stacked
---
1. Reset the initializer to how it was (`:inline`)
1. Go to the user and observe that only the `first_name` field is stacked. The rest are inline.
=> feature: stacked fields by default

app/components/avo/field_wrapper_component.html.erb, app/components/avo/field_wrapper_component.rb, app/components/avo/views/resource_edit_component.html.erb, app/components/avo/views/resource_index_component.html.erb, app/components/avo/views/resource_show_component.html.erb, db/factories.rb, lib/avo/html/builder.rb, spec/dummy/app/avo/resources/product_resource.rb, spec/features/avo/html_attribute_spec.rb
Adds the `label` and `content` helpers to the [`html` option](https://docs.avohq.io/2.0/stimulus-integration.html#attach-html-attributes).
1. Step 1
1. Step 2
=> feature: label and content available in the html option

lib/avo/base_resource.rb
Previously if there was an error thrown from the block for label or description fields, it would be silently swallowed and not show in the logs that there was an error.
To reproduce, set `as_label: true` on a field, give the field a block and then throw an error inside the block. On main the error never appears, on this branch it is raised in the logs.
=> Don't swallow errors with labels and descriptions

lib/avo/fields/key_value_field.rb
Key value fields only appear to work with ActiveRecord attributes. In order to support virtual attributes (and real attributes) a subtle code change is needed.
1. Step 1
1. Step 2
=> Support virtual_attributes in key_value field

app/javascript/js/controllers/search_controller.js
The Algolia `autocomplete()` method returns a `destroy` method. We hold a pointer to this and call it when the controller is disconnected. This addresses a problem where a zombie search would remain on screen when navigating back.
Fixes #1365
1. Perform a global or resource search
1. Select one of the search results
1. Click the browser back button
**What should happen:** The search modal should no longer be visible when you navigate back.
=> fix: destroy the search modal when disconnected

lib/avo.rb, lib/avo/services/authorization_clients/nil_client.rb, lib/avo/services/authorization_service.rb
Fixes an issue where community version requires `pundit` even if it doesn't use it.
From https://github.com/avo-hq/avo/pull/1384
1. Use Avo on Community license
2. Don't require `pundit` in the `Gemfile`
1. Observe that everything is running
=> fix: don't raise errors on community when pundit is missing

app/javascript/js/controllers/search_controller.js, lib/avo/fields/base_field.rb, lib/avo/fields/concerns/has_default.rb, lib/avo/fields/concerns/is_readonly.rb, lib/avo/fields/concerns/is_required.rb, lib/avo/hosts/resource_view_record_host.rb, spec/features/avo/default_field_spec.rb
Adds the ability to access the `resource`, `record`, `view` and more in the default block.
Alternative to https://github.com/avo-hq/avo/pull/1380
=> feature: default executes in host

spec/dummy/app/views/devise/sessions/new.html.erb, spec/dummy/app/views/devise/shared/_error_messages.html.erb, spec/dummy/app/views/devise/shared/_links.html.erb, spec/dummy/db/seeds.rb
Just updated the seed default password and the sign in form to make it easier to get started.
=> chore: update the default sign in form

bin/init
Init script checks to see if git upstream requires update, does if required, doesn't if doesn't.
~Fixes # (issue)~
- Run `bin/init`
- Run `bin/init`
- Great!
Compare to current state:
- Run `bin/init`
- Run `bin/init`
- Error!
=> init script may be run repeatedly without error

app/components/avo/sidebar_profile_component.rb, bin/test, lib/avo/configuration.rb, spec/components/avo/sidebar_profile_component_spec.rb, spec/rails_helper.rb
Added a new configuration option called `sign_out_path_name`. This allows callers to completely customize the name of the path that we use in our sign-out menu item.
Note that I have also turned on view component tests so that I could write some unit tests for this. If those were previously off for a reason, though, I can revert this part of the change.
Fixes #1407 
1. Verify that the sign-out menu item works if the sign-out path in your app uses the standard name of `destroy_user_session_path`
1. Verify that the sign-out menu item works if your app has a custom name for its sign-out path which you pass into `config.sign_out_path_name`
=> feature: make sign-out path name configurable

app/components/avo/base_component.rb, db/factories.rb, spec/dummy/app/models/brother.rb, spec/features/avo/has_many_field_spec.rb
Link to child resources
A small bug. 
if the parent resource is the same as the base class or if the child class is missing we fallback to the parent class. 
We may as well raise an exception ? 
1. Step 1
1. Step 2
=> Fallback to resources class / link to child resource feature

app/controllers/avo/dashboards_controller.rb, spec/system/avo/dashboards_spec.rb
Put the dashboard name in the page title to get more descriptive tab names.
Check page titles on both named and unnamed dashboards. If the dashboard has a name, it will be prepended to the app name in the page title.
=> feature: add dashboard name to page title

app/views/avo/actions/show.html.erb
[Pressing enter in a form](https://www.w3.org/TR/2018/SPSD-html5-20180327/forms.html#implicit-submission) will trigger the first button of `type="submit"` in the form. "submit" is the [default type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type) for buttons inside a form. Explicitly set `type="button"` on the cancel button so that it won't be triggered by enter. This causes the true submit button to be triggered instead.
Fixes #1427
https://user-images.githubusercontent.com/549149/201212767-6e9f907c-339a-4b3a-96c6-49cf1066adb4.mov
https://user-images.githubusercontent.com/549149/201215161-9b78bacb-d0eb-4d08-ade6-4b841f31b0b5.mov
1. Run the sample app
2. Go to http://localhost:3030/admin/resources/posts/35
3. Click on "Toggle post published"
4. Click into the …
=> bug: enter should submit rather than cancelling action

lib/avo/concerns/has_html_attributes.rb, spec/dummy/app/avo/resources/team_resource.rb, spec/features/avo/html_attribute_spec.rb
`parsed_html` was being memoized at the field level, but it depends on the record. Since the field is only instantiated once, that resulted in cached results from the first record being applied to all records.
I have removed the memoization and refactored the code slightly so that the parsing will happen once per call to `get_html`. There might be a way to reintroduce memoization in a more robust way, but I'm not sure if the speed increase would be enough to justify the complexity. Let me know what you think.
I updated `TeamResource` to exercise this code and added a test.
Fixes #1430
1. Notice that `TeamResource` has been modified to generate a style for each team name on the index page.
1. Go to /admin/resources/teams
Before this change all rows used the color of the first team. Now …
=> fix: Fix problem with HasHTMLAttributes memoization

app/components/avo/sidebar/group_component.html.erb, app/components/avo/sidebar/heading_component.html.erb, spec/dummy/db/schema.rb
- Editor menu expandable only expand click on `icon`, so I resolved this issue now a user can expand the link by clicking on whole menu link.
- This same issue with sub menus too, so I have also resolved into it.
1. Step 1
1. Step 2
https://user-images.githubusercontent.com/105207904/201431065-66cb2b0c-ed19-4d01-b3b3-084199dfd48b.mp4
=> fix: sidebar group and heading are clickable to collapse/expand

app/controllers/avo/search_controller.rb
Fixes https://github.com/avo-hq/avo/issues/1448
1. Search resources
1. Notice the right count number showing up
=> fix: get correct search results count

app/javascript/js/controllers/fields/trix_field_controller.js
It's possible to disable csrf tokens by setting
`config.action_controller.allow_forgery_protection = false` in your environment config file. This is the default in the test environment.
Unfortunately, the trix field controller assumes that the csrf token will always be available, which makes it crash if it's not. Because of that it's not possible to use avo trix fields in tests.
I've changed the code so that if the csrf token isn't set then we don't use it.
1. Disable csrf tokens in your development environment by setting `config.action_controller.allow_forgery_protection = false` in `config/environments/development.rb`
2. Try to edit and save a resource with a trix field (this should work on this branch but hit errors on main)
Manual reviewer: please leave a comment with …
=> Don't set the csrf token if it's not available

app/controllers/avo/attachments_controller.rb, app/javascript/js/controllers/fields/trix_field_controller.js, lib/avo/base_resource.rb
To use attachments on a trix field, you need to set an attachment_key in the field definition (which gives the name of the association which attachments can be stored in).
Although there is code in the trix stimuls controller to warn the user if they haven't set this, it doesn't work, because it expects the `data-attachment-key` attribute to be set but empty and does not work if the attribute isn't set at all (which is how the html actually works if attachment_key isn't set).
Also, although the server throws an error if you try to attach something without setting the attachment name (it throws an error because it cannot find the right association to use), the error is unhelpful:
TypeError ([...] is not a symbol nor a string)
(Where the array contains the name of every association on the …
=> Warn developers if they forget to set attachment_key on trix fields

app/javascript/js/controllers/fields/date_field_controller.js, lib/avo/concerns/handles_field_args.rb, lib/avo/fields/base_field.rb, spec/components/avo/sidebar_profile_component_spec.rb, spec/dummy/app/avo/resources/comment_resource.rb, spec/dummy/app/avo/resources/team_resource.rb, spec/system/avo/date_time_fields/date_time_eastern_spec.rb, spec/system/avo/date_time_fields/date_time_utc_spec.rb, spec/system/avo/date_time_fields/date_time_western_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1441
1. Go to team resource
1. observe the time to the browser timezone
2. add the `timezone` option to the `created_at` field
3. observe the time being casted to that timezone
=> fix: time fields without relative don't cast the time

app/views/avo/actions/show.html.erb, lib/avo/base_action.rb, lib/avo/hosts/resource_record_host.rb, spec/dummy/app/avo/actions/release_fish.rb, spec/system/avo/custom_resource_controls_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1463
This can be used like this:
```ruby
class ReleaseFish < Avo::BaseAction
self.message = -> {
"Are you sure you want to release the #{record.name}?"
}
end
```
=> feature: callable action message

app/controllers/avo/dashboards/cards_controller.rb, lib/avo/base_card.rb, spec/dummy/app/avo/cards/metric_from_param.rb, spec/dummy/app/avo/dashboards/dashy.rb, spec/dummy/config/boot.rb, spec/features/avo/metric_receives_params_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1464
1. Go to `Dashy` dashboard
2. observe the `Metric from param` card to have the current user id value
3. add `metric=111` param in the url
4. observe that same card have the `111` value
=> fix: card missing current_user

app/components/avo/fields/trix_field/edit_component.html.erb, app/components/avo/fields/trix_field/edit_component.rb
Fixes an issue where trix field ids were not unique when used as native fields.
=> refactor: trix id not unique when used as native

app/components/avo/resource_component.rb, spec/dummy/app/policies/team_policy.rb, spec/features/avo/authorization_spec.rb, spec/support/wait_for_loaded.rb
As described in `BaseComponent`, when authorizing the associations we don't always have access to the child association.
In the `Post` `has_many` `Comments` example, when you want to authorize `show_comments?` you will have a `Comment` instance as the `record` variable in `PostPolicy`, but when you try to authorize the `attach_comments?` policy method, you won't have a `Comment` instance, because you want to create one, but we expose the parent `Post` instance so you have more information about that authorization action that you're trying to make.
Docs clarification [here](https://docs.avohq.io/2.0/authorization.html#associations)
Fixes https://github.com/avo-hq/avo/issues/1459
1. Go to a Team
1. You'll see in the logs what kind of record you have access to.
2. Observe that ivor the view, …
=> fix: expose the parent record from association policy methods

app/javascript/js/controllers/fields/trix_field_controller.js
Fixes https://github.com/avo-hq/avo/issues/1386#issuecomment-1340692517
[Pre-release](https://rubygems.org/gems/avo/versions/2.21.1.pre.pr1484)
1. Got to a post
1. use the `force_locale=ro` param
2. upload a file in the trix field
3. observe that it is uploaded properly
=> fix: correctly parse and build the trix attachment path

app/controllers/avo/application_controller.rb, app/controllers/avo/dashboards_controller.rb, lib/avo/dashboards/base_dashboard.rb, spec/dummy/app/avo/dashboards/dashy.rb
Fixes https://github.com/avo-hq/avo/issues/1354
[Docs](https://docs.avohq.io/2.0/dashboards.html#dashboards-authorization)
1. Go to Dashy
2. change the authorization rule to `!current_user.is_admin?`
3. observe you get redirected to some other page.
=> feature: dashboards authorization

lib/generators/avo/resource_generator.rb, spec/dummy/app/models/event.rb, spec/dummy/db/migrate/20221224005546_create_events.rb, spec/dummy/db/schema.rb, spec/features/avo/generators/resource_generator_spec.rb
This fixes a bug with the Resource generator where it uses the wrong field type for datetime database fields. It should map to the Avo date_time field, whereas it currently maps incorrectly to datetime.
Also added password_digest to the ignored db fields as this is another common password field people use in Rails apps.
1. Create a minimal rails app with a model that has a datetime field, I.E. a User model with a confirmed_at datetime field
1. Run the Avo resource generator for that model (I.E. ```bin/rails generator avo:resource user```) and observe the datetime field getting set to ``` as: :date_time ``` whereas running the same steps from the main branch will result in ```as: :datetime```
=> Resource generator incorrect date_time field fix

lib/avo/fields/date_time_field.rb, lib/avo/fields/time_field.rb, spec/dummy/app/avo/resources/course_resource.rb
Fixes https://github.com/avo-hq/avo/issues/1506
1. Go to a course
1. See that the timezone block gets evaluated to `Berlin`
=> feature: timezone callable

app/controllers/avo/search_controller.rb
Another attempt at fixing fa513705f2b79ca8f498d05e755f55759f42c824. It turns out that simply unscoping select does not fix the issue as rails does something weird with the count query, as explained in #1494 
#1494 
1. Search for any resource and confirm that the count (the number of matching models) is correct
2. 
=> Make search work when using strange selects in ransack

app/components/avo/fields/belongs_to_field/edit_component.html.erb, app/components/avo/fields/belongs_to_field/edit_component.rb, spec/support/helpers.rb
Fixes an issue where a searchable `belongs_to` field used a different view than a non-searchable field.
1. Got to a resource with a belongs to
1. add a data attribute for the `edit` view
2. check that the attribute is added on `new` and `edit`
=> fix: searchable belongs_to uses valid view

lib/avo/fields/base_field.rb, spec/dummy/app/avo/resource_tools/team_membership_tool_playground.rb, spec/dummy/app/avo/resources/membership_resource.rb, spec/dummy/app/views/avo/resource_tools/_team_membership_tool_playground.html.erb
Fixes and issue where one would try to use `avo_edit_field` and had to use the `stimulus_controllers` on a resource.
1. Add a `hey` stimulus controller to a `membership_resource`
1. add this field to a resource tool 
2. observe that the field has the `hey-target=teamBelongsTo` attribute added to the field
```ruby
class MembershipResource < Avo::BaseResource
self.stimulus_controllers = "hey"
end
```
```erb
<%= avo_edit_field :team, form: form, as: :belongs_to, resource: @resource.hydrate(model: @model), html: {
edit: {
input: {
data: {
foo: :barr
}
}
}
} %>
```
=> refactor: base field initializes with a resource

app/views/avo/partials/_table_header.html.erb, spec/support/helpers.rb
Adds `data-field-id` and `data-field-type` to the table headers so one can target them using CSS and conditionally apply styles or through JS.
=> feature: add data attributes to table headers

lib/generators/avo/templates/initializer/avo.tt
`Avo::Configuration` has no `authenticate_with=` method. Instead use `authenticate_with` with a block.
1. generate a new rails project
2. install avo
3. see generated config file in `config/initializers/avo.rb`
=> Fix authenticate_with in avo config template

db/factories.rb, lib/avo/fields/status_field.rb, spec/dummy/app/avo/resources/project_resource.rb, spec/features/avo/status_field_spec.rb
Solves issue when we use strings on `loading_when` and `failed_when` conditions on the `status` field.
This kind of args: 
```
failed_when: [:closed, :rejected, :failed, 'user_reject'], loading_when: [:loading, :running, :waiting, 'Hold On']
```
Did not work until now, even [when the docs](https://docs.avohq.io/2.0/fields/status.html) state they should.
1. Use any string for the `failed_when` or `loading_when` fields, you will notice these fallbacks to default behavior.
Before:
Now:
=> fix: allow strings array on status loading running

app/views/layouts/avo/application.html.erb, lib/generators/avo/resource_generator.rb, spec/dummy/db/seeds.rb
When columns with binary data come in as a text field (such as Geospatial data in MySQL) then it is an ASCII string that does not render properly in Avo.  By using a `format_using` on the field the encoding can be safely changed to UTF-8, and out of convenience this can be established as a default behaviour for rendering text fields.
1. Obtain (or create) a database in MySQL that has text fields encoded as ASCII-8BIT.  The original **[sakila](https://downloads.mysql.com/docs/sakila-db.zip)** test database from MySQL AB does use this kind of data type in the **Address** table for geospatial data.
2. Create a Resource file for the affected model, can use this for **sakila**:
```
bin/rails g avo:resource address
```
3. When rendering the page, note that this error appears:
```
incompatible …
```
=> By default have text fields convert ASCII-8BIT to UTF-8

app/controllers/avo/application_controller.rb
Fixes https://github.com/avo-hq/avo/issues/1608
I switched the order of the authenticate and authorization before actions.
Fixes https://github.com/avo-hq/avo/issues/1608
- [x ] I have performed a self-review of my own code
1. Step 1
Set `authenticate_with` in `avo.rb`
1. Step 2
Without this patch the authorization happened first leading to unexpected results.
=> fix: authentication before authorization

package.json, yarn.lock
Anyone using avo who also loads turbo-rails JS themselves is currently subject to this issue https://github.com/hotwired/turbo-rails/issues/409 which has been [resolved](https://github.com/hotwired/turbo-rails/commit/3f719f20923d67f9bf14a9f3f13a1e6321ba8fca) in a recent release of the hotwired/turbo-rails lib. In the event that Turbo Rails is loaded twice (say, by a dependency like avo and by the main app), the turbo-rails JS will attempt to redundantly define that cable stream source element and crash with a console error.
This issue was resolved in Turbo Rails 7.2.5, but Avo is currently locked to 7.2.0. This PR upgrades the library to 7.3.0 and fixes this error case for users who are also loading turbo rails themselves.
1. In your main app, using avo as a dependency, attempt to import …
=> Bump Hotwire TurboRails JS to 7.3.0

lib/avo/fields/belongs_to_field.rb, lib/avo/fields/concerns/use_resource.rb, lib/avo/fields/has_base_field.rb, spec/dummy/app/avo/resources/comment_resource.rb, spec/dummy/app/avo/resources/compact_user_resource.rb, spec/dummy/app/controllers/avo/compact_users_controller.rb, spec/features/avo/use_resource_spec.rb, spec/system/avo/belongs_to_polymorphic_spec.rb
Add `use_resource` option to `belongs_to` field.
Fixes #1616
```ruby
field :user, as: :belongs_to, use_resource: CompactUserResource
```
```ruby
class CompactUserResource < Avo::BaseResource
self.title = :name
self.model_class = ::User
self.find_record_method = ->(model_class:, id:, params:) {
model_class.friendly.find id
}
heading "personal information"
field :first_name, as: :text
field :last_name, as: :text
field :birthday, as: :date
heading "contact"
field :email, as: :text
end
```
[use_resource_belongs_to.webm](https://user-images.githubusercontent.com/69730720/224484103-072b256b-0dc3-4b8b-a6ad-cdae5cd6957f.webm)
Docs PR https://github.com/avo-hq/avodocs/pull/23
=> feature: add use resource option to belongs to field

lib/avo/fields/tags_field.rb, spec/dummy/app/avo/actions/toggle_inactive.rb, spec/system/avo/tags_spec.rb
Tags field option `fetch_labels` can now be used to dynamically fetch the labels for each record.
For example  
```ruby
field :skills, as: :tags,
fetch_labels: -> { ["tag", "custom_label"] }
```
Of course this is supposed to be used dynamically, something like this:
```ruby
field :users, as: :tags,
fetch_labels: -> {
User.where(id: record.array_with_user_ids).pluck(:first_name)
}
``` 
or
```ruby
field :users, as: :tags,
fetch_labels: -> {
User.where(id: record.array_with_user_ids).pluck(:first_name, :last_name)
.map { |first_name, last_name| "#{first_name} #{last_name}" }.presence || resource.model.array_with_user_ids
}
``` 
Fixes #1619
Docs PR https://github.com/avo-hq/avodocs/pull/24
=> feature: fetch_labels option for tags field

app/components/avo/fields/common/single_file_viewer_component.html.erb, app/components/avo/fields/common/single_file_viewer_component.rb, app/components/avo/fields/file_field/edit_component.html.erb, app/components/avo/fields/file_field/edit_component.rb, app/components/avo/fields/files_field/edit_component.html.erb, app/components/avo/fields/files_field/edit_component.rb, app/controllers/avo/attachments_controller.rb, lib/avo/fields/concerns/file_authorization.rb, spec/dummy/app/policies/post_policy.rb, spec/dummy/app/policies/project_policy.rb, spec/dummy/app/policies/user_policy.rb, spec/system/avo/tags_spec.rb
Now we can police each file using field level authorization methods.
```ruby
field :cover_photo, as: :file, is_image: true
```
```ruby
def upload_cover_photo?
user.student?
end
def download_cover_photo?
true
end
def delete_cover_photo?
user.admin?
end
```
Fixes #1624
Docs PR https://github.com/avo-hq/avodocs/pull/25
=> feature: field level file authorization

app/components/avo/fields/file_field/edit_component.html.erb, app/components/avo/fields/files_field/edit_component.html.erb, lib/avo/fields/concerns/file_authorization.rb
Refactors the file authorization to allow control to either all attachments or granular per field.
=> refactor: loose file authorization

lib/generators/avo/templates/initializer/avo.tt
Fixes # ([1633](https://github.com/avo-hq/avo/issues/1633))
=> fix: Removed resource_control from generator

CONTRIBUTING.MD, app/components/avo/views/resource_index_component.html.erb, app/components/avo/views/resource_index_component.rb, app/controllers/avo/search_controller.rb, lib/avo/base_resource.rb, lib/avo/hosts/base_host.rb, lib/avo/services/authorization_service.rb, lib/generators/avo/templates/initializer/avo.tt, spec/dummy/app/avo/resources/city_resource.rb, spec/dummy/app/policies/application_policy.rb, spec/dummy/app/policies/course_link_policy.rb, spec/dummy/app/policies/course_policy.rb, spec/dummy/app/policies/post_policy.rb, spec/dummy/app/policies/team_policy.rb, spec/dummy/app/policies/user_policy.rb, spec/dummy/config/initializers/avo.rb, spec/features/avo/hidden_from_global_search_spec.rb, spec/features/avo/search_with_custom_path.rb, spec/rails_helper.rb
Add two new class attributes to `Avo::BaseResource` to further customize the search behaviour:
- search_policy_class: responsible for setting the policy used to authorize the search on the applied resource
- search_result_url: responsible for setting the url to be used in the search results
An Avo app contains the following classes: 
- ReportResource (used only by admin users to manage reports)
- Avo::Customers::ReportsController (used by customer users to view reports)
- ReportPolicy (allowing only admin users to manage ReportResource)
- Customers::ReportPolicy (allowing customer users to view reports from the controller aforementioned)
When a customer searches for a report on the global search, Avo 2.28 will use `ReportPolicy` to authorize the search and it will deny since a customer …
=> feature: add search_result_url and search_policy_class

lib/avo/dashboards/base_divider.rb
Fixes an issue where the dividers are rendered invisible by default.
=> fix: divider renders invisible by default

app/components/avo/fields/common/single_file_viewer_component.html.erb, app/components/avo/fields/common/single_file_viewer_component.rb, lib/avo/fields/file_field.rb, lib/avo/fields/files_field.rb, spec/dummy/app/avo/resources/post_resource.rb
Fixes #1664
Now it's possible to hide the caption of an image with the option `display_filename: false` on a `file`/`files` field
1. Step 1
1. Step 2
=> feature: display_filename option for file and files field

lib/avo/fields/base_field.rb
Fixes an issue where you can't set the `visible` field option to `false`.
```ruby
field :user, as: belongs, visible: false # this does not hide the field
```
=> fix: allow field visible false

lib/avo/fields/id_field.rb, spec/dummy/app/avo/resources/user_resource.rb, spec/features/avo/field_sorting_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1676
1. Visit the users page. Observe that the ID field is not sortable
1. Visit the projects page. Observe that the ID field is sortable
=> fix: disable sorting on id field

app/controllers/avo/attachments_controller.rb, lib/avo/fields/concerns/file_authorization.rb, spec/dummy/app/policies/course_link_policy.rb, spec/dummy/app/policies/course_policy.rb, spec/dummy/app/policies/photo_comment_policy.rb, spec/dummy/app/policies/post_policy.rb, spec/dummy/app/policies/project_policy.rb, spec/dummy/app/policies/team_policy.rb, spec/dummy/app/policies/user_policy.rb
Fixes #1662
We have discovered that assigning different weights to two methods that police the same thing can be a complex and challenging task. As a result, we have decided to make `upload_attachments?`, `download_attachments?`, and `delete_attachments?` obsolete.
From now on, only field level authorization will be considered. If it is defined and returns true, the action will be granted; otherwise, it will not.
~~How it works:~~
~~`upload_attachments?`, `download_attachments?` and `delete_attachments?` are first level authorization for attachments. 
`upload_file_name?`, `download_file_name?` and `delete_file_name?`  are second level authorization for each field.~~
~~Lets pick uploads example:~~
~~If `upload_attachments?` is NOT defined only `upload_file_name?` will count for authorize …
=> improvement: another approach on attachments field level authorization

app/helpers/avo/application_helper.rb, lib/avo/filters/base_filter.rb, spec/helpers/avo/application_helper_spec.rb
In order to allow page authors to create links that go to a resource page with a filter already enabled, expose encode and decode methods for filter params.
This was inspired by a conversation we had on the Avo discord.
This PR does not include any user-visible changes. I'll add a comment with the test output.
=> Add helpers for encoding/decoding filter params

lib/avo/fields/base_field.rb
Fixes #1695
We had a vulnerability that allows non-visible fields to be edited by intercepting the request and manipulating the form.
Now we only update fields that are NOT read-only AND visible
=> security: avoid form manipulation on non-visible fields

lib/avo/app.rb
`ActiveStorage::Current.url_options` is set as a hash for Rails 7.
Fixes https://github.com/avo-hq/avo/issues/1706
=> Fix: ActiveStorage current url_options should be set as a hash of url options

app/components/avo/resource_component.rb, lib/avo/fields/base_field.rb
Fixes #1688
We were wrongly initializing `@updatable = !readonly`, this would not work when `readonly` is a proc.
=> fix: readonly as proc

.github/workflows/test.yml, lib/avo/concerns/fetches_things.rb
In order to ensure compatibility with the latest rails release, add `7.0` to the test matrix in github CI.
1. Step 1
1. Step 2
=> Add Rails 7.0.x to the test matrix

package.json, yarn.lock
In order to fix security vulnerabilities in some of its dependencies, upgrade css-loader to the most recent release.
1. Step 1
1. Step 2
=> Upgrade css-loader npm library

package.json, yarn.lock
According to the official repo at
https://github.com/tailwindlabs/tailwindcss-jit, this project was merged into core tailwindcss in 2021. Avo is using tailwindcss 3.0 so it should be available via the core.
1. Step 1
1. Step 2
=> Remove outdated @tailwindcss/jit

app/components/avo/fields/country_field/edit_component.html.erb, app/components/avo/fields/number_field/edit_component.html.erb, app/components/avo/fields/password_field/edit_component.html.erb, app/components/avo/fields/select_field/edit_component.html.erb, app/components/avo/fields/text_field/edit_component.html.erb, lib/avo/fields/base_field.rb
In order to allow admins to add `autocomplete` attributes to form fields (e.g. to support address autofill from mapbox), create a new `autocomplete` field option. Default should be no `autocomplete` attribute at all on the form input element.
1. Step 1
1. Step 2
=> Add autocomplete field option

lib/avo/base_action.rb, spec/dummy/app/avo/actions/release_fish.rb
Hey all. I think I have spotted an issue here and this is my suggested fix, but Im not 100% sure why the original `present?` checks are there, so please let me know if Im missing something fundamental!
When initializing an Action any class variables should be set to nil if no value provided. For example when on an `Index` view, `model` == `nil` intentionally. 
The existing implementation behaves in such a way that breaks `.message` for example. 
Lets say you visit a show page, an Action is initialized with `model` set to the current record you are viewing. Thus `self.class.model` is set to it.
if you then navigate to the `index` page, the Action is initialized with `model == nil`, but the `present?` check means `self.class.model` still points to previous record instance. Therefore when …
=> [Fix] When initializing an Action any class variables should be set to nil if appropriate

lib/avo/app.rb
When checking for the use of specific cache types (redis, memcached) avoid calling those classes and triggering their onload code.
Fixes #1731 
1. Step 1
1. Step 2
=> Refer to cache class without calling them

app/components/avo/views/resource_index_component.html.erb
In order to allow users to access multiple pages of results while using the map view, render pagination links if needed when the view type is `:map`.
1. Step 1
1. Step 2
=> Include pagination on resource index map view

app/components/avo/index/resource_map_component.html.erb
Add a space between the static `overflow-auto` class and the interpolated layout class.
1. Step 1
1. Step 2
=> Add space after `overflow-auto` class

app/components/avo/actions_component.rb, app/views/avo/actions/show.html.erb, config/routes.rb, lib/avo/base_action.rb, lib/avo/resources/controls/action.rb, spec/dummy/app/avo/actions/sub/dummy_action.rb, spec/dummy/app/avo/resources/fish_resource.rb, spec/dummy/app/avo/resources/team_resource.rb, spec/dummy/app/avo/resources/user_resource.rb, spec/features/avo/custom_resource_controls_spec.rb
Fixes an issue where you can't use namespace actions.
Now instead of just using `DummyAction`, you can nest them inside directories `Sub::DummyAction`.
=> refactor: enable action namespacing

app/javascript/js/controllers/search_controller.js, spec/features/avo/search_spec.rb
- Adds encoding to the built search query to allow using special characters in searchable resources (`+$@/...`)
- Adds some test (run pending)
Fixes #1701
1. Rename any searchable field to include a non-standard character
2. Use any of the search options to find it
=> fix(searchControllerJs): encodes special chars in query

lib/generators/avo/resource_generator.rb
Fixes https://github.com/avo-hq/avo/issues/1726
=> fix: through reflection in generator

lib/avo/configuration.rb, spec/dummy/config/initializers/avo.rb, spec/features/avo/app_spec.rb
Adds the ability to use a block in the `app_name` configuration.
=> feature: callable app_name

app/controllers/avo/search_controller.rb
In the count process of the search screen, there was a bug that caused an internal error when the id did not exist for a table.
1. Step 1
1. Step 2
=> Fix to count by primary key of model

lib/avo/app.rb
Fixes an issue where apps deployed in environments where they don't have access to `/tmp/cache` would fail to use the cache store.
=> fix: valid file cache store path

lib/generators/avo/resource_generator.rb
Fixes an issue where if the generator can't parse a field, it would crash.
=> Handle missing field_options more gracefully.

lib/avo/engine.rb
Fixes https://github.com/avo-hq/avo/issues/1786
Fixes https://github.com/avo-hq/avo/pull/1765#discussion_r1224736534
=> refactor: remove default i18n load dir

config/initializers/pagy.rb, spec/dummy/config/initializers/pagy.rb, spec/features/avo/discreet_pagination_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1783
=> fix: allow extra pagy i8n load

app/components/avo/fields/file_field/index_component.rb, app/components/avo/fields/index_component.rb, app/controllers/avo/application_controller.rb, lib/avo/base_resource.rb, spec/dummy/app/avo/resources/user_resource.rb
Fixes an issue where Avo tried to eager load computed file fields. That would crash the app because you can't really do that.
From [here](https://discord.com/channels/740892036978442260/740893011994738751/1118232114647810098)
1. Go to the user resource
1. uncomment the `first_post_image` field
2. ensure it's not crashing the app.
=> fix: prevent eager loading of computed file fields

app/components/avo/alert_component.html.erb
In order to handle non-string `message` values, call `to_s` before the sanitization step. This is consistent with other templates where `sanitize` is used.
When `message` is a non-string value (i.e. `true`), passing it to `sanitize` results in an exception. Elsewhere in the code, we avoid this by first applying `to_s`.
1. Step 1
1. Step 2
=> Stringify message before sanitization

app/components/avo/sidebar/item_switcher_component.html.erb, app/components/avo/sidebar/link_component.html.erb, app/components/avo/sidebar/link_component.rb, app/components/avo/sidebar_component.html.erb, spec/dummy/config/initializers/avo.rb
Add icons to the sub-menus. This will give more **life** to the sidebar.
```ruby
config.main_menu = -> do
dashboard :dashy, icon: "bolt"
resource :comments, icon: "chat-bubble-bottom-center-text"
end
```
- [ X] I have performed a self-review of my own code
1. Add `icon: 'user'` next to the resource
1. Watch it appear in the menu
=> ✨ Add icon to menu items

app/components/avo/sidebar_component.html.erb
When using the community license, the dashboards or resources lack an icon getter for the left sidebar menu items.
=> fix: menu icons on community license

lib/avo/concerns/has_fields.rb, lib/avo/fields/tags_field.rb, lib/avo/items_holder.rb, spec/dummy/db/seeds.rb
Fixes #1805
The "Tags" field is a feature available in the Pro license, but for some reason, it was visible even on the community license. However, the field was not being updated properly. This created a misleading impression that there was a problem with the field.
Now tags field is hidden on community license.
Seeds was commented not sure why, this PR also uncomment seeds
1. Step 1
1. Step 2
=> fix: hide tags field on community license

app/components/avo/fields/area_field/edit_component.html.erb, app/components/avo/fields/boolean_field/edit_component.html.erb, app/components/avo/fields/code_field/edit_component.html.erb, app/components/avo/fields/country_field/edit_component.html.erb, app/components/avo/fields/markdown_field/edit_component.html.erb, app/components/avo/fields/number_field/edit_component.html.erb, app/components/avo/fields/password_field/edit_component.html.erb, app/components/avo/fields/progress_bar_field/edit_component.html.erb, app/components/avo/fields/status_field/edit_component.html.erb, app/components/avo/fields/text_field/edit_component.html.erb, app/components/avo/fields/textarea_field/edit_component.html.erb, app/components/avo/fields/trix_field/edit_component.html.erb, app/components/avo/views/resource_edit_component.html.erb, lib/avo/base_resource.rb, lib/avo/execution_context.rb, lib/avo/fields/base_field.rb, spec/dummy/app/avo/resources/city_resource.rb, spec/dummy/app/avo/resources/comment_resource.rb, spec/dummy/app/avo/resources/photo_comment_resource.rb, spec/dummy/app/avo/resources/post_resource.rb, spec/dummy/app/avo/resources/product_resource.rb, spec/dummy/app/avo/resources/team_resource.rb, spec/dummy/app/avo/resources/user_resource.rb, spec/dummy/app/avo/resources/z_post_resource.rb, spec/dummy/app/models/city.rb, spec/dummy/app/views/avo/resource_tools/_city_editor.html.erb, spec/features/avo/native_fields_spec.rb, spec/system/avo/date_time_fields/date_time_eastern_spec.rb, spec/system/avo/date_time_fields/date_time_utc_spec.rb, spec/system/avo/date_time_fields/date_time_western_spec.rb
Enables developers to add custom formatters before the data is displayed in the UI and before it gets saved to the database.
We retrofitted `format_using` to use the `ExecutionContext` and dropped the `value` argument.
The `update_using` block is run just before the value is saved on the model.
[Docs](https://docs.avohq.io/2.0/field-options.html#fields-formatter)
```ruby
field :metadata, as: :code,
format_using: -> {
if view == :edit
JSON.generate(value)
else
value
end
},
update_using: -> do
ActiveSupport::JSON.decode(value)
end
```
=> feature: format_using and update_using field options

app/controllers/avo/search_controller.rb, spec/features/avo/search_has_many_scope_spec.rb
Fixes #1808
```ruby
class UserPolicy < ApplicationPolicy
class Scope < Scope
def resolve
scope.where("first_name like ?", "%a%")
end
end
end
```
When searching on a has many field, the policy scope was not being applied, returning all association records.
[before.webm](https://github.com/avo-hq/avo/assets/69730720/f6b6045c-793e-4804-912b-76f13c9257b1)
Now the policy scope is being applied on the search result.
[after.webm](https://github.com/avo-hq/avo/assets/69730720/709c916b-b066-42fd-afb7-b18f8c687c84)
=> improvement: apply policy scope on has many search query

app/controllers/avo/base_controller.rb, lib/avo/base_resource.rb
This is a proposed feature to add custom destroy methods to resources. This makes Avo compatible with soft delete gems like discard. Please reject if not appropriate. 
```
...
self.destroy_record_method = -> (record:) {
record.discard
}
...
```
If not defined, the default destroy! is used. 
=> feature: Allow custom destroy methods.

spec/dummy/app/avo/resources/active_record_attachment_resource.rb, spec/dummy/app/controllers/avo/active_record_attachments_controller.rb
Fixes an issue where the `AttachmentsController` would clash with the private one.
=> fix: rename clashing controller

app/controllers/avo/search_controller.rb
Fixes #1809
When searching on a has many association table, the `fetch_parent` method was directly using `ParentModel.find id` strategy instead `ParentResource.find_record id`
1. Step 1
1. Step 2
=> fix: use resource find record on search instead model direct find

app/components/avo/index/grid_item_component.html.erb
Fixes #1816
When cover type is `file` check if value is present before calling `attached?` on it. Before this PR having a `nil` value on grid cover would break the app, now it renders the `Avo::Index::GridCoverEmptyStateComponent`
1. Step 1
1. Step 2
=> fix: allow nil values on grid cover

app/components/avo/views/resource_show_component.html.erb, lib/avo/resources/controls/action.rb, spec/features/avo/custom_resource_controls_spec.rb
Fixes #1769
Action visibility block runs even on show controls actions now
1. Step 1
1. Step 2
=> fix: action visibility on show controls

.github/PULL_REQUEST_TEMPLATE.md
At some point the documentation for avo was moved from avo-hq/docs to avo-hq/avodocs. The pull request template is still referring to the old docs repository, so I've updated it to point to the current one
NA
=> Make pull request template refer to avodocs not docs

app/components/avo/fields/location_field/show_component.html.erb, lib/avo/fields/location_field.rb
I've added an extra attribute to the location field so you can override the zoom level in the resource. I've also made mapkick show the map controls so users can zoom in and out if they want to.
Right now location fields always load at the default zoom level of 15 and there's no way to customize it.
1. Find a resource with a location field in the code
2. View a model that uses that resource and see the zoom level of the location (should be very zoomed-in)
1. Edit the code so that the field has `zoom: 1`  on the location field
3. Reload the page
4. Check that the location field is now zoomed out really far
=> Added zoom to location fields

lib/avo/base_resource.rb, lib/avo/fields/base_field.rb, lib/avo/fields/location_field.rb, spec/system/avo/location_field_spec.rb
Fixes #1838
1. Step 1
1. Step 2
=> fix: location field new view

lib/avo/concerns/has_fields.rb
Fixes #1842
This pull request resolves an issue where the target of links rendered on the `belongs_to` field was not being properly set when it is placed within a tab row. Since we are utilizing turbo-frames on tabs, all such links should aim the target to `_top` when they are inside tabs.
1. Step 1
1. Step 2
=> fix: belongs to field target inside tab -> panel -> row

app/components/avo/resource_component.rb, app/components/avo/views/resource_edit_component.html.erb, app/components/avo/views/resource_index_component.html.erb, app/components/avo/views/resource_show_component.html.erb, app/components/avo/views/resource_show_component.rb
Fixes #1768
Show controls actions now respect the `act_on?` methods declared on the policies.
1. Step 1
1. Step 2
=> fix: authorize show controls actions

app/javascript/js/controllers/fields/easy_mde_controller.js
Fixes #1843 
This pull request addresses a bug that caused the markdown field value to be hidden until clicked. This issue occurred specifically when the field was displayed within a secondary tab in the edit view.
Inspired from this issue: https://github.com/Ionaru/easy-markdown-editor/issues/499
1. Step 1
1. Step 2
=> fix: markdown field not appearing on edit in tab

app/components/avo/panel_component.html.erb, app/components/avo/panel_component.rb
Adds a new rendering option for PanelComponent sidebars to skip the white background and provide a transparent container instead.
- [N/A] I have commented my code, particularly in hard-to-understand areas
1. In a Panel Component use `with_bare_sidebar` in place of `with_sidebar` and verify that the white background is gone.
=> add with_bare_sidebar to PanelComponent

app/components/avo/resource_component.rb, spec/dummy/app/models/project.rb, spec/rails_helper.rb
Fixes #1873
In order to render the detach button we check for the inverse association using the `inverse_of` method. 
Occasionally, Rails may not identify the inverse association and we were raising an error to instruct where the `inverse_of` configuration is needed. We noticed that many apps was breaking due this error. 
To improve user experience and avoid breaking apps, we have made a modification. Instead of raising an error, we now display a warning during development, providing guidance on the necessity of configuring `inverse_of`.
=> fix: warning instead raising error when can't find the inverse_of

app/controllers/avo/actions_controller.rb, lib/avo/base_action.rb, spec/dummy/app/avo/actions/sub/dummy_action.rb
Fixes #1761 , #1877 
Action's `redirect_to` method now accepts `allow_other_host` and `status` arguments.
It's also possible to turn turbo to false using the `self.turbo = false` action configuration, this is useful for external redirects for example.
=> feature: action redirect allow_other_host and status arguments & actions turbo attribute

Appraisals, Gemfile.lock, gemfiles/rails_6.0_ruby_3.0.3.gemfile, gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock, gemfiles/rails_6.0_ruby_3.2.2.gemfile, gemfiles/rails_6.0_ruby_3.2.2.gemfile.lock, gemfiles/rails_6.1_ruby_3.0.3.gemfile, gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock, gemfiles/rails_6.1_ruby_3.2.2.gemfile, gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock, gemfiles/rails_7.0_ruby_3.0.3.gemfile, gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock, gemfiles/rails_7.0_ruby_3.2.2.gemfile, gemfiles/rails_7.0_ruby_3.2.2.gemfile.lock, spec/dummy/app/models/city.rb, spec/dummy/app/models/comment.rb, spec/dummy/app/models/course.rb, spec/dummy/app/models/course/link.rb, spec/dummy/app/models/fish.rb, spec/dummy/app/models/post.rb, spec/dummy/app/models/project.rb, spec/dummy/app/models/sibling.rb, spec/dummy/app/models/spouse.rb, spec/dummy/app/models/team.rb, spec/dummy/app/models/team_membership.rb, spec/dummy/app/models/user.rb
Vulnerability report: [SNYK-RUBY-RANSACK-5776488](https://security.snyk.io/vuln/SNYK-RUBY-RANSACK-5776488)
Ransack changelog: https://github.com/activerecord-hackery/ransack/blob/main/CHANGELOG.md
We use ransack 4 in production for a while, however since ransack 3.1.0 is a transitive dependency in Avo, the vulnerability scanner continuously reports the problem with the dependency. 
1. Step 1
1. Step 2
=> chore(deps): bump ransack from 3.0.1 to 4.0.0

lib/avo/fields/base_field.rb
Helpers and other included modules were not accessible on the `format_using` and `update_using` execution context.
Fixes https://discord.com/channels/740892036978442260/1137012402899136582
=> fix: include field included_modules on format_using and update_using execution context

CONTRIBUTING.MD
While setting up the project for local development, I've noticed one unclear instruction in the Readme. It instructs to run the `db:seed` command, although seeding is part of the `bin/init` script.
I've decided to add a note to prevent confusion for future contributors.
N/A
1. Setup fresh `avo` repository locally by running `bin/init`
1. Log in to the dashboard with `avo@avohq.io` / `secret` credentials
=> fix: added note about the seeding step to Readme

app/components/avo/fields/common/badge_viewer_component.html.erb, db/factories.rb, lib/avo/fields/badge_field.rb, spec/dummy/app/avo/resources/project_resource.rb, spec/dummy/app/models/project.rb, spec/features/avo/badge_field_spec.rb, spec/features/avo/badge_spec.rb, spec/features/avo/select_field/enum_hash_display_value_true_spec.rb
This PR addresses the feature requirement for including new secondary badge to differentiate option like drafting in badges
Fixes #1909 
1. Created new project in test app using drafting option from stages
=> feature: Added new badge 'secondary' for option like drafting

tailwind.config.js
Fixes #1942 
1. Step 1
1. Step 2
=> fix: remove dummy app files from tailwind.config.js

app/controllers/avo/search_controller.rb
Fixes #1930
This PR applies the scopes before making the count on search.
=> fix: search count is incorrect when attach_scope

lib/generators/avo/tailwindcss/install_generator.rb
Added check to fix issue of showing instruction based on the path of tailwind.config.js file and append the -c ./config/tailwind.config.js to the instructions.
Fixes #1764 
1. Tested code by running `bin/rails generate avo:tailwindcss:install` command for dummy project
2. If we have tailwind.config.js in spec/dummy/config/tailwind.config.js path we get instruction as
`"scripts": { "avo:tailwindcss": "tailwindcss -i ./app/assets/stylesheets/avo.tailwind.css -o ./app/assets/builds/avo.tailwind.css -c ./config/tailwind.config.js" --minify }`
3. If we don't have file in config directory we get instruction as
`"scripts": { "avo:tailwindcss": "tailwindcss -i ./app/assets/stylesheets/avo.tailwind.css -o ./app/assets/builds/avo.tailwind.css" --minify }`
=> Fix: Added check for tailwind.config.js based on its path #1764

app/components/avo/sidebar/item_switcher_component.html.erb, lib/avo/menu/resource.rb, spec/dummy/config/initializers/avo.rb, spec/features/avo/menu_builder_spec.rb, spec/features/avo/menu_item_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1651
In this Pull Request I'm adding an option to pass `params` to the `resource` method on the `MenuBuilder`. It can be a Hash or a Proc that will return a Hash.
Whatever is passed as `params` will be added to the path of the menu item, when navigating to it.
Before this PR, there was a [POC](https://github.com/bryszard/avo/pull/1) on which @Paul-Bob helped me understand the scope of the changes to be done.
In the POC we've identified one caveat for future users of the feature - we don't support having multiple menu items for the same resource, but with different params. The reason is simple - if we have two menu items with the same path, they would be both highlighted as `active` when visited. The workarounds for that using current library …
=> feature: allow params on resource menu item

lib/avo/concerns/fetches_things.rb
Fixes https://github.com/avo-hq/avo/issues/1955
If self.authorization_policy is set on a resource and the current user would pass the check for index? the resource does not show up in the navigation menu. 
Updating the `Services::AuthorizationService.authorize` call in `Avo::Concerns::FetchesThings#get_available_resources` appears to resolve this. 
No tests are failing locally, but I still need to figure out the test suite so that I can test this functionality 
1. Step 1
1. Step 2
=> bug: Update fetches_things.rb to use custom policy if available

lib/avo/app.rb, lib/avo/configuration.rb, lib/avo/execution_context.rb, lib/generators/avo/templates/initializer/avo.tt
Fixes #1982 
1. Step 1
1. Step 2
=> feature: allow custom cache store & improve the computed one

app/components/avo/fields/tags_field/edit_component.html.erb, app/javascript/js/controllers/fields/tags_field_controller.js, lib/avo/fields/tags_field.rb, spec/dummy/app/avo/resources/post_resource.rb
Fixes https://github.com/avo-hq/avo/issues/1926
We're using a JS library to handle tags `@yaireo/tagify`. 
There is a feature there that allows to show to the users tag suggestions - we provide a list of potential suggestions and we have some options around it. 
One of those options is `dropdown.max_items` which we have hard-coded currently to 20.
We want to allow users of Avo to set their own `max_items` limit, keeping the 20 as default.
https://github.com/avo-hq/avo/assets/12682792/f2890331-a9e9-4a11-8b2a-8f6713e98b36
1. Check the `Posts` resource in the dummy app
1. Remove the tags and show how many tags show up (limit is set to 2, there are 3 options, so you should see 2 and info that more tags are there but hidden)
Manual reviewer: please leave a comment with output from the test if …
=> feature: allow suggestions_max_items option on tags field

config/initializers/pagy.rb, lib/generators/avo/templates/locales/avo.es.yml
Hi!
I've started playing around with Avo for a personal project and since I'm using Spanish, I thought that maybe you'd be interested in the translation file. So, here it is. I also added the line to include the `es` locale in Pagy (that took me a bit to find).
Minor note: I added question marks around `are_you_sure_detach_item` text, although the `en` version doesn't have one. Is that on purpose?
=> chore: adds Spanish locale

app/components/avo/views/resource_edit_component.html.erb
The form footer lacked a safeguard for rendering buttons, leading to an issue where the back button attempted to render without a valid path within the belongs_to modal creation.
Fixes #2008 
1. Step 1
1. Step 2
=> fix: create belongs_to from associations with buttons on form footers

app/javascript/js/controllers/action_controller.js, lib/avo/base_action.rb, spec/system/avo/actions_spec.rb
When using `no_confirmation` on actions the form was getting submitted by JS resulting on `UnknownFormat`, changing the way that JS submit to actually click on the form button solved the issue.
Fixes https://discord.com/channels/740892036978442260/1174872788323020911
1. Step 1
1. Step 2
=> fix: redirect on action when no_confirmation = true

app/controllers/avo/associations_controller.rb
[This change](https://github.com/avo-hq/avo/pull/1856/files#diff-b1f64e5509fa895bb0217e2740a262487a1344069c30bef0391e92f05c760b91) intended to make sure that validations / callbacks are called when detaching a record from a `has_many` associations. Unfortunately it introduced a bug where the record getting detached is actually deleted from DB.
[`destroy(*records)`](https://edgeapi.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-destroy)
> ...
This method will always remove record from the database ignoring the :dependent option.
...
Delete is what we want here but [`delete(*records)`](https://edgeapi.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-delete) will not run associations callbacks...
Fixes …
=> fix: detach should not destroy attachment

app/components/avo/fields/belongs_to_field/edit_component.rb, spec/dummy/app/models/course/link.rb, spec/dummy/config/locales/avo.es.yml, spec/system/avo/create_via_belongs_to_spec.rb
` via_resource_id: resource.record.to_param` when `resource.record` is not a persistent yet `to_param` will return `nil` and that's fine. But in case you use `prefix_id` or some other ID manipulation it will break if the attributes used on the manipulation are blank.
Fixes #2045 
1. Step 1
1. Step 2
=> fix: create new record from belongs_to associations

lib/avo/concerns/has_items.rb, spec/dummy/app/avo/resources/user.rb, spec/system/avo/resource_sidebar_spec.rb
Extract fields from sidebars and add them to permitted params.
Fixes #2051
=> fix: extract fields from sidebar and add them to permitted params

app/components/avo/resource_component.rb
On render when we check for `sidebars.any?` we should assure that `sidebars` returns an array even on community license.
Fixes #2047
=> fix: sidebars on community tier

spec/dummy/app/avo/actions/test/no_confirmation_redirect.rb, spec/dummy/app/avo/resources/user.rb, spec/system/avo/actions_spec.rb
Fixes actions spec and remove `class_eval`
=> chore: fix actions spec

avo.gemspec
Fixes an issue where an `application.js` file was mistakenly pushed with the gem.
=> fix: ignore application js file

app/components/avo/fields/belongs_to_field/edit_component.html.erb, app/components/avo/fields/belongs_to_field/edit_component.rb
Removes the div wrap around `belongs_to` field edit component. It was causing a bad layout on froms
Fixes #2063
```ruby
def fields
panel do
row do
field :link, as: :text, help: "Hehe. Something helpful."
field :course, as: :belongs_to, stacked: true
end
end
end
```
=> fix: belongs_to row forms layout

lib/avo.rb, lib/avo/dynamic_router.rb, lib/avo/resources/resource_manager.rb
I saw that v3 has switched to standard Zeitwerk-compatible namespacing and took a look at the implementation, saw some opportunity for tidying up.
~ I have commented my code, particularly in hard-to-understand areas
~ I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
~ I have added tests that prove my fix is effective or that my feature works
I would consider the existing test suite sufficient
=> Refactor Resource loading to simplify and centralize behavior

app/components/avo/fields/has_one_field/show_component.rb, spec/features/avo/create_has_one_spec.rb
`via_resource_class` on create path was missing from `belongs_to` fields. This PR adds `via_resource_class` like we use it on create path for `has_many` field.
=> fix: `via_resource_class` on `belongs_to` fields

lib/avo/concerns/has_items.rb
Main panel fields were fetched twice when `only_root == false`
Fixes #2077
Fixes  [discord thread](https://discord.com/channels/740892036978442260/1138182212655788054/1184003726730592316)
=> fix: main_panel extraction

app/controllers/avo/base_controller.rb, app/javascript/js/controllers/filter_controller.js, lib/avo/filters/base_filter.rb, spec/system/avo/filters/filters_spec.rb
Fixes #2061 
1. Encode and decode filters on JS controller following [mdn official documentation about "the unicode problem"](https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem)
2. Un-silence decoding errors, we had some suppressed errors, that makes some bugs hard to debug and understand.
=> fix: allow all chars on text filters

app/controllers/avo/base_controller.rb
`set_applied_filters` method should ignore dynamic filter params
Fix:
=> fix: dynamic filters

app/controllers/avo/search_controller.rb
Fixes [discord thread](https://discord.com/channels/740892036978442260/1184299599830188092).
`current_user` was called instead `_current_user` helper on the `app/controllers/avo/search_controller.rb`
=> fix: search current_user

lib/avo/fields/status_field.rb
Fixes an issue where dynamic filters would not have options because they are not declared anywhere for the neutral state.
Now, that we declare them in the `neutral_when` option, the dynamic filters will know about them and display them.
1. Using `avo-advanced`
2. Change one project status field to something different `xoxo`
1. Go to the projects Index page and try to set a dynamic filter on `status`
2. Observe that the `xoxo` value is missing
3. now set the `neutral_when` value to `field :status, as: :status, neutral_when: [:xoxo]`
4. se the dynamic filter again and observe that the `xoxo` value is present.
=> fix: status-field dynamic filter missing some options

lib/avo/base_action.rb
Fixes [#150](https://github.com/avo-hq/avodocs/issues/150)
- https://github.com/avo-hq/avodocs/pull/151
1. Step 1
1. Step 2
=> fix: action authorize variables, direct access to `view` and `resource` instead `action.resource.view` 

lib/avo/filters/base_filter.rb
Since we removed the rescue on record to catch relevant errors we should ensure that `params[:filters]` is a string before trying to decode it. When using dynamic filters `params[:filters]` is a Hash
1. Step 1
1. Step 2
=> fix: applied filters when filters are dynamic

lib/avo/fields/belongs_to_field.rb
`belongs_to` name on index was hard-coded.
Fixes #2099
=> fix: `belongs_to` index field name

Gemfile.lock, app/javascript/js/application.js, app/javascript/js/custom-stream-actions.js, app/views/avo/associations/create.turbo_stream.erb, app/views/layouts/avo/application.html.erb, avo.gemspec, gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock, gemfiles/rails_6.0_ruby_3.2.2.gemfile.lock, gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock, gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock, gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock, gemfiles/rails_7.0_ruby_3.2.2.gemfile.lock, gemfiles/rails_7.1_ruby_3.0.3.gemfile.lock, gemfiles/rails_7.1_ruby_3.2.2.gemfile.lock, lib/avo/engine.rb, package.json, yarn.lock
We merged an experimental Turbo 8 PR and this PR will revert that.
=> chore: revert bad turbo 8 merge

lib/avo/fields/concerns/has_html_attributes.rb
When on grid item `action` and `resource` are not accessible so adding stimulus attributes would raise an error `undefined local variable or method 'action' for #<Avo::Index::GridItemComponent...`
1. Step 1
1. Step 2
=> fix: stimulus attributes crashing on grid view

app/components/avo/field_wrapper_component.html.erb, app/components/avo/row_component.html.erb, spec/system/avo/app_spec.rb
Fixes an issue where `row` columns are not equal.
=> refactor: equal width columns in rows

app/components/avo/tab_group_component.rb, app/components/avo/tab_switcher_component.rb, lib/avo/resources/items/tab_group.rb, spec/system/avo/tabs_spec.rb
This PR removes the double `group_param` definition moving it to `Avo::Resources::Items::TabGroup` and delegating to that class when usage is necessary.
Fixes #2265
1. Step 1
1. Step 2
=> fix: tabs persistence when tab name has spaces

lib/avo/services/encryption_service.rb, spec/dummy/config/boot.rb, spec/rails_helper.rb
Fixes #2090
- Only fetch secret key from `Rails.application.secrets.secret_key_base` if rails version is less than `7.2.0`
- Raise custom error when not on production
- Keep same behavior on production
=> fix: secret key base warning

app/controllers/avo/application_controller.rb, lib/avo/fields/status_field.rb, tailwind.preset.js
Fixes an issue where the default values in the status field would render inexistent options in dynamic filters.
=> fix: remove status field defaults and fix the neutral state

lib/avo/execution_context.rb, spec/dummy/app/avo/resources/product.rb
Fixes #2300
Delegating missing methods to view_context on Avo::ExecutionContext allow to direclty use `@view_context` methods without explicitly call it:
`body: simple_format(record.description)`
VS
`body: view_context.simple_format(record.description)`
=> feature: delegate missing to view_context

app/components/avo/views/resource_index_component.rb
Call scopes from `avo-advanced` instead `avo-pro`
=> chore: move scopes from pro to advanced

app/javascript/js/controllers/fields/key_value_controller.js, package.json, yarn.lock
Addresses https://github.com/avo-hq/avo/security/advisories/GHSA-ghjv-mh6x-7q6h
Fixes a security issue where the output for the `key_value` field is not sanitized.
1. Follow the steps in the CVE to test.
=> security: sanitize key_value field content

app/views/avo/partials/_navbar.html.erb
The problem is that our warning from `_custom_tools_alert.html.erb` is currently having an equal precedence (z-index = 50) as the navbar (z-index = 50) which results in this:
I'm setting the z-index of the navbar to 100, which is the same value as flash alerts and modals currently have. Meaning that only those components are allowed to be displayed over the navbar.
After the fix:
1. Run the dummy app and scroll a bit
=> Set z-index for navbar to the highest value, equal only to flash alerts

app/controllers/avo/search_controller.rb
Fixes https://github.com/avo-hq/avo/issues/2014
1. Step 1
1. Step 2
=> Mark highlight search

app/javascript/js/controllers/fields/key_value_controller.js, package.json, yarn.lock
Addresses https://github.com/avo-hq/avo/security/advisories/GHSA-ghjv-mh6x-7q6h
Fixes a security issue where the output for the `key_value` field is not sanitized.
=> security: v2 CVE-2024-22191

app/javascript/js/controllers/search_controller.js
Allows usage of html tags inside search results labels and descriptions. 
`W<mark>rap</mark>safe`:
=> fix: search highlight

app/javascript/avo.base.js, app/javascript/js/controllers/sidebar_controller.js
Fixes https://github.com/avo-hq/avo/issues/2414
This is mainly a refactor to move some global JS code to a StimulusJS controller.
=> refactor: sidebar remember scroll move to controller

lib/avo/services/encryption_service.rb
This helps avoid the rails 7.1 deprecation warning about using `Rails.application.secrets` when no secret key base is explicitly configured, when `Rails.env.local? || ENV["SECRET_KEY_BASE_DUMMY"]`
1. Step 1
1. Step 2
=> Use Rails.application.secret_key_base directly

Gemfile.lock, app/components/avo/index/resource_controls_component.rb, app/controllers/avo/application_controller.rb, spec/dummy/app/avo/resources/course.rb, spec/features/avo/fields_methods_for_views_spec.rb
Fixes #2403 
The detach button request has been updated to no longer hydrate the resource using the `destroy` view, as it was identified as a problematic approach when using `def display_fields` or `def form_fields` API since those methods wouldn't get called. 
To address this, we have modified the process to include passing the current view as parameters during the detach request. This ensures that the appropriate view is properly hydrated into the resource.
[before.webm](https://github.com/avo-hq/avo/assets/69730720/7696b801-fed5-4c8b-bdc4-dd69accbc923)
[after.webm](https://github.com/avo-hq/avo/assets/69730720/4b12ce52-f9d0-4c3b-8a7c-cf1ee9a35cbb)
1. Set a resource with an association field using only `def display_fields` and `def form_fields` API
2. Visit resource's show view
3. …
=> fix: destroy when using forms and display fields API

app/javascript/js/controllers/search_controller.js
Fixes #2416
Clear all HTML tags before updating the belongs_to searchable field with selected option.
=> fix: searchable belongs_to field keep html tags on selected option

lib/avo/base_resource_tool.rb, lib/avo/concerns/has_items.rb, lib/avo/resources/items/holder.rb
Fixes https://github.com/avo-hq/avodocs/issues/163
Try to use the `resource`, `parent`, and `view` in a resource tool initializer.
```ruby
class Avo::ResourceTools::FishInformation < Avo::BaseResourceTool
def initialize(**kwargs)
super(**kwargs)
abort [parent.class, resource.class, view].inspect # 👈 these objects are available in the initializer
end
end
```
=> feature: expose resource in resource tools intializers

README.md
The existing links to the Roadmap 404. I've updated them with the current URL found at https://github.com/avo-hq/avo/projects.
N/a
N/a
=> Update links to Roadmap in README.md

app/components/avo/fields/common/files/view_type/grid_item_component.html.erb
On main, even if you choose to display filenames, filenames are hidden for file fields on avo 3.x. This is happening because the parent flexbox is set to flex row and truncate css class was truncating the text down to 0 width.
To fix this I've made the parent flexbox use flex-col, which puts the filename underneath the image (as it was in avo 2.x) so it doesn't get truncated and can be seen.
Before it looks like this:
On this branch it looks like this:
1. Find a resource with a files component and set `display_filename: true` is set to `true`
2. View it in the browser and confirm that the filename isn't visible
3. Switch to this branch
4. Confirm that the filename is visible now.
=> Stop file field from hiding filename

app/components/avo/field_wrapper_component.rb
If a user added a `data` attribute to a wrapper that Avo already generated for it from the `slef.stimulus_controllers` DSL, it will not be used. Only Avo's will be displayed.
From [here](https://discord.com/channels/740892036978442260/740893011994738751/1201589913125146755)
1. On a resource add the following
```ruby
self.stimulus_controllers = ["foo"]
field :name, as: :text, html: {
edit: {
wrapper: {
data: {
foo_target: "bar baz"
}
}
}
```
2. Before the output on the wrapper element would have been `data-foo-target="nameTextWrapper"`, now it's `data-foo-target="bar baz"`.
=> feature: override auto-generated data attributes

lib/avo/base_resource.rb
Apply same logic that we use to fetch fields but on cards. We should fetch cards only when visiting a dashboard.
Related PR https://github.com/avo-hq/avo-dashboards/pull/31
=> fix: fetch cards only when necessary

app/components/avo/index/resource_controls_component.rb, app/components/avo/views/resource_index_component.rb, spec/dummy/app/avo/resources/course.rb, spec/features/avo/discreet_pagination_spec.rb, spec/features/avo/fields_methods_for_views_spec.rb
Fixes #2403
[This PR](https://github.com/avo-hq/avo/pull/2415) is fetching the view from the `resource` when it should fetch the view from the `parent_resource` because fields will be evaluated on the parent resource when detaching.
It also fixes the need to add a association field on `form_fields` in order to attach.
=> fix: detach when using view *_fields api

app/components/avo/index/resource_controls_component.rb, app/controllers/avo/application_controller.rb, spec/system/avo/app_spec.rb
Fixes a regression (broken index destroy action) introduced here https://github.com/avo-hq/avo/pull/2436
`params[:view]` was passed as empty string `""` and we were doing `params[:view] || action_name.to_s` which would result in empty string `""` since:
```
irb(main):001> "" || "value"
=> ""
```
A resource with the `view` value as `nil` breaks fetching fields. This is fixed now and resource's `view` have the propper value
1. Go to any resource's index
2. Destroy any record
=> fix: index destroy

lib/avo/fields/trix_field.rb
This PR comes in order to fix a critical regression introduced by #2429 which changed 
```ruby
@attachments_disabled = args[:attachments_disabled] || false
```
by
```ruby
@attachments_disabled = args[:attachments_disabled] || true
@attachments_disabled = false unless @attachment_key.present?
```
Unfortunately this created an unexpected behaviour making `@attachments_disabled` always defaulting to `true`. Here is why:
```ruby
irb(main):001> args = {}
=> {}
irb(main):002> args[:attachments_disabled] = false
=> false
irb(main):003> @attachments_disabled = args[:attachments_disabled] || true
=> true
```
This has the side effect of breaking the attachment feature by always disabling it even when specifying an attachment key or manually set the `attachments_disabled` option to `false`.
This PR …
=> fix: Trix field disable_attachments option unexpected behaviour

app/components/avo/fields/common/files/view_type/grid_item_component.html.erb
In #2431 I fixed a bug where (at some point) the filename on a file field was hidden. The fix was only applied to the 3.x branch but I'd like to use it in 2.x as well.
The filename on a file input is hidden.
1. Find a file input on an avo 2.x app
2. Upload a file
3. Confirm that the filename is visible (it should be with this patch, but wasn't before)
=> Backport #2431 to 2.x branch

lib/avo/test_helpers.rb
When using selenium the `type` helper don't work:
```ruby
1.1) Failure/Error: select_first_result_in_search
NoMethodError:
undefined method `keyboard' for an instance of Selenium::WebDriver::Chrome::Driver
```
=> fix: select_first_result_in_search selenium compatible

app/components/avo/sidebar_component.html.erb
We are generating the dashboard path using the path helper instead of taking it from the dashboard.
We are doing it this way so we don't have to pass the params to the path in the dashboards (previous implementation) and let Rails do that itself.
Related PRs:
https://github.com/avo-hq/avo-dashboards/pull/32
https://github.com/avo-hq/avo-menu/pull/17
=> refactor: remove dashboard path

RELEASE.MD, app/views/avo/partials/_header.html.erb, lib/avo.rb, lib/avo/configuration.rb, lib/avo/current.rb, lib/generators/avo/templates/initializer/avo.tt, spec/dummy/app/controllers/avo/switch_accounts_controller.rb, spec/dummy/app/models/user.rb, spec/dummy/config/routes.rb
This PR adds the ability to add concerns to Avo's controllers natively.
This aids the mutitenancy feature.
Docs: https://docs.avohq.io/3.0/multitenancy.html
=> feature: load concerns to Avo's controllers & aid multitenancy

lib/avo/view_inquirer.rb
Fixes #2478 
Fixes creating / updating a resource using:
```ruby
def fields
if view.form?
field :name, as: :text
end
end
```
=> fix: create and update when using `view.form?`

lib/generators/avo/templates/initializer/avo.tt
Updated the default client authorization to nil in avo.tt
In the Avo initializer file, modified the setting for `config.authorization_client` to be nil instead of `:pundit`.
Fixes #2475
1. Step 1
1. Step 2
=> Updated the default client authorization to nil

app/helpers/avo/turbo_stream_actions_helper.rb
Fixes #2385 
`close_action_modal` now updates the `actions_show` to be empty instead removing the frame, keeping the frame there for a new action request.
[before.webm](https://github.com/avo-hq/avo/assets/69730720/1115fbaf-5ac9-4a73-927a-dd3f643c54d1)
[after.webm](https://github.com/avo-hq/avo/assets/69730720/b9874784-589c-4f63-9902-9ec3928ce3f2)
=> fix: double download action

app/controllers/avo/base_controller.rb
Fixes #1944
Save record only once on creation after applying the associations logic.
=> fix: remove duplicate create method

lib/generators/avo/templates/locales/avo.ar.yml, lib/generators/avo/templates/locales/avo.en.yml, lib/generators/avo/templates/locales/avo.es.yml, lib/generators/avo/templates/locales/avo.fr.yml, lib/generators/avo/templates/locales/avo.ja.yml, lib/generators/avo/templates/locales/avo.nb.yml, lib/generators/avo/templates/locales/avo.nn.yml, lib/generators/avo/templates/locales/avo.pt-BR.yml, lib/generators/avo/templates/locales/avo.pt.yml, lib/generators/avo/templates/locales/avo.ro.yml, lib/generators/avo/templates/locales/avo.tr.yml
This PR removes field and resource translations from the default locale file
Fixes [#2494](https://github.com/avo-hq/avo/issues/2494)
1. Step 1
1. Step 2
=> fix: Remove field_translations and resource_translations key

app/controllers/avo/application_controller.rb, lib/avo/configuration.rb, spec/dummy/config/initializers/avo.rb
Enable adding to the `default_url_options` method.
=> feature: Add `default_url_options` support

app/controllers/avo/actions_controller.rb
Fixes #2399
On handle action now `resource == @resource`
Before this PR `resource == @resource.class` because we were targeting it wrong when calling the handle method.
=> fix: resource on action handle

lib/avo/base_action.rb, spec/dummy/app/avo/actions/sub/dummy_action.rb, spec/dummy/app/avo/resources/city.rb, spec/system/avo/actions_spec.rb
Fixes #2496
Action name accept now procs as input: `self.name = -> { "Dummy action #{arguments[:some_argument]}" }`
Also the `self.message` has now context of arguments and view.
- https://github.com/avo-hq/avodocs/pull/176
=> feature: action name as proc

app/views/layouts/avo/application.html.erb, lib/avo/configuration.rb, lib/generators/avo/templates/initializer/avo.tt
Rename `instantclick` to `instant_click` on `turbo` configuration.
- https://github.com/avo-hq/avodocs/pull/178
=> fix: rename instantclick to instant_click

lib/avo.rb
The error message now correctly converts camel case resource names to snake case before displaying the message
Fixes [2515](https://github.com/avo-hq/avo/issues/2515)
1. Step 1
1. Step 2
=> fix: Update error message in MissingResourceError class

app/controllers/avo/base_controller.rb, app/helpers/avo/turbo_stream_actions_helper.rb, app/views/avo/actions/show.html.erb, app/views/layouts/avo/application.html.erb, spec/dummy/app/avo/actions/toggle_inactive.rb, spec/dummy/app/avo/resources/user.rb, spec/system/avo/actions_spec.rb
Fixes https://discord.com/channels/740892036978442260/1029406999227666483/1212776480925290589
`turbo_stream_action_tag` doesn't support the `html` option. It is being replaced with the proper `template` option
=> fix: double download with turbo_temporary

app/components/avo/actions_component.html.erb, app/components/avo/actions_component.rb, app/controllers/avo/base_controller.rb
Fixes #2544 
Reverting to same behavior as versions `<= 3.4.1` where index `@resource` keep last record hydrated. This avoid breaks while evaluating table header and there are fields using `visible: -> { resource.record.... }` checks on a visible field.
Also reverting the usage of `link_arguments` helper internally for generating actions path since it would generate the links always for the last record on the table.
=> fix: visible block

lib/avo/fields/base_field.rb
This PR enables users to override the `has_attribute?` method in order to get access to setters when there are no getters.
=> refactor: conditional fill field

lib/avo/base_resource.rb, scripts/export-tailwind-safelist.js
* Added necessary Tailwind classes to the whitelist. It's needed for avo-pro#46.
* Reverted the use of HashWithIndifferentAccess. No specific tests needed (the functionality is already covered by tests here and in avo-pro).
Not applicable.
=> Drag and drop reordering: Tailwind classes, reverting HashWithIndifferentAccess

app/components/avo/fields/belongs_to_field/edit_component.html.erb
Use the human model name in the link for creating a new polymorphic association, instead of the class name
Right now, when you have a polymorphic belongs to field and you specify the types argument (so the field shows a useful select menu allowing you to choose from the different polymorphic types) it has a link below the select menu saying "Create new <classname>". However, the name it uses for the resource is the class name used in the code, which isn't very user-friendly.
This is what it looks like before (note the class name with modules in the link):
This is what it looks like after:
1. Find a polymorphic belongs to field that uses types, eg. https://main.avodemo.com/avo/resources/comments/549/edit
1. Switch to this branch
1. Confirm that the "create new <classname>" …
=> Use human model name when creating new polymorphic association

app/components/avo/views/resource_index_component.rb
Modified the authorized_to_search? method in the ResourceIndexComponent to hide the search input if the avo_search? policy method is not defined for the resource.
Fixes [#2283](https://github.com/avo-hq/avo/issues/2283)
1. Step 1
1. Step 2
=> Hide search input when avo_search? policy is not defined

lib/generators/avo/install_generator.rb
Fixes #2567
1. Step 1
1. Step 2
=> fix: ensure Account is an ActiveRecord model before generating Avo resource

lib/avo/base_resource.rb
Fixes an issue where the file hash was badly compounded with multiple-word resources.
`Avo::Resources::CourseLink` would look for `app/avo/resources/courese link.rb` file which didn't exist.
Now it will look for `app/avo/resources/courese_link.rb`.
=> fix: multiple word resources bad cache hash

app/assets/stylesheets/css/fields/tags.css, app/components/avo/fields/tags_field/edit_component.html.erb, package.json, yarn.lock
Fixes some tags issues by updating tagify and adjust some styles.
=> chore: update tags and fix styles

app/controllers/avo/application_controller.rb, spec/features/avo/controller_action_spec.rb
Fixes #2605
Keep original `new` / `edit` views when `create` / `update` actions are executed.
=> fix: keep original view after run update or create actions

app/javascript/js/controllers/fields/date_field_controller.js, lib/avo/fields/date_time_field.rb, spec/system/avo/date_time_fields/timezone_spec.rb
Fixes #2510 
Flatpickr is always using the local timezone when editing. If `timezone` option is present it will ignore it. With this PR we change the timezone of the selected input keeping the date and time values before converting it to UTC.
Force timezone option when `UTC` to `Etc/UTC` on edit due this issue https://github.com/moment/luxon/issues/1358
=> fix: date_time fields timezone

app/controllers/avo/base_controller.rb, spec/system/model_errors_spec.rb
Fixes #2602 
Collect errors from record even if nothing is raised. Errors can be added on callbacks without raising exception. Action fail if any error is present
=> fix: collect errors from record without exception

avo.gemspec
Fixes #2411 
Keep `avo.custom.js` template on build, remove only the dummy app `avo.custom.js` file.
=> fix: keep avo.custom.js template on build

app/controllers/avo/search_controller.rb
Fixes #2581
On a STI situation when `self.link_to_child_resource = true` search results now respect the correct resource url.
https://github.com/avo-hq/avo/assets/69730720/151f5d21-ec3e-41a0-b24d-74932ee858ea
=> fix: search when link_to_child_resource

.github/workflows/feature-tests.yml, .github/workflows/system-tests.yml, .github/workflows/undercover.yml, Gemfile, Gemfile.lock, app/controllers/avo/application_controller.rb, gemfiles/rails_6.1_ruby_3.1.4.gemfile, gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock, gemfiles/rails_6.1_ruby_3.2.2.gemfile, gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock, gemfiles/rails_6.1_ruby_3.3.0.gemfile, gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock, gemfiles/rails_7.1_ruby_3.1.4.gemfile, gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock, gemfiles/rails_7.1_ruby_3.2.2.gemfile, gemfiles/rails_7.1_ruby_3.2.2.gemfile.lock, gemfiles/rails_7.1_ruby_3.3.0.gemfile, gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock, scripts/merge_coverage.rb, spec/spec_helper.rb
=> Enable coverage in Undercover CI

app/controllers/avo/base_controller.rb, spec/dummy/app/avo/resources/post.rb
This enables the possibility to define a proc on `default_view_type` option. It's useful when we want different default view types according to the user or used device.
```ruby
class Avo::Resources::Post < Avo::BaseResource
self.default_view_type = -> {
mobile_user = request.user_agent =~ /Mobile/
mobile_user ? :table : :grid
}
end
```
- https://github.com/avo-hq/avodocs/pull/188
=> feature: callable `default_view_type`

app/controllers/avo/base_controller.rb
Fixes https://discord.com/channels/740892036978442260/1201874761546735636/1225395037047619664
Ensure that record is present when `detect_fields` is called on `new` action.
=> fix: hydrate resource with record when detect_fields on new

app/components/avo/views/resource_index_component.rb
Implement resource search functionality in cases where there are no existing policies defined for the resource.
Fixes https://discord.com/channels/740892036978442260/1223913103998193664
=> fix: resource search

app/components/avo/fields/select_field/show_component.html.erb
Fixes select field on boolean attributes when value is false.
```ruby
field :is_capital,
as: :select,
options: {
'Yes': true,
'No': false
}
```
1 - Before
2 - After
=> fix: select boolean false value

.github/workflows/undercover.yml, app/controllers/avo/application_controller.rb
Fixes command typo and adds an untested patch to check the full feedback loop with Undercover.
1. Step 1
1. Step 2
=> Fix typo in undercover.yml GitHub Action workflow

app/controllers/avo/application_controller.rb
Impressively, this seems to be all that's required to support composite primary keys in Rails 7.1
Support composite primary keys on show, edit, update and destroy actions on Rails 7.1.
`params.extract_values` was [introduced in Rails 7.1.0.beta1](https://github.com/rails/rails/commit/da7a6da4e7f5caf227420c550a8a13550dd9c682).
Not really.
We do have a model that uses 3 enums as primary keys and I was able to view it's show page, edit and update it after the change. To implement the change in our codebase we have overwriting `set_record` on each resource that has a composite primary key.
=> Support composite primary keys on show, edit, update and destroy actions

app/components/avo/panel_component.html.erb
- Ensure Resource titles are always visible.
- Action buttons don’t wrap to new lines
- Breadcrumb always spans full width
Makes a few changes to the layout of the Resource header.  Mainly it always ensures that no data is obscured or cut off. 
Yes, it does make pages longer but i feel it's more important to be able to see the content than have shorter pages. 
Before:
After:
=> Layout tweaks to Resource header area

app/components/avo/resource_component.rb, app/components/avo/views/resource_edit_component.rb, app/components/avo/views/resource_show_component.rb, lib/avo/concerns/request_methods.rb, spec/components/avo/views/resource_show_component_spec.rb
Preserve page number when going back from resource show page.
Page number is fetched from referral url by parsing its query params.
Another approach can be using pagination data from index page as a parameter for generated links and then just checking `params` for `back_path`. The problem with this option is not that we will have to pass `@pagy` down through components tree, but that page number will be present in show links as well, which seems redundant.
Fixes [#1555](https://github.com/orgs/avo-hq/projects/8?pane=issue&itemId=47768610)
1. Run local dummy app
2. Open project list and go to page 2
3. Select some project and open show page
4. Click 'Go back'
5. Make sure you are on page 2 
=> fix: preserve page when go back from resource show page (#1555)

spec/dummy/db/schema.rb
Adds missing `ChangePriceInProducts` from #2669 migration to dummy app SQL schema.
=> Add missing migration to dummy app

lib/avo/fields/boolean_group_field.rb, lib/avo/fields/select_field.rb
Using instance variable instead the reader method slightly increase performance. Reader methods that are not used outside the class can be removed.
=> chore: performance tweak on boolean group field and select field

app/components/avo/field_wrapper_component.html.erb, app/components/avo/panel_component.html.erb, app/controllers/avo/base_controller.rb, lib/avo/base_resource.rb, spec/dummy/config/environments/development.rb, tailwind.preset.js
This PR makes the value section of the field take up all the space it can when there is a sidebar present.
=> enhancement: full-width fields when sidebar present

app/controllers/avo/application_controller.rb, spec/system/avo/reload_button_spec.rb
Fixes https://github.com/avo-hq/avo/issues/2687
=> fix: leaky global default_url_options

app/controllers/avo/associations_controller.rb
Fixes #2568
`record` variable on `detach_...` method was actually the parent record instead the detached record as expected and documented.
please leave a comment with output from the test if that's the case.
=> fix: detach action record

app/javascript/js/controllers/menu_controller.js
Fixes an issue where the sidebar section and group would animate in on page refresh.
Related to https://github.com/avo-hq/avo/pull/2695
=> fix: bad animation for menu on reload

lib/generators/avo/concerns/override_controller.rb
Fixes #2710
Check proper directory for internal controller override. Engine dir instead app one.
=> fix: check proper dir for internal controller override

lib/avo.rb
Eager load `Avo::Actions`. Fixes direct access through an action link after booting up the app without needing to visit resource's index first.
=> fix: eager load actions

app/components/avo/index/resource_table_component.rb
Fixes #2732
Caching before render instead inside initializer to avoid:
```
ActionView::Template::Error (`#controller` can't be used during initialization, as it depends on the view context that only exists once a ViewComponent is passed to the Rails render pipeline.
It's sometimes possible to fix this issue by moving code dependent on `#controller` to a [`#before_render` method](https://viewcomponent.org/api.html#before_render--void).):
```
=> fix: cache_table_rows

app/components/avo/index/resource_table_component.rb, app/views/layouts/avo/application.html.erb
Fixes #2732
Refactor rows and header cache
=> fix: table cache

lib/avo/fields/trix_field.rb
Check if `ActionText::RichText` is defined before use it.
Fixes #2738
=> fix: check if ActionText::RichText is defined

lib/avo/menu/menu.rb
When updating the `json` gem from 2.7.1 to [2.7.2](https://github.com/flori/json/blob/master/CHANGES.md#2024-04-04-272) in our Rails 7.1.3/Ruby 3.3.0 application we got the error
> NameError:
uninitialized constant OpenStruct
./vendor/bundle/ruby/3.3.0/gems/avo-2.49.0/lib/avo/menu/menu.rb:1:in <main>
when running our rspec test suite. The error was resolved by adding `require "ostruct"`
1. Step 1
1. Step 2
=> require ostruct in case other gems are not doing so

app/components/avo/fields/common/heading_component.html.erb, app/components/avo/fields/common/heading_component.rb
Allow html option classes for heading field wrapper:
```ruby
field :user_information, as: :heading, html: -> {
edit do
wrapper do
classes do
record.something? ? "hidden" : ""
end
end
end
}
```
=> feature: html classes for heading wrapper

app/components/avo/field_wrapper_component.html.erb, lib/avo/concerns/breadcrumbs.rb, lib/avo/concerns/can_replace_items.rb, lib/avo/concerns/checks_assoc_authorization.rb, lib/avo/concerns/has_items.rb, lib/avo/concerns/visible_in_different_views.rb, lib/avo/fields/base_field.rb, lib/avo/fields/belongs_to_field.rb, lib/avo/fields/concerns/frame_loading.rb
Fixes https://github.com/avo-hq/avo/issues/1929
=> fix: wrong label on `belongs_to`field

app/controllers/avo/base_controller.rb
Fixes wrong default table order introduced by https://github.com/avo-hq/avo/pull/2756
=> fix: default sort

app/javascript/js/controllers/fields/tags_field_controller.js
Fixes https://github.com/avo-hq/avo/issues/2763
=> fix: tags dissapearing when using fetch_valeus_from option

app/components/avo/fields/boolean_group_field/edit_component.html.erb, app/components/avo/fields/boolean_group_field/edit_component.rb, lib/avo/fields/boolean_group_field.rb, spec/dummy/app/avo/actions/sub/dummy_action.rb, spec/system/avo/actions_spec.rb
Fixes #2569
Boolean group field was not respecting the form scope. For this reason, on actions, it's values was getting passed through params outside `fields` scope behaving as unpermitted params.
This PR also drops `record` dependency for boolean group fields. Now it can be used for example on an action from index view.
=> fix: boolean group field on actions

lib/avo/base_action.rb
Implement message truncation to 320 characters on action.
Fixes https://github.com/avo-hq/avo/issues/2707
1. Step 1
1. Step 2
=> fix: truncate long action messages to avoid overflow

.erb-lint.yml, .erb-lint_rubocop.yml, Gemfile, Gemfile.lock, gemfiles/rails_6.1_ruby_3.1.4.gemfile, gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock, gemfiles/rails_6.1_ruby_3.2.2.gemfile, gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock, gemfiles/rails_6.1_ruby_3.3.0.gemfile, gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock, gemfiles/rails_7.1_ruby_3.1.4.gemfile, gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock, gemfiles/rails_7.1_ruby_3.2.2.gemfile, gemfiles/rails_7.1_ruby_3.2.2.gemfile.lock, gemfiles/rails_7.1_ruby_3.3.0.gemfile, gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock, spec/system/avo/filters/filters_spec.rb, spec/system/avo/filters_panel_open_spec.rb, spec/system/avo/select_all_spec.rb
=> chore: add erb_lint

app/views/avo/base/create_fail_action.turbo_stream.erb, spec/dummy/app/avo/filters/course_city_filter.rb, spec/system/avo/has_many_spec.rb
Fixes an error that on record creation, non-record error were swallowed and not displayed.
Example errors:
- foreign key constraints
- misc API connections down the request line
=> fix: add model-unrelated errors to alerts

app/javascript/js/controllers/card_filters_controller.js
Updated the query parameter in frame.src from `date` to `global_range[date]` in the updateCards method of card_filters_controller.js to reflect the new parameter naming convention.
Related to [dashboard-wide filters](https://github.com/avo-hq/avo-dashboards/pull/36)
1. Step 1
1. Step 2
=> Update date param to global_range

app/components/avo/index/resource_controls_component.rb, lib/generators/avo/templates/initializer/avo.tt
Adds a few more prefixes to `svg`s.
Related to https://github.com/avo-hq/avo/pull/2783
=> fix: add a few more svg prefixes

app/controllers/avo/search_controller.rb
The authorization_policy on the resource should be used when set in the search controller.
Fixes something similar to #2799 (related to #2805)
#2805 fixed most of the test failures for us, but this PR is still necessary to get them all passing.
Here's the [test run](https://github.com/rubygems/rubygems.org/actions/runs/9325667018/job/25673035487?pr=4745) that failed.
This is the commit without the fix applied that fails: https://github.com/rubygems/rubygems.org/pull/4745/commits/4726858ea8a102e3ecf3bec3c43a4c5d412048b0
Specifically, the search controller test failure is caused in [test/integration/avo/gem_name_reservations_controller_test.rb:15](https://github.com/rubygems/rubygems.org/blob/8c6080fbc313712c134b3f433297695640209f2b/test/integration/avo/gem_name_reservations_controller_test. …
=> Use correct policy class in search controller

app/components/avo/actions_component.rb, app/components/avo/divider_component.html.erb, app/components/avo/divider_component.rb, app/controllers/avo/base_controller.rb, lib/avo/base_resource.rb, lib/avo/divider.rb, spec/dummy/app/avo/resources/user.rb, spec/features/avo/divider_spec.rb
Fixes https://github.com/avo-hq/avo/issues/2672
[Test for divider in actions_list in show_controls](https://github.com/avo-hq/avo-advanced/pull/35)
1. Step 1
1. Step 2
=> Action list dividers with labels

app/components/avo/divider_component.html.erb, app/controllers/avo/application_controller.rb, app/controllers/avo/base_controller.rb, lib/avo/configuration.rb, spec/dummy/app/avo/resources/project.rb, spec/dummy/config/initializers/avo.rb, spec/features/action_icon_and_divider_spec.rb, spec/features/avo/divider_spec.rb
This fixes the way locales are being handled and a bug that required the user to run a URL with `set_locale` twice to actually have it visible.
This will enable to set the `config.locale` in the initializer and Avo will use that one independently of the apps locale.
=> fix: set_locale param not setting the locale properly

app/views/avo/actions/show.html.erb, spec/system/avo/tabs_spec.rb
Fixes an issue where the same field configuration would behave differently in a resource edit form and an action form.
Now, the behavior is more consitent.
From here: https://discord.com/channels/740892036978442260/1250828661314027540
=> fix: remove client-side validation on action forms

lib/avo/fields/tags_field.rb, spec/system/avo/tabs_spec.rb, spec/system/avo/tags_spec.rb
Fixes #2724
Acts as taggable on stores the tags values through DB tables. When the record is not DB persistent (on a new unsaved record) the tags values only can be accessed directly from the record's tag list. `tag_list_on(acts_as_taggable_on_option)` helper does the trick.
[acts_as_taggable_on_fix.webm](https://github.com/avo-hq/avo/assets/69730720/e7bc27af-36f0-46b1-9726-f41889ea6b56)
=> fix: persist values after validation errors on tags fields that acts as taggable on

app/controllers/avo/associations_controller.rb
Fixes the detach action when used on a association field that uses `for_attribute`
=> fix: associations for_attribute detach

lib/generators/avo/all_resources_generator.rb, lib/generators/avo/install_generator.rb, lib/generators/avo/resource_generator.rb
Fixes an issue where the generators would fail if there were pending migrations.
This is common if you install rails, run the devise generator and then Avo's.
This PR also brings a new command `all_resources` which will generate all resources.
We're now stuck at generating all the resources. The `all_resources` generator will not continue past the first resource it finds.
1. Step 1
1. Step 2
=> fix: generators can run without prior migrations

lib/generators/avo/resource_generator.rb
Fixes 
```
Something went wrong while trying to geenrate an Avo resource: undefined method `check_all_pending!' for #<ActiveRecord::Migration:0x00007f34c44262b0 @name="ActiveRecord::Migration", @version=nil, @connection=nil>
```
https://github.com/avo-hq/avo/actions/runs/9612901197/job/26514493416
=> fix: resource generator db check

app/controllers/avo/search_controller.rb, lib/avo/configuration.rb, lib/generators/avo/templates/initializer/avo.tt, spec/dummy/config/initializers/avo.rb
This PR adds a new configuration called search_results_count which lets the user specify the number of results to display after searching.
Currently this number is 8 and avo provides no way to change this number.
Fixes #2885
1. Logged into avo. Typed 'a' in projects search box. Verified that 8 search results are displayed.
2. Changed the search_results_count variable to 10 in spec/dummy/config/initializers/avo.rb.
3. Typed 'a' in projects search box. Verified that 10 search results are displayed now.
=> Add search_results_count to configuration

app/javascript/js/controllers/fields/code_field_controller.js
Fixes an issue where the `code` field might be duplicated in some navigation scenarios.
=> fix: code mirror does not disconnect properly

app/components/avo/field_wrapper_component.html.erb, app/components/avo/field_wrapper_component.rb, app/views/avo/base/preview.html.erb
Tweak the design of the preview field.
=> refactor: preview field tweaks

spec/dummy/db/seeds.rb
I just noticed that [Unsplash](https://unsplash.com/) now requires a developer account, hence seeding the dummy app was broken.
I changed it to Picsum ✌
=> Change dummy photo service from unsplash to picsum

app/components/avo/fields/belongs_to_field/index_component.html.erb, lib/avo/fields/belongs_to_field.rb, spec/dummy/app/avo/resources/comment.rb, spec/dummy/app/avo/resources/post.rb, spec/features/avo/belongs_to_spec.rb
This adds support for `link_to_record` to `belongs_to` field, meaning on index view it will link to the record instead of the associated record.
Closes already closed #2689.
1. Step 1
1. Step 2
=> Add link to record support to belongs to field

app/components/avo/sidebar/base_item_component.rb
Fixes #2833
This feature hides all empty menu groups and sections.
=> feature: hide empty menu groups and sections

app/javascript/js/controllers/fields/tags_field_controller.js, lib/avo/fields/tags_field.rb
Fixes #2922 
Properly apply `delimiters` on the tags field.
Format tags' param value using the first delimiter then split them using the same delimiter.
=> fix: tags delimiters

app/components/avo/fields/belongs_to_field/edit_component.html.erb, lib/avo/fields/belongs_to_field.rb
Fixes #2723
Apply the target resource policy on the belongs_to field create new link.
- https://github.com/avo-hq/docs.avohq.io/pull/232
=> feature: apply target resource policy on belongs_to field create new link

README.md, app/components/avo/fields/common/files/view_type/grid_item_component.html.erb, app/components/avo/index/grid_cover_empty_state_component.html.erb, app/components/avo/index/grid_item_component.rb, lib/avo/base_resource.rb, lib/avo/fields/base_field.rb
Applies the changes from these PRs
https://github.com/minthesize/avo/pull/1
https://github.com/minthesize/avo/pull/2
=> performance: perf optimizations

lib/avo/base_action.rb, spec/dummy/app/avo/actions/test/do_nothing.rb, spec/dummy/app/avo/resources/user.rb, spec/system/avo/actions_spec.rb
Added `do_nothing` alias for `close_modal` as described in issue #2944
Fixes #2944
1. head to http://localhost:3030/admin/resources/users/new
2. click "Actions"
3. click "Do nothing"
4. click "Run" 
=> Feature: alias close_modal action response to do_nothing

app/components/avo/fields/trix_field/edit_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/2714
=> fix: trix and action text improvements

lib/avo.rb
Fixes #2962 
A short informative message with a redirect to [a more detailed documentation](https://docs.avohq.io/3.0/upgrade.html#upgrade-from-3-7-4-to-3-9-1) about a rails 7.1 path helpers issue.
=> chore: rails 7.1 warning

app/components/avo/fields/date_time_field/edit_component.html.erb, app/components/avo/fields/time_field/edit_component.html.erb, app/javascript/js/controllers/fields/date_field_controller.js, lib/generators/avo/templates/locales/avo.ar.yml, lib/generators/avo/templates/locales/avo.en.yml, lib/generators/avo/templates/locales/avo.es.yml, lib/generators/avo/templates/locales/avo.fr.yml, lib/generators/avo/templates/locales/avo.ja.yml, lib/generators/avo/templates/locales/avo.nb.yml, lib/generators/avo/templates/locales/avo.nn.yml, lib/generators/avo/templates/locales/avo.pt-BR.yml, lib/generators/avo/templates/locales/avo.pt.yml, lib/generators/avo/templates/locales/avo.ro.yml, lib/generators/avo/templates/locales/avo.tr.yml, spec/dummy/config/locales/avo.en.yml, spec/system/avo/date_time_fields/date_time_spec.rb, spec/system/avo/date_time_fields/time_spec.rb
This PR adds a button to nullify date_time fields.
Fixes #2770
This is how it looks right now:
=> Create button to nullify date_time fields

.github/workflows/i18n-tests.yml, .github/workflows/system-tests.yml, spec/system/i18n_spec.rb
Creates a separate job to run i18n specs.
Fixes #2957 
1. Step 1
1. Step 2
=> Run i18n_specs in a separate job

app/components/avo/fields/boolean_field/index_component.html.erb, app/components/avo/fields/boolean_field/show_component.html.erb, spec/system/avo/boolean_field_spec.rb
When a boolean field is nullable, it shows false as a red X instead of a dash.
Fixes #2996.
1. Step 1
1. Step 2
=> [#2996] - Change boolean field to show dash when null

lib/avo/resources/items/tab.rb, spec/features/avo/tabs_panels_and_sidebar_visibility_spec.rb
This PR adds a `visible` option to Tab, which should hide all the contained fields as well as the tab itself.
This new option shouldn't affect `tabs` only `tab`
https://github.com/user-attachments/assets/92d3e602-de77-42b8-83c8-6956ff38a2a3
1. Add `visible: -> { false }` to a `tab`
2. Make sure it hides all the tab header and all fields contained
3. Move set it back to true and they should reappear
5. Ensure it doesn't hide anything when visible isn't set
=> feature: add visible option to tab

app/controllers/avo/base_controller.rb, lib/avo/resources/base.rb, spec/dummy/app/avo/resources/course.rb, spec/features/avo/default_sort_column_spec.rb
This PR adds the ability to customize the default sorting attribute. The sorting column for the index view is `created_at` by default, but now the user can customize that by setting the `default_sort_column` option in the resource file to the desired default sorting column.
We still use `created_at` as the default sorting column if:
* `default_sort_column` is not set
* `default_sort_column` is set, but the model doesn't have that column
This also allow for backwards compatibility.
Fixes #2982
https://github.com/user-attachments/assets/0837ffdb-c4b6-40e0-984b-6a7dc73dc6a9
Tip: You can use the console log to see what column is being used for sorting when fetching the records (or just look at the UI)
1. Open any model's index page
2. Verify that it's sorting by `created_at`
3. Set the …
=> feature: add `default_sort_column` configuration option

app/components/avo/turbo_frame_wrapper_component.html.erb, lib/avo/asset_manager.rb, lib/generators/avo/eject_generator.rb
Fixes an issue where, sometimes, the asset files would be added multiple times.
Also fixes https://github.com/avo-hq/avo/issues/2978
=> fix: assets outputted multiple times

app/controllers/avo/search_controller.rb, spec/dummy/app/avo/resources/project.rb, spec/features/avo/search_custom_results_spec.rb
Fixes #3012 
```ruby
self.search = {
query: -> {
array = []
30.times do |iteration|
array << {
_id: iteration,
_label: "Label nr #{iteration}",
_url: "https://#{iteration}.ro"
}
end
array
}
}
```
[search_results.webm](https://github.com/user-attachments/assets/e5f1e5d3-c9c2-4a51-b192-e3d48fbd8adc)
- https://github.com/avo-hq/docs.avohq.io/pull/253
=> feature: custom search results

app/assets/stylesheets/css/sidebar.css, app/components/avo/sidebar_component.html.erb, app/javascript/js/controllers/sidebar_controller.js, app/views/avo/partials/_navbar.html.erb
Currently the functionality for the show/hide of the sidebar uses 'el-transition' for the sidebare ease-in/out but nothing for the main body. It looks uneven. I've changed them both to use css transitions and have removed some unneccesary code. Works on all viewport sizes
Fixes # No Issue
**Old functionality:**
https://github.com/user-attachments/assets/0004757a-f44c-4d13-bdb3-76392d0ee49e
**New functionality**
https://github.com/user-attachments/assets/4fcef603-1bc1-4f46-a19a-fcfeeb12118f
Click on the hamburge icon on any viewport size
=> Fix: css based solution for sidebar without js dependency

app/views/avo/partials/_custom_tools_alert.html.erb, lib/avo.rb, lib/avo/error_manager.rb, spec/dummy/app/avo/resource_tools/team_membership_tool_playground.rb, spec/dummy/app/avo/resources/membership.rb
Fixes #3030
Hide rails 7.1 version error on production.
=> fix: exclude rails 7.1 version error from production

spec/features/avo/avo_warning_spec.rb
This adds tests for #3054
1. Step 1
1. Step 2
=> Write test for warnings

app/controllers/avo/associations_controller.rb, spec/dummy/app/models/team_membership.rb, spec/dummy/app/models/user.rb, spec/features/avo/has_many_field_spec.rb
Fixes #2512
1. Step 1
1. Step 2
=> Feature: Run callbacks on through model when detaching association

spec/system/avo/sign_out_dropdown_spec.rb
Fixes sign-out test by clicking specifically on the "per page" text instead of randomly clicking on the body, as the random clicks were occasionally opening the search modal.
=> fix: sign_out test

app/controllers/avo/actions_controller.rb, lib/avo/base_action.rb, spec/dummy/app/avo/actions/sub/dummy_action.rb, spec/system/avo/actions_spec.rb
Fixes #3025 
Fetch fields on each action request instead of on each action initialization.
=> performance: don't fetch fields on action's initialization

lib/avo/resources/items/tab_group.rb, spec/dummy/app/avo/resources/fish.rb, spec/features/avo/tabs_panels_and_sidebar_visibility_spec.rb
This PR adds a `visible` option to tabs, which should hide all the contained tabs and their fields.
https://github.com/user-attachments/assets/f4ec6cfa-e2d3-401b-a050-1c91d8767107
1. Add `visible: -> { false }` to a `tabs`
2. Make sure it hides all the tabs inside of it and their fields
3. Move set it back to true and they should reappear
5. Ensure it doesn't hide anything when visible isn't set
=> add visible option for tabs

app/components/avo/sidebar_component.html.erb, app/controllers/avo/application_controller.rb, app/javascript/js/controllers/sidebar_controller.js, app/views/avo/partials/_navbar.html.erb
This PR ensures that the correct cookie is set after a user toggles the sidebar
Fixes #3059
https://github.com/user-attachments/assets/a6498a28-5f49-496e-9be6-edb72ba66cfd
1. Step 1
1. Step 2
=> Fix: Side menu always displays

app/controllers/avo/associations_controller.rb
Use `@reflection` ivar instead of fetching the reflection on each `reflection` method usage
=> performance: use `@reflection` ivar on associations controller

lib/avo/base_resource.rb, lib/avo/fields/belongs_to_field.rb, lib/avo/fields/has_base_field.rb
:construction: This targets 2.x branch.
- `_reflections` returns different key type per Rails version
:information_source: Model.reflections seems supported for 6.0+ (I have not checked earlier versions since those seems unsupported).
:bulb: This fixes issues at RubyGems.org with Rails 7.2 beta compatibility.
=> refactor: Prefer Model.reflections over private Model#_reflections.

app/components/avo/actions_component.html.erb, app/components/avo/actions_component.rb, app/components/avo/resource_component.rb, app/javascript/avo.base.js
Fixes #2975 
```ruby
class Avo::Resources::Fish < Avo::BaseResource
self.index_controls = -> do
actions_list style: :primary, color: :slate, label: "", title: "Cool popover!"
end
end
```
=> feature: popovers in action lists

lib/avo.rb, lib/avo/fields/base_field.rb
Fixes #3068 
When rendering a polymorphic field and one of the types doesn't have a valid resource the custom error is confusing:
```ruby
field :reviewable,
as: :belongs_to,
polymorphic_as: :reviewable,
types: [::Fish, ::Post, ::Project, ::Team]
```
I deleted the `Avo::Resources::Team` to generate the errors.
```
Failed to find a resource while rendering the :team field.
You may generate a resource for it by running 'rails generate avo:resource team'.
Alternatively add the 'use_resource' option to the :team field to specify a custom resource to be used.
More info on https://docs.avohq.io/3.0/resources.html.
```
```
Failed to find a resource while rendering the :reviewable field.
You may generate a resource for it by running 'rails generate avo:resource team'.
Alternatively add the …
```
=> fix: MissingResourceError on polymorphic field

lib/avo/resources/base.rb
This change makes in possible to use `default: true` when toggling a default scope without wrapping it into a arguments hash. Related comment: https://github.com/avo-hq/avo-advanced/pull/42
Fixes #2402
Related PR: https://github.com/avo-hq/avo-advanced/pull/42
(Tests are in the advanced repo. PR linked above)
1. Step 1
1. Step 2
=> Feature: Set default scopes

app/components/avo/actions_component.rb, app/controllers/avo/actions_controller.rb, app/views/avo/actions/show.html.erb, lib/avo/base_action.rb
Fixes #3021
`set_record` on `handle` request (only on show pages) to make it available while fetching fields.
=> fix: `set_record` when fetching `fields` on actions' `handle`

app/components/avo/sidebar/base_item_component.rb
Fixes https://discord.com/channels/740892036978442260/1138182212655788054/1270409584024096952
Check for `visible?` on all items before rendering the menu group/section
=> fix: hide empty menu groups and sections

.github/workflows/codeql.yml, .github/workflows/feature-tests.yml, .github/workflows/i18n-tests.yml, .github/workflows/lint.yml, .github/workflows/system-tests.yml, .github/workflows/test-tailwindcss-integration.yml, app/components/avo/fields/belongs_to_field/edit_component.html.erb
Implements gh actions' [concurrency](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency) which will stop previous CI actions on each new commit, avoiding creating big workflow queues.
=> chore: gh actions' concurrency

app/controllers/avo/application_controller.rb, app/javascript/js/controllers/sidebar_controller.js
Fixes https://discord.com/channels/740892036978442260/1270822164345524316
Fixing a bug that was introduced [here](https://github.com/avo-hq/avo/pull/3064).
`Some cookies are misusing the recommended “SameSite“ attribute` was getting raised which led to some strange behaviors.
=> fix: Some cookies are misusing the recommended “SameSite“ attribute

app/components/avo/views/resource_index_component.rb, lib/avo/concerns/has_controls.rb, spec/features/avo/breadcrumbs_spec.rb
This PR adds a back button when association pages are opened in their own window.
Fixes #3061
https://github.com/user-attachments/assets/09ce786c-9c5b-40ab-b5e9-6159106db373
1. Step 1
1. Step 2
=> Feature: Add back button to association pages

app/controllers/avo/search_controller.rb, app/javascript/js/controllers/search_controller.js
Fixes #3091
Related PR: https://github.com/avo-hq/avo-pro/pull/85
Raises an informative error (is displayed only on development) whenever a field has `searchable: true` but the target resource doesn't have the search configured.
https://github.com/user-attachments/assets/b8e3dd7f-0f6c-4ba0-a107-64b6521223e6
=> feature: informative development error when search misconfigured

lib/tasks/avo_tasks.rake
Fixes #3107
_All tests were done on my local machine._
`rails avo:sym_link` was taking around 6 seconds to execute.
With this improvement, it went down to around  3 seconds, where 90% of the execution time is starting the task, not the actual task code.
The execution time of the code inside the task was decreased drastically.
If the code from the task were executed on a bash script it would cut all the time required for starting the task but we need it on the task to enhance on `assets:precompile`.
If from the task we call a script instead the execution time is almost the same, there are no significant improvements.
=> performance: sym_link

app/components/avo/paginator_component.html.erb, app/components/avo/paginator_component.rb, spec/system/avo/filters/filters_spec.rb
Fixes an issue where pagy `data-turbo-frame` was missing. Pagy 9 brings this breaking change where the `anchor_string` need to be passed on the front end helpers instead of passing it to the `pagy` method in the controller.
I have also removed the `attr_reader`s from the `Avo::PaginatorComponent` in favor of the instance variables as a performance tweak.
=> fix: pagy 9 `data-turbo-frame`

lib/avo/concerns/pagination.rb, lib/generators/avo/templates/initializer/avo.tt
Fixes #3049 
Dropping the [array legacy API](https://ddnexus.github.io/pagy/docs/extras/size/) in favor of integer.
- https://github.com/avo-hq/docs.avohq.io/pull/276
=> chore: change pagy default size to integer

app/components/avo/actions_component.rb, spec/system/avo/actions_spec.rb
Fixes #3135
Fix action arguments regression introduced [here](https://github.com/avo-hq/avo/pull/3093).
=> fix: actions arguments

app/javascript/avo.base.js
Temporarily fixes #2607
I subscribed to [the PR](https://github.com/hotwired/turbo/pull/1227) that natively fixes [the turbo issue](https://github.com/hotwired/turbo/issues/886). We should revert this temporary fix after [the PR](https://github.com/hotwired/turbo/pull/1227) gets merged.
This solution appears to fix the problem and was suggested several times on [the original issue](https://github.com/hotwired/turbo/issues/886).
=> fix: temporary fix for turbo bug with lazy loading

app/components/avo/paginator_component.rb, app/components/avo/views/resource_index_component.html.erb
Fixes empty `turbo_frame` on the pagination component
=> fix: paginator component turbo_frame

lib/generators/avo/templates/tailwindcss/tailwind.config.js
I ran the generator to install tailwind for avo. I had an ejected component that wasn't in the config for tailwind to watch. I added the folder where it ejected the component to.
I haven't submitted an issue.
1. Eject a component. I had Avo::Views::ResourceShowComponent ejected and modified.
1. Add a div with tailwind classes in it. I did a button.
2. You'll see that some of the classes don't apply.
3. Apply this fix.
4. You'll see it start working.
=> Have Avo tailwind watcher cover ejected components.

lib/generators/avo/tailwindcss/install_generator.rb
When running the tailwind generator, it appends the avo command to the end of the file. If the file doesn't end in a newline, it adds it to the previous line.
Fixes # 3187
1. Step 1
1. Step 2
=> Add a newline before appending the avo tailwind command to Procfile.dev

lib/avo/concerns/model_class_constantized.rb, lib/avo/resources/base.rb
Fixes #3191
Constantize the `model_class` on reader instead of on writer.
=> fix: constantize `model_class` on reader

app/components/avo/index/resource_table_component.rb, spec/dummy/app/models/post.rb
Fixes #3196 
Disable "Select All" when serializing the query raises any error.
In development  a warning message is displayed. The warning includes a link to documentation that explains how the "Select All" feature works and provides some guidance on known issues.
- https://github.com/avo-hq/docs.avohq.io/pull/286
=> dx: disable select all feature when serialization raises error

lib/avo/resources/base.rb, spec/features/avo/resource_title_spec.rb
Fixes #3201 
Enforce `String` type on `record_title` method
=> fix: resource fails to show when title is numeric

app/components/avo/sidebar/link_component.html.erb, app/components/avo/sidebar/link_component.rb
Fixes #3199 
Now all extra arguments are passed to the menu link.
https://github.com/avo-hq/avo-menu/pull/33
=> fix: unknown keyword rel on menu link

app/components/avo/index/resource_controls_component.rb, app/components/avo/index/table_row_component.rb, lib/avo/concerns/checks_show_authorization.rb
Fixes #3200
Apply `show?` policy on `click_row_to_view_record` feature. If `show?` returns `false` then the row should not be clickable.
=> feature: apply `show` policy on `click_row_to_view_record`

.github/workflows/test.yml, app/components/avo/fields/belongs_to_field/autocomplete_component.rb, app/components/avo/fields/has_one_field/show_component.rb, app/components/avo/index/resource_controls_component.rb, app/components/avo/views/resource_index_component.rb, app/controllers/avo/application_controller.rb, app/controllers/avo/associations_controller.rb, app/controllers/avo/base_controller.rb, gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock, gemfiles/rails_6.0_ruby_3.2.2.gemfile.lock, gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock, gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock, gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock, gemfiles/rails_7.0_ruby_3.2.2.gemfile.lock, spec/dummy/app/models/user.rb, spec/features/avo/breadcrumbs_spec.rb, spec/system/avo/dashboards_spec.rb, spec/system/avo/tabs_spec.rb
- better compatible with newer Rails, since it casts to needed type on its own
successor to https://github.com/avo-hq/avo/pull/2927
I'm trying to setup Rails 7.2 for Avo 2.x CI at https://github.com/avo-hq/avo/pull/3204 as well, but it will probably need more time.
=> [2.x] Remove last usage of _reflections in favor of reflect_on_association.

app/components/avo/profile_item_component.rb
Allow `Symbol` on  `Avo::ProfileItemComponent` `method` prop.
```ruby
config.profile_menu = -> do
link_to "Sign out", path: main_app.destroy_user_session_path, icon: "user-circle", method: :post
end
```
=> fix: allow `Symbol` on `Avo::ProfileItemComponent` `method`

app/components/avo/base_component.rb, app/controllers/avo/application_controller.rb, app/controllers/avo/associations_controller.rb, lib/avo/concerns/find_association_field.rb, spec/dummy/app/avo/resources/store.rb, spec/system/avo/has_many_spec.rb
Fixes #3166
Fixes #3158
In the previous attempt [#3230](https://github.com/avo-hq/avo/pull/3230), I aimed to target the exact field type when fetching association fields. However, that approach was abandoned as it led down a rabbit hole and was difficult to stabilize. In some cases, identifying the exact field type would require passing it through params, which is not ideal for maintainability and simplicity.
This PR simplifies things by following the 80/20 rule. Instead of trying to pinpoint the exact field type, Avo now just checks if the field is one of the supported associations when fetching fields. This fixes the reported issue and similar ones without overcomplicating things.
=> fix: verify type when fetching associations fields

app/controllers/avo/associations_controller.rb, spec/dummy/app/avo/resources/user.rb, spec/features/avo/has_many_field_spec.rb
Add `resource` and `parent_resource` on associations `scope` block
Docs: https://docs.avohq.io/3.0/associations/has_many.html#scope
=> refactor: add `resource` and `parent_resource` on associations `scope` block

app/javascript/js/controllers/toggle_controller.js
Fixes #3282 
Verify `exemptionContainerTarget` presence before executing exemption on `clickOutside`.
https://github.com/user-attachments/assets/d51df323-2971-4f6e-8188-38bf5750b644
=> fix: verify `exemptionContainerTarget` presence

app/javascript/avo.base.js
Fixes #3265 
- On the first load, get the `title` attribute value from the element and remove the attribute to prevent the default HTML title behavior.
- The retrieved title is stored in a new `tippy_title` attribute to ensure it can be used for future reference.
- When navigating back via the browser's back button, the `tippy_title` attribute is used to repopulate the tooltip content instead of relying on the now-removed title attribute.
https://github.com/user-attachments/assets/0703c503-a00b-438e-97a6-030a8cdaee47
=> fix: improve tippy tooltip to support browser back button

app/javascript/avo.base.js
Fixes a bug introduced here https://github.com/avo-hq/avo/pull/3284
- Removing the `data-tippy` attribute to prevent multiple tooltip renders on the same element.
- Tagging the element with a `has-data-tippy` attribute to track the tooltip status.
- Reverting the `data-tippy` attribute on `turbo:before-cache` event to ensure tooltips are properly reinitialized on page navigation (e.g., when the back button is pressed).
=> fix: multiple tippy renders

app/javascript/avo.base.js
Refactor and simplify the code introduced by:
- https://github.com/avo-hq/avo/pull/3284
- https://github.com/avo-hq/avo/pull/3285
=> refactor: tippy data

app/components/avo/index/resource_controls_component.html.erb, app/components/avo/index/resource_controls_component.rb
Fixes #3214
https://github.com/user-attachments/assets/3f8d344a-af83-466d-920a-c2d549b705a5
=> fix: alignment of user actions on posts

app/controllers/avo/application_controller.rb, app/controllers/avo/debug_controller.rb, app/controllers/avo/private_controller.rb, app/views/avo/debug/status.html.erb, app/views/avo/debug/status.text.erb, app/views/layouts/avo/application.html.erb, lib/avo/plugin.rb, lib/avo/plugin_manager.rb, lib/generators/avo/templates/initializer/avo.tt
- Fixes an issue with plugin reporting and hides the ruby/rails/avo aversions from the public.
- Adds the `/avo/avo_private/status.txt` path to quickly find out what you need
- hides all the private stuff behind the lightweight `user_is_admin?` or `user_is_developer?` flags
=> refactor: plugins reporting and versions hiding

app/components/avo/index/table_row_component.rb
Add reader for `resource` on `Avo::Index::TableRowComponent`
```ruby
undefined local variable or method `resource` for an instance of Avo::Index::TableRowComponent
```
=> fix: undefined local variable or method `resource` for an instance of Avo::Index::TableRowComponent

app/components/avo/index/resource_table_component.rb, app/components/avo/views/resource_index_component.rb
Fixes #3294
Remove `ActiveRecord::Relation` type from `query` since using some gems (like [Scenic gem](https://github.com/scenic-views/scenic)) might return other types.
=> fix: remove type from query

app/javascript/js/controllers/toggle_controller.js
Fixes #3296 
Add tags options to the exemption containers and refactor the JS code to accept more than one exemption container.
[avo-dynamic_filters #71](https://github.com/avo-hq/avo-dynamic_filters/pull/71)
=> fix: tags filters closing on tag selection

app/controllers/avo/search_controller.rb, lib/avo/resources/resource_manager.rb
Fixes https://github.com/avo-hq/avo/issues/3301
Related PR: https://github.com/avo-hq/avo-pro/pull/92
You can now monkeypatch the `process_results` method with something like this:
```ruby
Rails.configuration.to_prepare do
Avo::SearchController.prepend SearchControllerExtensions
end
module SearchControllerExtensions
def process_results(resources, request: nil)
regex = /.*\/resources\/(.*).*/
if request&.referrer.present?
resource_path = request.referrer.match(regex).captures.first
if resource_path.present?
resource_class = Avo.resource_manager.get_resource_by_plural_name resource_path
end
end
results = super
results
end
end
```
=> feature: process search results

app/views/avo/partials/_table_header.html.erb, lib/avo/configuration.rb, lib/generators/avo/templates/initializer/avo.tt, spec/features/avo/default_sort_column_and_direction_spec.rb
Fixes https://github.com/avo-hq/avo/issues/3260
Me working on this feature:
https://www.loom.com/share/da337fcece7f42b9ab61d96a75e65df0
1. Enable the configuration with `config.first_sorting_option = :asc` in the intializer
1. Got to the index view
2. sort a column
3. observe that the sequence is `asc, desc, then reset`
=> feature: customizable first sorting option

lib/generators/avo/tool_generator.rb
=> Add a comment to notice about security

lib/avo/configuration.rb
Callable `disabled_features`
```ruby
Avo.configure do |config|
config.disabled_features = -> { current_user.is_admin? ? [] : [:global_search] }
end
```
Tests: https://github.com/avo-hq/avo-pro/pull/93
Docs: https://github.com/avo-hq/docs.avohq.io/commit/1432973377a6769669e55fef6b673190a185a293
=> refactor: callable `disabled_features`

Gemfile.lock, avo.gemspec, gemfiles/rails_6.1_ruby_3.1.4.gemfile, gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock, gemfiles/rails_6.1_ruby_3.3.0.gemfile, gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock, gemfiles/rails_7.1_ruby_3.1.4.gemfile, gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock, gemfiles/rails_7.1_ruby_3.3.0.gemfile, gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock, gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile, gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile.lock, gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile, gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile.lock, gemfiles/rails_8.0_ruby_3.1.4.gemfile, gemfiles/rails_8.0_ruby_3.1.4.gemfile.lock, gemfiles/rails_8.0_ruby_3.3.0.gemfile, gemfiles/rails_8.0_ruby_3.3.0.gemfile.lock
Update `prop_initializer` dependency to `>= 0.2.0`
=> chore: update `prop_initializer` dependency

app/components/avo/index/table_row_component.html.erb, app/views/avo/partials/_table_header.html.erb, lib/avo/concerns/controls_placement.rb, lib/avo/configuration/resource_configuration.rb, lib/avo/resources/base.rb, spec/features/avo/resource_controls_placement_spec.rb
You can now have the placement of the actions set on the resource too. So you can have a resource with controls on the left and another one with controls on the right.
1. On a resource level, add `self.controls_placement = :left`
2. View the controls being rendered on the `left` instead of the default `right` value
=> ✨ Controls placement on resource level

lib/avo/test_helpers.rb
A few of the test helpers use the `type` helper method but in selenium it raises this error:
NoMethodError:
undefined method `keyboard' for #<Selenium::WebDriver::Chrome::Driver:0x000000013ebbb950>
I've changed this to do the same thing (type in the focused element) but in a way that should work in every capybara driver.
1. Tests using `add_tag` and other helpers that use the keyboard should still pass.
=> Made the send_keys helper work in selenium as well as cuprite

app/controllers/avo/associations_controller.rb, lib/avo/concerns/checks_assoc_authorization.rb, lib/avo/fields/has_base_field.rb, spec/dummy/config/initializers/avo.rb
Fixes #3327
Apply `implicit_authorization` only when using a custom authorization service or the `Avo::Pro::Authorization::AuthorizationService`.
If the default `Avo::Services::AuthorizationService` is being used, bypass the `implicit_authorization` logic entirely.
In summary, `implicit_authorization` should only take effect if a custom authorization service is implemented or when using Avo Pro.
=> fix: implicit_authorization on default authorization service

app/components/avo/fields/trix_field/edit_component.rb, app/javascript/js/controllers/fields/trix_field_controller.js, lib/generators/avo/templates/locales/avo.ar.yml, lib/generators/avo/templates/locales/avo.en.yml, lib/generators/avo/templates/locales/avo.es.yml, lib/generators/avo/templates/locales/avo.fr.yml, lib/generators/avo/templates/locales/avo.ja.yml, lib/generators/avo/templates/locales/avo.nb.yml, lib/generators/avo/templates/locales/avo.nn.yml, lib/generators/avo/templates/locales/avo.pt-BR.yml, lib/generators/avo/templates/locales/avo.pt.yml, lib/generators/avo/templates/locales/avo.ro.yml, lib/generators/avo/templates/locales/avo.tr.yml, spec/system/avo/trix_field_spec.rb
Translates trix_field_controller js warnings
Fixes #3329
1. Change the locale to one of locales supported
2. Try to upload a image in trix when creating a new resource
https://github.com/avo-hq/docs.avohq.io/pull/301
=> feature: translate trix field controller js warnings

app/components/avo/sidebar_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/2009 .
Username and logout links are hidden on mobile device when browser's address bar is opened. The workaround is to use `dvh` instead of `vh` to calculate sidebar height properly. 
`dvh` is [supported](https://caniuse.com/?search=dvh) by all main browsers in 2024.
1. How it works with `vh`:
https://github.com/user-attachments/assets/9fa43cf2-df93-42da-be24-29efbaa46f74
2. How it works with `dvh`:
https://github.com/user-attachments/assets/32070b28-fa21-4de5-84e0-6424457f18e7
=> fix: consider browser dynamic toolbar state for sidebar height

app/components/avo/actions_component.rb, app/components/avo/resource_component.rb, app/javascript/js/controllers/item_selector_controller.js, lib/avo/base_action.rb
Fixes #2735
Enable **non** standalone actions defined on `self.index_controls` only when a record is selected.
https://github.com/avo-hq/avo-advanced/pull/50
=> fix: disable non standalone actions on custom controls

spec/dummy/app/avo/resources/review.rb, spec/dummy/app/avo/resources/user.rb, spec/dummy/config/initializers/friendly_id.rb, spec/features/avo/app_spec.rb, spec/features/avo/create_has_one_spec.rb, spec/features/avo/field_setter_missing_spec.rb, spec/features/avo/link_to_child_resource_spec.rb, spec/features/avo/number_spec.rb, spec/features/avo/search_has_many_scope_spec.rb, spec/features/avo/textarea_spec.rb, spec/features/avo/use_resource_spec.rb, spec/system/avo/attach_and_attach_another_spec.rb, spec/system/avo/resource_sidebar_spec.rb, spec/system/avo/select_all_spec.rb
=> Fix typographical errors from spec directory

app/components/avo/panel_component.html.erb, app/views/avo/partials/_panel_breadcrumbs.html.erb
We've seen users who need custom breadcrumbs and we'd like to help them override our implementation without extracting the whole panel component.
Also fixes a small visual bug with icon spacing.
=> refactor: extract breadcrumbs partial

lib/avo/filters/base_filter.rb, spec/dummy/app/avo/filters/user_names_filter.rb, spec/dummy/config/locales/avo.en.yml
Fixes #3244 
Docs PR: https://github.com/avo-hq/docs.avohq.io/pull/304
=> feature: callable filter `name` and `button_label`

app/components/avo/modal_component.html.erb, app/components/avo/modal_component.rb, app/javascript/js/controllers/modal_controller.js, app/views/avo/actions/show.html.erb, lib/avo/base_action.rb, spec/dummy/app/avo/actions/export_csv.rb, spec/system/avo/actions_spec.rb
Fixes #3326 
Related PR: https://github.com/avo-hq/docs.avohq.io/pull/303
https://www.loom.com/share/970418f8279244f7b4feb97e2617bff5?sid=f44ba85f-55c0-4809-a464-cc1328f628a2
By default, action modals use a dynamic backdrop. Added a `self.dynamic_backdrop = false` action option in case you want to prevent the user from closing the modal when clicking on the backdrop.
```ruby
class Avo::Actions::DummyAction < Avo::BaseAction
self.name = "Dummy action"
self.dynamic_backdrop = false
def handle(query:, fields:, current_user:, resource:, **args)
succeed 'Yup'
end
end
```
I saw that other action options like `no_confirmation` and `standalone`  doesn't have tests.
1) Should I add tests for a simple feature like this one?
PS: It's not laziness, I'm assuming it's not worth it in this context. …
=> feature: action dynamic backdrop option

app/components/avo/button_component.rb, app/javascript/js/controllers/loading_button_controller.js
Fixes https://github.com/avo-hq/avo/issues/3389
=> fix: SVG breaks buton in Safari

lib/avo/test_helpers.rb, spec/dummy/app/models/post.rb, spec/system/avo/test_helpers_spec.rb, yarn.lock
Fixes the tags test helper so it returns the text of each visible tag.
The tags helper was getting the `label` attribute of `.tagify__tag` elements before but so far as I can see `.tagify__tag` elements do not have a label. Because of that the tags helper was always returning an array of `nil` values (one for each tag). Instead I've changed them to get the text of the tag.
I'm not sure why this wasn't causing the avo test suite to fail before, as there is a test for this helper and the other tags helpers (which return the result of the tags helper) but this seems to work for both the avo test suite and my own code (and matches what I can see when I try avo myself in the browser). It also matches what the `wait_for_tag_to_appear` helper does (ie. looks for tag text, not label).
The tags …
=> Correct how the tags helper gets the text for tags

app/javascript/js/controllers/search_controller.js, app/views/avo/partials/_navbar.html.erb, app/views/layouts/avo/application.html.erb
Fixes #3324
Related PR https://github.com/avo-hq/avo-pro/pull/95
Now, `params[:resource_class]` and `params[:record_id]` are present on the search query, bringing information about the resource and the record.
https://www.loom.com/share/84b66f8b21cc4908beba09abe1f79d19?sid=d7975477-b20a-40d2-be24-372553de5db4
=> enhancement: extra params on global search

app/controllers/avo/associations_controller.rb
Fixes #3406
In STI models, the `inverse_of` option is essential on associations for correctly configuring `via_*` parameters on links.
When Avo encounters an STI model without `inverse_of` set in the reflection, it will raise an informative error **in development environment only**.
```ruby
class Users::Student < User
has_many :marks, foreign_key: :student_id
end
```
=> dx: raise informative error when `inverse_of` is missing on STI

app/components/avo/actions_component.rb, lib/avo/divider.rb, lib/avo/resources/base.rb
Fixes #3297
https://github.com/avo-hq/avo-advanced/pull/51
- https://github.com/avo-hq/docs.avohq.io/pull/309
```ruby
self.index_controls = -> do
action Avo::Actions::ReleaseFish
list label: "Custom Index List", icon: "heroicons/outline/cube-transparent", style: :primary, color: :slate, title: "A custom list" do
link_to "Google", "https://google.com", icon: "heroicons/outline/academic-cap"
divider label: "↓ Action ↓"
action Avo::Actions::Sub::DummyAction, icon: "heroicons/outline/globe"
divider
link_to "Fish.com", "https://fish.com", icon: "heroicons/outline/fire", target: :_blank
link_to "Avo", "https://avohq.io/", target: :_blank
end
end
```
=> enhancement: add divider to custom list (custom controls)

lib/generators/avo/eject_generator.rb
Allow to eject components from plugins, for example, to eject kanban item: `rails g avo:eject --component Avo::Kanban::Items::ItemComponent`
=> enhancement: eject components from plugins

lib/avo/resources/base.rb, spec/dummy/config/locales/avo.pt.yml, spec/features/avo/generators/locales_generator_spec.rb, spec/features/avo/localization_spec.rb
Fixes #3449
Remove memoization from resource name to force re-evaluation on locale change.
=> fix: i18n on resource class

app/javascript/js/custom-confirm.js
Turbo 8 deprecated `Turbo.setConfirmMethod()` and instead moved it to `Turbo.config.forms.confirm` instead (see https://github.com/hotwired/turbo/pull/1216). Because of that, avo is throwing deprecation messages in the javascript console:
Please replace `Turbo.setConfirmMethod(confirmMethod)` with `Turbo.config.forms.confirm = confirmMethod`. The top-level function is deprecated and will be removed in a future version of Turbo.
I've updated the code to use the new config object instead, which should resolve the deprecation warning.
1. Confirm that turbo confirmation popups still work.
=> Fix Turbo.config.forms.confirm deprecation message

app/controllers/avo/associations_controller.rb, lib/avo/concerns/checks_assoc_authorization.rb, lib/avo/configuration.rb, lib/avo/fields/has_base_field.rb
Fixes #3447 
Now `explicit_authorization` makes no impact when `authorization_client` is `nil` 
Tests here: https://github.com/avo-hq/avo-pro/pull/97
=> fix: explicit authorization

app/controllers/avo/associations_controller.rb, app/views/avo/associations/new.html.erb
I _think_ this is all that's necessary to fix the issue linked below. In the AssociationsController, we expect a `:turbo_frame` param to be passed to the route if we want to rerender the turbo frame instead of closing it. The only bit I'm unclear on is whether we need to have additional special handling for the `attach_another` button. I figured [this](https://github.com/avo-hq/avo/blob/f6d132891fdf87a754af0880a3a97b9b3e0d4f51/app/controllers/avo/associations_controller.rb#L256) was enough.
Fixes #3456 
1. Step 1
1. Step 2
=> fix: broken attach and attach another button for searchable associations

app/helpers/avo/application_helper.rb, lib/avo.rb
On the same lines with https://github.com/avo-hq/avo/pull/3177 but this time, it works. Thanks Paul for the help.
We are caching, in memory, all the svg paths.
=> perf: svg loading improvements

app/controllers/avo/actions_controller.rb, app/controllers/avo/associations_controller.rb, app/controllers/avo/base_controller.rb, app/helpers/avo/turbo_stream_actions_helper.rb, spec/helpers/avo/turbo_stream_actions_helper_spec.rb
Fixes #3462
1. Step 1
1. Step 2
=> fix: Rename Turbo Stream helpers to avoid clashes in user apps (#3462)

lib/avo/svg_finder.rb
From the SVG caching saga, this PR fixes an early return that was bypassing the caching mechanism.
Related to https://github.com/avo-hq/avo/pull/3470 & https://github.com/avo-hq/avo/pull/3471
=> fix: svg cache

app/components/avo/sidebar_profile_component.html.erb
Fixes #3482 
Fixes a bug where the profile menu wasn't positioned correctly.
=> fix: profile menu position

app/components/avo/views/resource_index_component.html.erb
Fixes #3391
Allow to access `parent_record` on the dynamic filters `suggestions` block.
=> enhancement: parent_record on filters suggestions

app/controllers/avo/base_controller.rb, spec/system/avo/tabs_spec.rb
Fixes #3489 
Store `per_page` on associations making the navigation between associated records a bit smoother.
=> fix: maintain `per_page` param in associations

app/views/avo/debug/status.html.erb, lib/avo/configuration.rb, lib/generators/avo/templates/initializer/avo.tt, spec/dummy/config/initializers/avo.rb
Add `exclude_from_status` configuration where can be defined what status item to exclude on the status page.
Usage example: 
```ruby
Avo.configure do |config|
config.exclude_from_status = ["license_key"]
config.exclude_from_status = -> do 
["license_key"]
end
end
```
=> enhancement: `exclude_from_status` configuration

app/controllers/avo/associations_controller.rb, app/controllers/avo/base_controller.rb
Use `@parent_resource` to generate the pagination key on session instead of using the `@record`
When `@record` is used there will be one entry for each record - association pair:
- `gid://avo3-dummy/Project/36.has_many.avo-resources-user`
- `gid://avo3-dummy/Project/37.has_many.avo-resources-user`
- etc...
But we want one single entry between each parent_resource - association pair:
- `avo-resources-project.has_many.avo-resources-user`
=> fix: session key for pagination

app/javascript/js/controllers/search_controller.js
Fixes the JS search controller.
`.aa-DetachedOverlay` is already getting removed when a value is selected from the search list, there is no need to remove it with code.
Fixes:
```ruby
search_controller.js:223 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'remove')
at n.handleOnSelect (search_controller.js:223:51)
```
=> fix: search_controller null error

app/components/avo/field_wrapper_component.rb, app/components/avo/index/field_wrapper_component.rb, app/components/avo/panel_component.rb
Fixes the field wrapper component classes. Previously, the way props were being handled did not account for custom classes, such as "bg-red-500."
For instance, in the following usage:
`<%= index_field_wrapper **field_wrapper_args, class: 'bg-red-500' do %>`
The custom class "bg-red-500" was not being applied correctly. This PR ensures that custom classes are properly merged and rendered.
=> fix: classes on field wrapper component

app/components/avo/filters_component.rb, lib/avo/concerns/pagination.rb
Fixes #2468
Fixes a pagination overflow error that might occur in cases where the default query has fewer pages than the query with certain filters applied. 
> Let's take a simple example. Suppose that there are only 1000 employees in the system, and Johan Wang supervises 20 people, and he is viewing 10 per page, so he has 2 pages of results. If he sets the filters to show everyone (which is not the default, but is available to him) then suddenly there are 100 pages. He can advance all the way to page 100 and everything works until he resets the filters back to his default. That's when there's an error.
_Originally posted by @brandondrew in [#2468](https://github.com/avo-hq/avo/issues/2468#issuecomment-1950822912)_
---
Fixes #3522
---
**Since we had fixed many Pagy::OverflowError and they …
=> fix: Pagy::OverflowError

app/components/avo/views/resource_edit_component.html.erb, app/javascript/js/controllers.js, app/javascript/js/controllers/form_controller.js, spec/system/avo/avo_cmd_return_to_submits_spec.rb
Fixes https://github.com/avo-hq/avo/issues/3531
1. Go to an edit page
1. Make some changes
2. when you are focused on an input field run cmd+return
3. observe how the form is submitted
=> feature: cmd+return to submit form

app/controllers/avo/associations_controller.rb, lib/avo/concerns/filters_session_handler.rb, lib/avo/configuration.rb, lib/generators/avo/templates/initializer/avo.tt, spec/dummy/config/initializers/avo.rb, spec/system/avo/filters/persist_filters_spec.rb, spec/system/avo/tabs_spec.rb
The `persistence` configuration enables retention of specific UI settings, such as pagination and static filters, across user interactions.
To set the `:driver` for persistence, configure it as follows:
```ruby
config.persistence = { driver: :session }
config.persistence = -> do
{ driver: :session }
end
```
- **Associations Pagination:** Keeps the pagination state for associated records.
- **Static Filters:** Retains static filter configurations applied by the user.
By setting `:driver` to `:session`, these configurations will persist within the user's session, maintaining their state across requests while the session remains active.
> [!WARNING]
> **`config.cache_resource_filters` is obsolete**  
> The `config.cache_resource_filters` option has been replaced by `config.persistence`.  
> …
=> enhancement: persistence setting

app/components/avo/field_wrapper_component.html.erb, spec/dummy/app/avo/resources/user.rb, spec/dummy/app/models/user.rb
=> fix: `break-words` on show content

app/views/layouts/avo/application.html.erb
In the browser javascript console I see this error on every page load:
The resource http://localhost:3000/avo-assets/avo.base.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally."
It's not causing me any issues as such - it's just noisy and can make it harder to see real issues. It seems like a simple thing to fix so I've raised a PR.
1. The avo dashboard should load with the correct styles and show no stylesheet warning in the browser console.
=> Set "as" attribute on stylesheet link tag

app/javascript/js/controllers/form_controller.js
Fixes #3553
**Problem:**
Autocomplete interactions were inadvertently triggering the `submit` action on the `form` controller. This action is intended to be triggered only by the specified Stimulus [Keyboard events](https://stimulus.hotwired.dev/reference/actions#keyboardevent-filter): 
`keydown.ctrl+enter->form#submit` and `keydown.meta+enter->form#submit`.
**Solution:**
This PR introduces a guard clause to ensure that the `event.key` property is present before proceeding with the form submission. This effectively prevents unintended triggers caused by autocomplete behavior.
=> fix: don't submit form on autocomplete

app/components/avo/field_wrapper_component.html.erb
Revert https://github.com/avo-hq/avo/pull/3542, which will reopen https://github.com/avo-hq/avo/issues/3530.
The `overflow-x-auto` property was causing some malfunctions, and `break-words` does not work on long strings like `a78020e0e5066b883c6f820603b2604277941d62d4b4cbbcfc18743712aae70053911007e6de1f2cf68df1dcee2f1cd14a3b1028e1f908a256ab0761d372a66`.
Using `break-all` is not ideal, as it will break all words indiscriminately, ignoring grammar or natural word breaks.
=> fix: field wrapper overflow

lib/generators/avo/eject_generator.rb
Ejecting components now fails with source_location undefined error, this is because it's used on the class directly while it's supposed to be used on methods
https://ruby-doc.org/3.3.6/Method.html#method-i-source_location
Will use `const_source_location` instead to find the class
1. Step 1
1. Step 2
=> fix: eject generator failing due to undefined source_location method

app/components/avo/profile_item_component.html.erb, app/components/avo/profile_item_component.rb
Add the ability to set a profile item's button to disabled, for example when adding an account switcher
=> Add disabled prop to ProfileItemComponent

app/components/avo/fields/location_field/show_component.html.erb, lib/avo/fields/location_field.rb, spec/dummy/app/avo/resources/city.rb, spec/system/avo/location_field_spec.rb
Fixes #3147
Allows to configure `mapkick_options` on location field 
```ruby
field :coordinates,
as: :location,
stored_as: [:latitude, :longitude],
mapkick_options: {
style: 'mapbox://styles/mapbox/satellite-v9',
controls: true
}
```
- https://github.com/avo-hq/docs.avohq.io/pull/334
=> Add `mapkick_options` to location field

app/components/avo/fields/radio_field/edit_component.html.erb, spec/dummy/app/avo/actions/sub/dummy_action.rb, spec/features/avo/radio_field_spec.rb
Fixes #3539
Fixes radio field labels to ensure proper association with options. Clicking a label now correctly selects the corresponding radio button, improving usability and accessibility.
=> fix: radio field on actions & improve accessibility

Gemfile, Gemfile.lock, app/components/avo/fields/location_field/show_component.html.erb, lib/avo/fields/location_field.rb, spec/dummy/app/avo/resources/city.rb, spec/system/avo/location_field_spec.rb
Adding `static` field option for location field and enabling it by default on preview.
- https://docs.avohq.io/3.0/fields/location.html#static
=> enhancement: location field on preview & static option

app/javascript/js/controllers/item_selector_controller.js, spec/system/avo/actions_spec.rb
Fixes #3591
Fixes an issue where non-standalone actions were not being enabled or disabled after selecting or deselecting records in grid view.
This issue originated from two lines of JavaScript that attempted to add and remove a class to the closest `<tr>` element without verifying its existence. However, in grid view, no `<tr>` elements are present.
=> fix: grid view item selector

app/controllers/concerns/avo/initializes_avo.rb
Adds a notification in your Rails logs if the license is invalid.
=> chore: add invalid license log notification.

app/components/avo/fields/common/heading_component.rb
This PR ensures that wrapper data is correctly assigned to `heading` fields.
```ruby
field :title, as: :heading, html: -> {
edit do
wrapper do
classes do
"hidden"
end
data do
{
"some-controller-target": "titleHeading"
}
end
end
end
}
```
=> fix: pass wrapper data on heading field

app/components/avo/resource_component.rb, lib/avo/concerns/has_resource_stimulus_controllers.rb
Fixes #3607
Adding the `saveButton` target to all the stimulus controllers registered on a resource.
=> enhancement: add `saveButton` stimulus target to save button

app/components/avo/asset_manager/javascript_component.html.erb
Fixes `javascript_include_tag` for `late-registration` to use `/avo-assets/` prefix when Avo is packed.
=> fix: `late-registration` javascript tag

lib/tasks/avo_tasks.rake
Fixes #3623 by including the `@tailwindcss/container-queries` dependency on `avo:yarn_install` task.
This dependency is necessary when using [tailwind integration](https://docs.avohq.io/3.0/tailwindcss-integration.html).
=> fix: tailwind integration

lib/avo/base_action.rb
Fixes #3626 
Don't check action's authorization on render if `visible` return false
=> fix: don't check action's authorization on render if `visible` return false

lib/tasks/avo_tasks.rake
Fixes an issue where the Tailwind version used in the Tailwind integration was not specified, resulting in a "random" version being used instead of the one used to render Avo styles. This fix ensures that the preset uses the same Tailwind version as Avo during the build process to prevent style overrides and conflicts.
=> fix: tailwind integration dependencies

app/views/layouts/avo/application.html.erb
When you load a page in avo the html `<link>` tag to load `avo.base.css` it ha a `defer` attribute on it. `defer` isn't a valid attribute for a `<link>` tag - it is for `<script>` tags and having it here is invalid html. I think this is also causing loading issues in google chrome for me when I redirect from avo to my main app.
I've removed defer from the `<link>` tag. This should make the html valid and shouldn't have any bad effects (as it shouldn't be used on a `<link>` tag anyway).
1. Check that the css for avo still loads correctly.
=> Removed defer attribute from the avo.base.css stylesheet tag

app/components/avo/actions_component.rb, app/components/avo/resource_component.rb, app/javascript/js/controllers/item_selector_controller.js
Fixes #3575 
Actions should only be enabled or disabled when a selected item belongs to the same context/resource. This way, in the "has many" context, only the relevant "has many" actions will be modified.
=> fix: has many record selection disables parent's actions

app/components/avo/media_library/list_component.html.erb
Small typo fix that leads to an AttributeError (`unknown keyword: :xanchor_string`) in the Media Library
=> Fix pagy nav typo

app/controllers/avo/search_controller.rb
Fixes the global search warning when a resource has search disabled. Previously, it appeared as an error.
=> fix: global search warning

Gemfile.lock, app/helpers/avo/application_helper.rb, avo.gemspec
Fixes #3650
This PR drops the `universalid` gem as it relies on `config` gem, which has been causing multiple issues.
=> chore: drop `universalid` dependency

app/controllers/avo/base_controller.rb
Fixes #3523
**In development**, log  errors rescued in `perform_action_and_record_errors`
=> enhancement: log errors rescued in `perform_action_and_record_errors`

app/components/avo/fields/radio_field/edit_component.html.erb, spec/dummy/app/avo/actions/sub/dummy_action.rb, spec/features/avo/radio_field_spec.rb
Fixes #3659
Fixes #3649
Fix radio field accessibility by correctly associating the label with its corresponding checkbox. Also ensures that the radio field selects the default value if given on actions.
=> fix: radio field accessibility

app/components/avo/paginator_component.rb, app/components/avo/views/resource_index_component.html.erb, app/helpers/avo/url_helpers.rb
Fixes #3667
Fixing `change_items_per_page_url` by using the parent resource's route key instead of the parent model's route key.
This is useful when the parent resource uses `self.model_class` and its route key differs from that of the parent model.
=> fix: `change_items_per_page_url` on paginator component

lib/avo/resources/array_resource.rb
Fixes #3682 
Modify array resource constant registration to use Avo namespace
This update ensures that defining a resource like:
```ruby
class Avo::Resources::Movie < Avo::Resources::ArrayResource
```
will generate a corresponding `Avo::Movie` backbone model instead of `Movie`.
By namespacing the generated model within `Avo`, we prevent potential conflicts with an existing `Movie` class in the parent application.
=> fix: modify array resource constant registration to use Avo namespace

lib/avo/concerns/has_field_discovery.rb
Fixes:
```
.../avo/lib/avo/concerns/has_field_discovery.rb:16: warning: already initialized constant Avo::Concerns::HasFieldDiscovery::COLUMN_NAMES_TO_IGNORE
.../avo/lib/avo/concerns/has_field_discovery.rb:16: warning: previous definition of COLUMN_NAMES_TO_IGNORE was here
```
=> fix: warning: already initialized constant Avo::Concerns::HasFieldDiscovery::COLUMN_NAMES_TO_IGNORE

lib/generators/avo/templates/resource/resource.tt
Auto generated resources have whitespaces. Rubocop doesn't allow them. It raises errors.
1. Use standart Rails rubocop rules.
2. Create a new model
3. run `bin/rubocop -f github`
=> Remove unnecessary blank lines in resource template

Gemfile.lock, app/components/avo/views/resource_index_component.rb, lib/avo/concerns/has_description.rb, lib/avo/fields/base_field.rb, spec/dummy/app/avo/resources/user.rb, spec/features/avo/has_many_field_spec.rb
Fixes https://github.com/avo-hq/avo/issues/3596
I'm not sure about this solution as there is a lot of metaprogramming that I don't fully understand. 
The description already supported lambdas so I just extended it so it now has access to `query`. I tried to do the same for `name` but it cannot have access to the query as it is also used to display the text of the tab (see screenshot). When rendering these tabs we don't have access to the query.
I appreciate the feedback, and if this is not the correct way to solve this I don't mind closing this PR :) 
1. Start the dummy app
2. Open any user
3. Notice the description of Posts relationship has a counter
4. Notice that we use lambda in code to display the name of the relationship
=> enhancement: allow dynamic content in `description` and `name`

lib/avo/concerns/has_items.rb, lib/avo/resources/items/holder.rb, lib/avo/resources/items/item_group.rb, spec/dummy/app/avo/resources/person.rb
Alias `row` to `cluster`
- https://github.com/avo-hq/docs.avohq.io/pull/349
=> refactor: alias `row` to `cluster`

app/javascript/js/controllers/table_row_controller.js
Fixes an issue when a user was trying to select a piece of text on a table row (with click to visit record option on) and that would trigger the visit to that record instead of ignoring it.
1. go to a table with `click_row_to_view_record` option on
1. select some text on a row
2. observe that thebrowser does not visit that record.
=> fix: text selection on table row triggers visit

app/components/avo/fields/has_one_field/show_component.html.erb
Fixes #2614 
`read_only` and `disabled` options were interfering with the rendering of attach/create buttons on `has_one` fields, while not affecting other association fields such as `has_many`.
We decided to remove these options from the attach/create functionality to maintain consistency with other fields, and now attach/create is controlled solely through authorization ([attach_{association}?](https://docs.avohq.io/3.0/authorization.html#attach_association) / [create_{association}?](https://docs.avohq.io/3.0/authorization.html#create_association)).
Heads up: `read_only` and `disabled` don't affect `has_one` fields anymore.
Please search for all `has_one` fields still using the `read_only` or `disabled` options and update them with the correct authorization methods: …
=> 🚨 fix: coherence within associations fields authorization

app/controllers/avo/base_application_controller.rb, lib/avo.rb
This update replaces the `ActionController::RoutingError` with a more descriptive and debuggable custom error, `Avo::ResourceNotFoundError`, when a requested resource is not found.  
The default `ActionController::RoutingError` can obscure the root cause of missing resources, making debugging more challenging. By introducing `Avo::ResourceNotFoundError`, we ensure clearer error messaging and a more maintainable approach to handling resource lookup failures.
=> refactor: start using `Avo::ResourceNotFoundError` instead `ActionController::RoutingError`

lib/avo/fields/badge_field.rb
Fixes https://github.com/avo-hq/avo-dynamic_filters/issues/82
Dynamic filters will now pick the correct options from badge fields. 
```ruby
field :stage, as: :badge, options: {info: ["Discovery", "Idea"], success: "Done", warning: "On hold", danger: "Cancelled"}, filterable: true
```
Notice that `neutral` is an option since it is one of the [default options](https://github.com/avo-hq/avo/blob/main/lib/avo/fields/badge_field.rb#L11).
=> fix: add options_for_filter method to `BadgeField`

app/controllers/avo/actions_controller.rb, app/javascript/js/controllers/action_controller.js, app/javascript/js/controllers/item_select_all_controller.js, app/views/avo/actions/show.html.erb, lib/avo/base_action.rb, spec/dummy/app/avo/actions/export_csv.rb
This PR introduces access to the `@index_query` variable within the `handle` method. This variable represents the index query of the resource, making it easier to work with the full dataset under various conditions:
- When "select all" is enabled, `@index_query == @query`.  
- When "select all" is **not** enabled, `@query` reflects only the selected records, whereas `@index_query` always returns the full index query with all filters and scopes applied.
This is particularly useful for standalone actions that need to operate on the entire dataset as defined by the current index query. For example, if a user applies filters and scopes, then selects **"Export All"**, the action can directly access the fully filtered query via `@index_query` without relying on manual selection handling.
1. …
=> enhancement: add `@index_query` access in actions

CONTRIBUTING.MD, lib/generators/avo/templates/locales/avo.ar.yml, lib/generators/avo/templates/locales/avo.de.yml, lib/generators/avo/templates/locales/avo.en.yml, lib/generators/avo/templates/locales/avo.es.yml, lib/generators/avo/templates/locales/avo.fr.yml, lib/generators/avo/templates/locales/avo.it.yml, lib/generators/avo/templates/locales/avo.ja.yml, lib/generators/avo/templates/locales/avo.nb.yml, lib/generators/avo/templates/locales/avo.nl.yml, lib/generators/avo/templates/locales/avo.nn.yml, lib/generators/avo/templates/locales/avo.pl.yml, lib/generators/avo/templates/locales/avo.pt-BR.yml, lib/generators/avo/templates/locales/avo.pt.yml, lib/generators/avo/templates/locales/avo.ro.yml, lib/generators/avo/templates/locales/avo.ru.yml, lib/generators/avo/templates/locales/avo.tr.yml, lib/generators/avo/templates/locales/avo.uk.yml, lib/generators/avo/templates/locales/avo.zh.yml
Fixes the missing locale keys for `created_at_timestamp` and `updated_at_timestamp`
=> fix: missing locale keys for `created_at_timestamp` and `updated_at_timestamp`

app/components/avo/fields/common/badge_viewer_component.rb
Fixes #3562
This PR ensures that all badges maintain a uniform width, restoring the correct behavior that was inadvertently disrupted in a previous commit. 
With this fix, badges will once again align consistently, improving visual coherence and usability.
=> fix: badge alignment

app/controllers/avo/base_controller.rb
Uses an instance variable (`@related_record`) for `related_record` during `create`.  
This ensures it remains accessible within an `after_action` callback.
=> refactor: use ivar for related_record

app/helpers/avo/turbo_stream_actions_helper.rb, lib/avo.rb
This PR relocates the execution of:
```ruby
Turbo::Streams::TagBuilder.prepend(Avo::TurboStreamActionsHelper)
```
from the file-level to the `boot` method.
This adjustment ensures consistent execution across all applications, including private repositories like `avo-advanced`, where it was previously unreliable on development.
=> refactor: turbo stream helpers

app/components/avo/clipboard_component.html.erb, app/components/avo/field_wrapper_component.html.erb, app/components/avo/index/field_wrapper_component.html.erb
Fixes #3562
Removes an unnecessary `<div>` from the field wrapper, enabling content alignment with `text-right`. To maintain the functionality of the `copyable` feature, the `Avo::ClipboardComponent` has been converted into an `inline-block`.
=> fix: index field wrapper extra div

config/routes.rb
This route is sort of duplicated with the root route in the `avo-dashboards` gem which defines a similarly unused route by default. Having two identically named routes may result in unpredictable behaviour outside of Avo when named routes are being used for things like client-side routing.
Renames the path helpers for the redirect routes `/dashboards` and `/resources`.
This issue was discovered via an edge case scenario where using the js-routes gem (https://github.com/railsware/js-routes) produces invalid JavaScript where the `avoDashboardsPath` route was being generated twice -- once by the route in `config/routes.rb` and once in the `avo-dashboards` gem. This leads to two identically named routes being set up in Rails, which causes two identically named routes to be produced by …
=> refactor: rename `/dashboards` and `/resources` redirect path helpers

lib/generators/avo/eject_generator.rb
Fixes a tiny typo in the eject generator.
(P.S. Adrian, great talk at SF Ruby last night!)
N/A, I think 😄 
None needed, I think.
=> Fix a tiny typo in the eject generator

app/controllers/avo/associations_controller.rb, spec/dummy/app/avo/resources/movie.rb
Fixes #3741 
Ignore `set_reflection` if the model class does not respond to `reflect_on_association` and the field is of type Array.
This allows rendering array fields from an array resource.
=> fix: array field on array resource

app/avo/base_resource.rb, lib/avo/concerns/abstract_resource.rb, lib/avo/resources/array_resource.rb, lib/avo/resources/base.rb, lib/avo/resources/resource_manager.rb
This PR introduces a concern that allows certain resources to be designated as abstract.
Such resources will be excluded during the resource-fetching process. This is particularly useful for omitting routes and menu entries for abstract resources, such as `Avo::Resources::ArrayResource`
This is beneficial because plugins can introduce new abstract resources without requiring modifications to Avo’s core, simply marking the plugin's resource as abstract is enough.
=> refactor: abstract resources

lib/avo/engine.rb
`mount engine[:klass], **engine[:options]` is mutating the `engine[:options]` making the app crash on reload.
This PR duplicates the options when calling mount to avoid the mutation.
=> fix: avoid engine options mutation on mount

app/controllers/avo/associations_controller.rb, lib/avo/resources/array_resource.rb, spec/dummy/app/avo/resources/event.rb, spec/dummy/app/models/event.rb
Fixes #3786
Adding access to `record` on the array field block:
```ruby
field :attendees, as: :array do
record.some_attendees
end
```
=> enhancement: access `record` on array block

lib/avo/mappings.rb, spec/dummy/app/models/city.rb, spec/dummy/app/models/post.rb, spec/dummy/app/models/product.rb, spec/dummy/app/models/project.rb, spec/features/avo/generators/resource_generator_spec.rb
Fixes #1677 
This PR fixes an issue where using `belongs_to` in `rails g model` would generate a `text` field instead of a proper association. The generator now treats `belongs_to` the same as `references`.
=> fix: `belongs_to` resource generator

Gemfile.lock, app/javascript/js/controllers/nested_form_controller.js
Fixes the nested records add button visibility by using `hidden` instead of `!hidden`, this is a Tailwind 4 breaking change 
Related PR https://github.com/avo-hq/avo-advanced/pull/62
=> fix: nested records hidden class

app/components/avo/alert_component.rb
Default alert component to info background color when type can't be identified.
=> refactor: default alert component background class

app/components/avo/views/resource_index_component.html.erb, app/components/avo/views/resource_index_component.rb, app/controllers/avo/base_controller.rb, lib/avo/resources/base.rb
This refactor moves `view_type` from `@index_params` into the `resource` object.
In [this PR](https://github.com/avo-hq/avo/pull/3780), we need to pass `view_type` to the action through params. With this change, we don't have to manually pass it to the action path generator. Since the action path generator already has access to the `resource`, it can just grab the `view_type` directly from there.
Without this refactor manual `view_type` would be required, such as:
```ruby
path, data = Avo::Actions::City::Update.link_arguments(
resource: resource,
view_type: ... # this would be required in order to enable grid item reload when using reload_records feature
)
```
=> refactor: access `view_type` from resource

lib/avo/mappings.rb
JSONB fields should be displayed as `code`, just like JSON fields.
Use `discover_columns` with a model that has a JSONB column. Without this PR, the column is not displayed, with this PR it is.
Happy to add tests if necessary.
Also, defining the `FIELDS_MAPPING` const could be cleaned up a bit, since many fields have the same value, e.g.:
```ruby
FIELDS_MAPPING = {
belongs_to: %i[references belongs_to],
boolean:    %i[boolean],
code:       %i[json jsonb],
date_time:  %i[datetime timestamp time],
date:       %i[date],
id:         %i[primary_key],
number:     %i[integer float decimal binary],
text:       %i[string],
textarea:   %i[text]
}.each_with_object({}) do |(key, value), hash|
value.each {
hash[_1] = {
field: key.to_s
}
}
end.freeze
```
=> add jsonb to fields mapping

lib/avo/resources/array_resource.rb, spec/dummy/app/avo/resources/movie.rb, spec/system/avo/array_resource_spec.rb
This PR resolves an issue with the `query` when an action is triggered on an array-based resource.
=> fix: array resource actions query

lib/avo/fields/textarea_field.rb
This PR moves the `hide_on: :index` call before `super`, allowing the behavior to be overridden with `show_on: :index` for `textarea` fields.
=> fix: allow textarea index field

app/components/avo/fields/date_field/index_component.html.erb
Fixes #3825
This PR sets the date content to `"inline-block"` on the index view, so the copyable component renders next to it instead of incorrectly appearing below.
=> fix: copyable date style

app/components/avo/fields/progress_bar_field/edit_component.html.erb, app/javascript/js/controllers/fields/progress_bar_field_controller.js, spec/dummy/app/avo/resources/project.rb, spec/system/avo/progress_bar_field_spec.rb
Fix progress bar field to allow a nil value during creation and update if the bar was untouched and the default field value is nil.
Fixes #3846
[Screencast from 15.05.2025 17:22:41.webm](https://github.com/user-attachments/assets/dae790a6-c806-4480-8b4e-5f32ad77c9ca)
=> refactor: allow progress field to submit nil values

app/javascript/js/controllers/item_select_all_controller.js
Populate `self.query` for standalone actions defined on self.index_controls. 
When an action is defined within an `index_control` in Avo, and this action is triggered with records selected, the `query` variable (expected to contain the IDs of the selected records) is empty (`[]`) when accessed via `self.message` within the action's execution context. However, the `query` variable is correctly populated with the selected record IDs if accessed within the `def handle` method of the same action.
Fixes #3855
https://github.com/user-attachments/assets/d30c775b-4494-4480-97da-051bf2d9b968
QA Scenarios
1. Trigger action with no selected records on Index Page => 0 count
2. Trigger action with selected records on Index Page => n counts
3. Trigger action on Show page => 0 count but 1 when executed …
=> fix: populate `self.query` for standalone `index_control` actions

lib/avo/engine.rb, spec/dummy/config/routes.rb
Accepts following syntax:
```rb
Rails.application.routes.draw do
mount_avo do
scope :resources do
get "courses/cities", to: "courses#cities"
get "users/get_users", to: "users#get_users"
end
put "switch_accounts/:id", to: "switch_accounts#update", as: :switch_account
end
end
```
1. Step 1
1. Step 2
=> enhancement: `mount_avo` accepts custom routes block

lib/avo/base_action.rb
Fixes #3859 
Changed the method for verifying if an action is active, and for generating the action URL, from using `record.persisted?` to `record.to_param.present?`.  
This is because, for array-based resources, the record may not be persisted but can still return a valid `to_param`.
=> fix: row actions on array resources

app/assets/stylesheets/avo.base.css
When using the `float: true` option in `row_controls_config`, the actions dropdown becomes unusable. The dropdown disappears as soon as the mouse leaves the table row to interact with the dropdown items, making it impossible to select any actions.
Fixes #3867
https://www.loom.com/share/206275a7a6424663a19811b153a1964e
1. Configure a resource with `float: true` in row_controls_config:
2. Setup `row_controls` with an `actions_list`
3. View the resource index page
4. Click on the "Actions" dropdown button for any row
5. Try to move the mouse cursor to select an item in the dropdown
=> Fix: Keep actions dropdown visible and on top when opened

app/components/avo/fields/belongs_to_field/edit_component.html.erb, app/javascript/js/controllers/fields/belongs_to_field_controller.js
The polymorphic holder `div` was not hidden, causing the `divide-y` property to add an extra divider.
This PR adds a `hidden` class by default and changes visibility when the holder is populated.
=> fix: hide polymorphic holder div

app/components/avo/items/panel_component.rb, app/components/avo/views/resource_edit_component.rb, app/components/avo/views/resource_show_component.rb
Identified this dead code and removed it.  
I noticed it was related to the Trix field, where it was supposed to render a show component when disabled.  
I went ahead and tested it, this behavior doesn't seem to apply (with or without this code),  so that might be a regression. I created an [issue](https://github.com/avo-hq/avo/issues/3888) to track and fix it.
=> refactor: remove dead code

lib/avo/resources/resource_manager.rb
Complementary to https://github.com/avo-hq/avo/pull/3893
=> fix: mark `BaseResource` as abstract in resource manager `fetch_resources`

lib/generators/avo/eject_generator.rb
Fixed `gsub(".rb", ".html.erb")` in eject generator to only replace the file extension (`.rb` at end of string) rather than all occurrences of "rb" in the filename. 
This prevents issues with files like 
```
/home/bob/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/avo-4.0.0.pre.dev.2/app/components/avo/fields/text_field/index_component.rb
```
being incorrectly transformed to 
```
/home/bob/.html.erbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/avo-4.0.0.pre.dev.2/app/components/avo/fields/text_field/index_component.html.erb
```
=> fix: eject generator for components ejection

app/views/avo/partials/_color_scheme_switcher.html.erb
Fixes missing method `color_scheme_path`
=> fix: missing method `color_scheme_path`

app/assets/stylesheets/application.css, app/assets/stylesheets/css/search.css, app/controllers/avo/search_controller.rb, app/javascript/js/controllers.js, app/javascript/js/controllers/search_controller.js, config/routes.rb
I broke searchable fields by removing the search-related controllers here: https://github.com/avo-hq/avo/pull/3712
I reverted those controllers just to keep the searchable fields working until we migrate to an alternative for searchable fields.
=> revert searchable fields compatibility

app/javascript/js/controllers/action_controller.js, app/views/avo/actions/show.html.erb, lib/avo/base_action.rb, spec/dummy/app/avo/actions/export_csv.rb, spec/dummy/app/avo/actions/test/no_confirmation_posts_redirect.rb, spec/dummy/app/avo/actions/test/no_confirmation_redirect.rb, spec/dummy/app/avo/actions/toggle_admin.rb, spec/dummy/app/avo/actions/toggle_published.rb, spec/dummy/app/avo/resources/post.rb
Rename `no_confirmation` action option to `confirmation`
=> rename `no_confirmation` action option to `confirmation`

spec/dummy/config/database.yml
I updated the names of the databases that are created in the dummy app from "dummy_3_(dev|test)" to "avo_dummy_(dev|test|prod)".
=> set sensible db names for dummy app

app/javascript/avo.base.js
The fail to load mechanism to pretty render some messages when an error is raised within a turbo frame has been broken for a while now and we noticed it recently.
The issue is related to this [hotwire issue](https://github.com/hotwired/turbo/issues/886) that is familiar to Avo since we fixed another similar issue a while ago with the fix found on that issue.
=> fix: fail to load frame

app/controllers/avo/search_controller.rb
I left a debug piece of code by mistake in the `render_error?` method. This PR removes it.
=> chore: revert debug code in the `render_error?` method

lib/generators/avo/js/install_generator.rb
The `preload` param can be removed, since "true" is the default value.
=> remove `preload: true`, since it's the default

app/components/avo/fields/date_time_field/edit_component.html.erb, app/components/avo/fields/time_field/edit_component.html.erb
Fixes #4058
Add disabled state to the clear button for `date` and `date_time` fields.
=> fix: disabled clear button on date fields
