- lib/avo/app/fields/field_extensions/visible_in_different_views.rb
- lib/avo/app/fields/password_field.rb
- spec/dummy/app/avo/resources/user.rb
Let me know what can be improved
Thanks!
*Documentation also updated for 'Showing / Hiding fields on different views' and 'Password Field' sections.
> fix: only_on not working on password and implementation of show_on/hide_on all

- app/frontend/js/components/Index/GravatarField.vue
- app/frontend/js/components/Index/IdField.vue
- app/frontend/js/components/Index/TextField.vue
> fix: link_to_resource removed when show restricted

- app/frontend/js/components/Button.vue
- app/frontend/js/components/Edit/DatetimeField.vue
- app/frontend/js/components/Index/ResourceFilters.vue
- app/frontend/js/views/ResourceIndex.vue
Clicking reset button for filters resets the filters to default and closes the filters modal.
> feature: reset button for filters

- app/frontend/js/components/Edit/DatetimeField.vue
> feature: set now/today button for datetime/date fields

- app/frontend/js/components/Edit/MarkdownField.vue
This removes the forced autofocus from markdown field
> fix: markdown field forces autofocus

- app/frontend/css/application.css
- app/frontend/js/components/Panel.vue
- app/views/layouts/avo/application.html.erb
> fix: janky page transitions

- app/controllers/avo/application_controller.rb
- app/controllers/avo/resource_overview_controller.rb
- app/controllers/avo/resources_controller.rb
- app/controllers/avo/search_controller.rb
- app/views/layouts/avo/_javascript.html.erb
- lib/avo/app/services/authorization_service.rb
- lib/avo/configuration.rb
- lib/generators/avo/templates/initializer/avo.rb
- spec/dummy/config/initializers/avo.rb
This PR adds two keys to Avo's configuration: `current_user_method` and `authenticate_with`.
> feature: configurable authentication

- app/mailers/avo/application_mailer.rb
- lib/avo/configuration.rb
Fixes https://github.com/avo-hq/avo/issues/208 and https://github.com/avo-hq/avo/issues/209
> fix: global classes loading as locals

- app/views/layouts/avo/_edit_field_wrapper.html.erb
- spec/features/avo/password_spec.rb
- made help text allow href and html
- made tests for edit and create
> (AVO-36) feature: Password field

- CONTRIBUTING.MD
- app/components/avo/modal_component.rb
- app/components/avo/panel_component.rb
- app/components/avo/show/fields/has_one_field_component.html.erb
- app/components/avo/views/resource_edit_component.html.erb
- app/components/avo/views/resource_index_component.html.erb
- app/components/avo/views/resource_new_component.html.erb
- app/components/avo/views/resource_show_component.html.erb
- app/views/avo/actions/show.html.erb
- app/views/avo/home/index.html.erb
- app/views/avo/relations/new.html.erb
- lib/generators/avo/templates/tool/view.tt
- spec/dummy/app/views/avo/tools/custom_tool.html.erb
Hi Adrian,
I just found out about your awesome gem and as it happens I saw some deprecation warnings. ViewComponents are ditching content areas for the slots syntax, so the make the project future proof I replaced it for you. 👋
> Migrate view components to slots

- app/components/avo/index/grid_cover_empty_state_component.html.erb
- app/components/avo/index/grid_cover_empty_state_component.rb
- app/components/avo/index/grid_item_component.html.erb
- app/components/avo/show/fields/has_one_field_component.html.erb
- app/components/avo/views/resource_edit_component.html.erb
- app/components/avo/views/resource_index_component.html.erb
- app/components/avo/views/resource_new_component.html.erb
- app/helpers/avo/application_helper.rb
- app/views/avo/home/index.html.erb
- lib/avo/grid_collector.rb
- lib/generators/avo/templates/tool/view.tt
- spec/components/avo/index/grid_cover_empty_state_component_spec.rb
- spec/dummy/app/views/avo/tools/custom_tool.html.erb
Fixes https://github.com/avo-hq/avo/issues/326
> fix: grid cover broken if it's nil

- app/views/avo/home/_actions.html.erb
- app/views/avo/home/_docs.html.erb
- app/views/avo/home/_filters.html.erb
- app/views/avo/home/_resources.html.erb
- app/views/avo/home/index.html.erb
Fixes https://github.com/avo-hq/avo/issues/332
> chore: update get started page & removed ApplicationRecord dependency

- bin/helpers.rb
Hi guys :wave: 
This is my first PR for avo!
While trying to setup everything, I found a problem while trying to run the `bin/init` that was solved with that tiny change.
> Fix init script

- app/helpers/avo/application_helper.rb
- lib/avo.rb
- spec/dummy/config/boot.rb
Fixes https://github.com/avo-hq/avo/issues/361
> fix: remove webpacker as a dependency in test env

- app/components/avo/fields/common/status_viewer_component.html.erb
- app/packs/stylesheets/components/status.css
- app/packs/svgs/check-circle-sm.svg
- app/packs/svgs/x-circle-sm.svg
- spec/features/avo/status_field_spec.rb
- spec/system/avo/status_field_spec.rb
Improved the design for the status field.
> refactor: better status field

- lib/generators/avo/templates/locales/avo.en.yml
- lib/generators/avo/templates/locales/avo.nb-NO.yml
- lib/generators/avo/templates/locales/avo.pt-BR.yml
- lib/generators/avo/templates/locales/avo.ro.yml
Hello, first of all, thanks for this amazing gem!! In this PR i did two minor changes to locales templates:
1 - The cancel tag was duplicated.
2 - The first tag of pt-BR locale was just pt, so i changed to pt-BR, same thing to nb-NO.
> fix: Small locales fixes

- README.md
- app/controllers/avo/base_controller.rb
- lib/avo/base_resource.rb
- spec/dummy/app/avo/resources/project_resource.rb
- spec/dummy/app/models/project.rb
Docs 👉 https://docs.avohq.io/1.0/resources.html#unscoped-queries-on-index
> feature: unscoped queries on index

- lib/avo/configuration.rb
- lib/generators/avo/field_generator.rb
- lib/generators/avo/templates/initializer/avo.tt
> Allow custom view component directory

- app/controllers/avo/base_controller.rb
- spec/system/avo/query_scope_spec.rb
Fixes https://github.com/avo-hq/avo/issues/436
> fix: allow sorting columns on index when default_value or resolve_query_scope are set

- app/controllers/avo/base_controller.rb
https://github.com/avo-hq/avo/issues/436
> fix: unscope only order for table header

- app/views/avo/partials/_profile_dropdown.html.erb
Fixes https://github.com/avo-hq/avo/issues/431
> fix: hide the toggle-panel controller where there's no dropdown

- app/controllers/avo/actions_controller.rb
- app/packs/js/controllers/actions_picker_controller.js
- app/packs/js/controllers/item_selector_controller.js
- app/views/avo/base/_actions.html.erb
- lib/avo/base_action.rb
- lib/generators/avo/action_generator.rb
- lib/generators/avo/templates/standalone_action.tt
- spec/dummy/app/avo/actions/dummy_action.rb
- spec/dummy/app/avo/resources/team_resource.rb
- spec/dummy/app/avo/resources/user_resource.rb
Fixes https://github.com/avo-hq/avo/issues/446 & https://github.com/avo-hq/avo/discussions/363
> feature: standalone actions

- app/controllers/avo/actions_controller.rb
Fixes https://github.com/avo-hq/avo/issues/439
> fix: actions broken when using string ids

- app/components/avo/views/resource_index_component.html.erb
- app/helpers/avo/resources_helper.rb
- app/views/avo/base/_actions.html.erb
Fixes #453 if the correct approach (see details there). Grateful for feedback on the change!
> Use same resource name as show component

- app/components/avo/fields/has_one_field/show_component.html.erb
- app/components/avo/fields/has_one_field/show_component.rb
- app/components/avo/index/resource_controls_component.html.erb
- app/components/avo/index/resource_controls_component.rb
- app/components/avo/resource_component.rb
- app/components/avo/views/resource_index_component.html.erb
- app/components/avo/views/resource_index_component.rb
- app/components/avo/views/resource_show_component.html.erb
- app/components/avo/views/resource_show_component.rb
- app/controllers/avo/relations_controller.rb
- app/controllers/avo/search_controller.rb
- lib/avo/base_resource.rb
- lib/avo/services/authorization_service.rb
- spec/dummy/app/policies/user_policy.rb
[BUG] Detach button should not be visible when user is not authorized to delete #449
> feature: relationships authorization

- app/components/avo/fields/has_one_field/show_component.html.erb
- app/components/avo/fields/has_one_field/show_component.rb
- app/components/avo/index/resource_controls_component.html.erb
- app/components/avo/index/resource_controls_component.rb
- app/components/avo/resource_component.rb
- app/components/avo/views/resource_index_component.html.erb
- app/components/avo/views/resource_index_component.rb
- app/components/avo/views/resource_show_component.html.erb
- app/components/avo/views/resource_show_component.rb
- app/controllers/avo/relations_controller.rb
- app/controllers/avo/search_controller.rb
- lib/avo/base_resource.rb
- lib/avo/services/authorization_service.rb
- spec/dummy/app/policies/user_policy.rb
- spec/features/avo/search_spec.rb
https://github.com/avo-hq/avo/issues/456
> fix: undefined method readonly on relationship

- app/controllers/avo/actions_controller.rb
- lib/avo/fields/base_field.rb
- lib/avo/fields_collector.rb
Fixes https://github.com/avo-hq/avo/issues/459
> fix: actions with plural names fail bc names are classified as singular

- lib/avo/configuration.rb
Fixes https://github.com/avo-hq/avo/issues/462
> fix: nullpointer due to computer_root_path

- app/views/avo/base/_actions.html.erb
fixes https://github.com/avo-hq/avo/issues/468
> fix: action button alignment

- app/components/avo/views/resource_show_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/470
> fix: actions are broken when using resources with string id

- lib/avo/configuration.rb
fixes https://github.com/avo-hq/avo/issues/482
> fix: custom tools navigation namespace

- app/packs/js/controllers/multiple_select_filter_controller.js
- app/views/avo/base/_multiple_select_filter.html.erb
- lib/avo/filters/multiple_select_filter.rb
- spec/dummy/app/avo/filters/post_status_filter.rb
- spec/system/avo/filters_spec.rb
A brand new filter which allows selection of multiple options. The code was sufficiently different from `SelectFilter` to want to create a new filter + Stimulus controller.
Feedback welcome!
> Multiple select filter

- app/components/avo/fields/common/single_file_viewer_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/487
> fix: delete attachment link broken

- app/views/avo/sidebar/_license_warnings.html.erb
- lib/avo/configuration.rb
- lib/generators/avo/templates/initializer/avo.tt
- spec/features/avo/h_q_spec.rb
> fix: manage frontend display of AvoHQ error on timeout request

- app/controllers/avo/search_controller.rb
- app/packs/js/controllers/search_controller.js
- app/packs/stylesheets/search.css
- app/views/avo/sidebar/_license_warnings.html.erb
- lib/avo/base_resource.rb
- lib/avo/configuration.rb
- lib/generators/avo/templates/initializer/avo.tt
- spec/dummy/app/avo/resources/post_resource.rb
- spec/features/avo/h_q_spec.rb
> feature: allow search help text for search headers

- app/views/avo/base/_filters.html.erb
> feature: display applied filters indicator

- app/packs/js/controllers/search_controller.js
- app/views/avo/partials/_global_search.html.erb
- lib/generators/avo/templates/locales/avo.en.yml
- lib/generators/avo/templates/locales/avo.nb-NO.yml
- lib/generators/avo/templates/locales/avo.pt-BR.yml
- lib/generators/avo/templates/locales/avo.ro.yml
- spec/dummy/config/locales/avo.en.yml
https://github.com/avo-hq/avo/discussions/379#discussioncomment-1296624
> refactor: added translations to search (placeholder and cancel button)

- app/views/avo/sidebar/_sidebar.html.erb
> Changes sidebar resource label to plural_name

- app/views/avo/sidebar/_sidebar.html.erb
- lib/avo/base_resource.rb
* Support custom resource label in navigation sidebar
> Add navigation_label to Resources

- lib/avo/fields/base_field.rb
- lib/generators/avo/templates/locales/avo.en.yml
- lib/generators/avo/templates/locales/avo.nb-NO.yml
- lib/generators/avo/templates/locales/avo.pt-BR.yml
- lib/generators/avo/templates/locales/avo.ro.yml
- spec/dummy/config/locales/avo.en.yml
Fixes https://github.com/avo-hq/avo/issues/537
> fix: visibility option broken

- app/packs/js/controllers/filter_controller.js
The TextFilter could not search Unicode string.
It's caused by the `btoa` method,
which will throw an error when encontering the Unicode string.
Rewrite the Base64 encode/decode method suggested by Stackoverflow:
https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings
> Issue-533 Fix the TextFilter bug with Unicode string

- lib/avo/fields/files_field.rb
This fixes a bug we introduced in 1.18.0
> fix: files field allow other values

- app/views/avo/partials/_profile_dropdown.html.erb
- lib/avo/configuration.rb
Fixes https://github.com/avo-hq/avo/issues/546
> dynamic user resource name

- app/controllers/avo/base_controller.rb
- lib/avo/base_action.rb
- spec/dummy/app/avo/actions/dummy_action.rb
- spec/system/avo/actions_spec.rb
Fixes https://github.com/avo-hq/avo/issues/588
> feature: actions visibility

- .github/workflows/test.yml
- Gemfile
- Gemfile.lock
- app/components/avo/views/resource_edit_component.html.erb
- app/components/avo/views/resource_new_component.html.erb
- app/components/avo/views/resource_show_component.html.erb
- app/helpers/avo/application_helper.rb
- app/packs/entrypoints/application.css
- app/packs/js/controllers/loading_button_controller.js
- app/packs/stylesheets/spinner.css
- spec/rails_helper.rb
- spec/system/avo/country_field_spec.rb
Fixes https://github.com/avo-hq/avo/issues/591
> feature: add loading spinner to submit buttons

- lib/avo/base_resource.rb
- spec/features/avo/multiple_names_model_spec.rb
Fixes https://github.com/avo-hq/avo/issues/610
> fix: model with two or more words have a bad form_scope

- app/components/avo/views/resource_edit_component.html.erb
- app/components/avo/views/resource_edit_component.rb
- app/components/avo/views/resource_index_component.html.erb
- app/components/avo/views/resource_index_component.rb
- app/components/avo/views/resource_new_component.html.erb
- app/components/avo/views/resource_new_component.rb
- app/components/avo/views/resource_show_component.html.erb
- app/components/avo/views/resource_show_component.rb
- app/controllers/avo/application_controller.rb
- app/controllers/avo/base_controller.rb
- spec/features/avo/controller_action_spec.rb
Based on [this](https://discord.com/channels/740892036978442260/740893011994738751/935108679848566844) discussion.
> chore: set model before authorize action

- app/components/avo/resource_component.rb
- app/components/avo/views/resource_index_component.html.erb
- app/components/avo/views/resource_index_component.rb
- app/components/avo/views/resource_new_component.html.erb
- app/controllers/avo/base_controller.rb
- lib/avo/base_resource.rb
- spec/dummy/app/avo/resources/person_resource.rb
- spec/dummy/app/models/person.rb
- spec/dummy/app/models/user.rb
- spec/dummy/db/migrate/20220201135401_add_spouse_id_person.rb
- spec/dummy/db/schema.rb
- spec/features/avo/create_through_record_spec.rb
Fixes https://github.com/avo-hq/avo/issues/606
> feature: HABTM create record

- app/assets/stylesheets/avo.css
- app/javascript/avo.js
- app/views/avo/partials/_global_search.html.erb
- app/views/layouts/avo/application.html.erb
Making avo more pleasant for windows users.
> chore: different os search icon

- app/components/avo/panel_component.html.erb
- app/components/avo/resource_component.rb
- app/components/avo/views/resource_index_component.rb
- app/components/avo/views/resource_show_component.html.erb
- app/components/avo/views/resource_show_component.rb
- lib/avo/fields/base_field.rb
- spec/dummy/app/avo/resources/user_resource.rb
- spec/dummy/config/locales/avo.en.yml
- spec/features/avo/i18n_spec.rb
Fixes https://github.com/avo-hq/avo/issues/629
[Docs](https://docs.avohq.io/1.0/localization.html#localizing-fields)
> feature: custom labels for associations

- app/controllers/avo/relations_controller.rb
- lib/avo/base_resource.rb
- lib/avo/fields/has_base_field.rb
- spec/dummy/app/avo/resources/user_resource.rb
- spec/dummy/app/models/comment.rb
- spec/features/avo/has_many_field_spec.rb
Fixes https://github.com/avo-hq/avo/issues/628
> feature: add scopes to associations

- .github/PULL_REQUEST_TEMPLATE.md
- app/components/avo/index/resource_controls_component.rb
- app/components/avo/resource_component.rb
- app/components/avo/views/resource_edit_component.html.erb
- app/components/avo/views/resource_index_component.rb
- app/components/avo/views/resource_new_component.html.erb
- app/components/avo/views/resource_show_component.rb
- app/controllers/avo/base_controller.rb
- db/factories.rb
- lib/avo/base_resource.rb
- lib/avo/services/authorization_service.rb
- spec/dummy/app/avo/resources/course_link_resource.rb
- spec/dummy/app/avo/resources/course_resource.rb
- spec/dummy/app/controllers/avo/course_links_controller.rb
- spec/dummy/app/controllers/avo/courses_controller.rb
- spec/dummy/app/models/course.rb
- spec/dummy/app/models/course/link.rb
- spec/dummy/db/migrate/20220207085343_create_courses.rb
- spec/dummy/db/migrate/20220207085352_create_course_links.rb
- spec/dummy/db/schema.rb
- spec/dummy/test/factories/course/links.rb
- spec/dummy/test/factories/courses.rb
- spec/features/avo/create_through_record_spec.rb
- spec/features/avo/has_many_field_spec.rb
1. Create and edit a `Course::Link`
2. The edits should go through as normal
> fix: broken form scope for namespaced models

- Gemfile
- Gemfile.lock
- app/components/avo/index/resource_controls_component.html.erb
- app/components/avo/index/resource_controls_component.rb
- app/components/avo/resource_component.rb
- app/components/avo/views/resource_index_component.html.erb
- app/components/avo/views/resource_index_component.rb
- app/views/avo/partials/_table_header.html.erb
- lib/avo/services/authorization_service.rb
- spec/dummy/app/avo/resources/team_resource.rb
- spec/dummy/app/models/team.rb
- spec/dummy/app/policies/team_policy.rb
- spec/dummy/app/policies/user_policy.rb
- spec/dummy/db/seeds.rb
- spec/features/avo/multiple_names_model_spec.rb
- spec/requests/avo/authorization/associations_spec.rb
- spec/system/avo/filters_spec.rb
Fixes https://github.com/avo-hq/avo/issues/634
1. Update the `TeamPolicy` attachment methods
1. See the changes on the team page. create/attach/actions buttons will disappear along the row buttons at the end.
> feature: advanced autorizations for associations

- lib/avo/fields/key_value_field.rb
This reverts commit 56c641367efefe5668a7235b8c388d8fc835587c.
1. Step 1
1. Step 2
> Revert "Fix key_value_field translation (#640)"

- app/components/avo/resource_component.rb
Fixes https://github.com/avo-hq/avo/issues/647
> feature: hydrate resource with model in authorization service

- .github/PULL_REQUEST_TEMPLATE.md
- docker/Dockerfile
> chore: misc support files tweks

- db/factories.rb
- spec/dummy/app/avo/resources/course_link_resource.rb
> chore: minor tweaks

- app/javascript/js/controllers/item_selector_controller.js
- lib/avo/base_resource.rb
- spec/features/avo/has_many_field_spec.rb
- spec/system/avo/has_many_spec.rb
Fixes https://github.com/avo-hq/avo/issues/668
1. Go to a team and see the reviews section. the reviews should have the user column
2. Go to a post and see the comments section. It should have the User column.
> fix: some fields are hidden on the has_many view

- app/views/avo/partials/_logo.html.erb
- app/views/avo/sidebar/_sidebar.html.erb
- spec/features/avo/app_spec.rb
Fixes https://github.com/avo-hq/avo/discussions/680
> refactor: move the root_path link in the logo partial

- lib/avo/fields/key_value_field.rb
https://github.com/avo-hq/avo/pull/640
1. Step 1
1. Step 2
> Fix key_value_field translation (#640)

- app/javascript/js/controllers/search_controller.js
- spec/features/avo/belongs_to_polymorphic_spec.rb
- spec/support/wait_for_loaded.rb
Add a dynamic way to wait for search to be finished.
> chode: fix flaky tests (wait for search)

- lib/avo/licensing/h_q.rb
Adds a few more exception rules to the HQ 
Description...
1. Step 1
1. Step 2
> chore: add a few more exceptions to hq response

- lib/generators/avo/templates/locales/avo.en.yml
I forgot to output the locales. Sorry...
> fix: add locales for ordering

- Gemfile.lock
- app/components/avo/base_component.rb
- app/components/avo/index/ordering/base_component.rb
- app/components/avo/index/ordering/button_component.html.erb
- app/components/avo/index/ordering/button_component.rb
- app/components/avo/index/ordering/buttons_component.html.erb
- app/components/avo/index/ordering/buttons_component.rb
- app/components/avo/index/resource_controls_component.html.erb
- app/components/avo/index/resource_controls_component.rb
- app/components/avo/resource_component.rb
- app/controllers/avo/base_controller.rb
- app/controllers/avo/relations_controller.rb
- avo.gemspec
- config/routes.rb
- lib/avo/base_resource.rb
- lib/avo/hosts/ordering.rb
- spec/dummy/app/avo/resources/course_link_resource.rb
- spec/dummy/app/models/course/link.rb
Fixes https://github.com/avo-hq/avo/issues/716
> fix: resource ordering broken in association

- .github/release-drafter-1x.yml
- .github/workflows/release-notes.yml
Description...
1. Step 1
1. Step 2
> chore: release drafter 1.x (#730)

- .github/release-drafter-1x.yml
- .github/workflows/release-notes.yml
Description...
1. Step 1
1. Step 2
> chore: release drafter 1.x (#730) (#732)

- Brewfile
- bin/dev
> chore: foreman to overmind migration

- .github/release-drafter.yml
- .github/workflows/release-notes.yml
- app/components/avo/actions_component.html.erb
- app/components/avo/index/resource_controls_component.html.erb
- app/components/avo/panel_component.html.erb
- app/components/avo/panel_component.rb
- app/components/avo/views/resource_edit_component.html.erb
- app/components/avo/views/resource_show_component.html.erb
- app/views/avo/actions/show.html.erb
- app/views/avo/associations/new.html.erb
Fixes https://github.com/avo-hq/avo/issues/741
After a chat with Khris we figured it's because some forms were not using `local: true`.
> fix: use local on forms

- app/components/avo/panel_component.html.erb
- app/components/avo/panel_component.rb
- app/components/avo/views/resource_edit_component.html.erb
- app/components/avo/views/resource_new_component.html.erb
- lib/avo/configuration.rb
Fixes https://github.com/avo-hq/avo/issues/672
[Docs](https://docs.avohq.io/2.0/resources.html#show-buttons-on-form-footers)
> feature: optionally show buttons on footer forms

- app/components/avo/fields/badge_field/index_component.html.erb
- app/components/avo/fields/boolean_field/index_component.html.erb
- app/components/avo/fields/external_image_field/index_component.html.erb
- app/components/avo/fields/file_field/index_component.html.erb
- app/components/avo/fields/file_field/index_component.rb
- app/components/avo/fields/gravatar_field/index_component.html.erb
- app/components/avo/fields/progress_bar_field/index_component.html.erb
- app/components/avo/index/field_wrapper_component.html.erb
- app/components/avo/index/field_wrapper_component.rb
- lib/avo/fields/external_image_field.rb
- spec/dummy/app/avo/resources/post_resource.rb
- spec/dummy/app/components/avo/fields/color_picker_field/index_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/760
This PR also fixes a few other inconsistencies with the table row.
> fix: file index field does not apply constraints to the image

- app/controllers/avo/search_controller.rb
- lib/avo/base_resource.rb
- spec/dummy/app/avo/resources/team_membership_resource.rb
> fix: hide_from_global_search

- lib/avo/fields/base_field.rb
Fixes i18n for fields
Description...
1. Step 1
1. Step 2
> Fix fields i18n

- app/controllers/avo/base_controller.rb
- lib/avo/base_resource.rb
- spec/dummy/app/avo/resources/comment_resource.rb
- spec/features/avo/after_create_update_path_spec.rb
- spec/features/avo/belongs_to_polymorphic_spec.rb
Fixes https://github.com/avo-hq/avo/discussions/776
[Docs](https://docs.avohq.io/2.0/resources.html#customize-what-happens-after-record-is-created-edited)
Description...
1. Step 1
1. Step 2
> feature: after create/update path

- app/components/avo/alert_component.html.erb
- app/components/avo/alert_component.rb
- app/components/avo/views/resource_show_component.html.erb
- app/components/avo/views/resource_show_component.rb
- lib/avo/base_action.rb
- lib/avo/base_resource.rb
- lib/avo/fields_collector.rb
- spec/features/avo/invalid_field_spec.rb
Fixes https://github.com/avo-hq/avo/issues/785
1. Visit a team
2. see the red alert on the bottom
> chore: display invalid fields errors

- .github/workflows/release-notes.yml
- app/helpers/avo/url_helpers.rb
- app/views/avo/partials/_profile_dropdown.html.erb
- lib/avo/base_resource.rb
- spec/dummy/config/application.rb
Add support for namespaced model names
> fix: add support for namespaced models

- app/components/avo/filters_component.html.erb
- app/components/avo/sidebar_profile_component.html.erb
- spec/dummy/app/avo/resources/person_resource.rb
- spec/dummy/app/avo/resources/post_resource.rb
- spec/dummy/app/avo/resources/team_resource.rb
Fixes https://github.com/avo-hq/avo/issues/793
> fix: missing target for controller in profile image

- Gemfile
- Gemfile.lock
- app/views/layouts/avo/application.html.erb
- spec/dummy/config/environments/development.rb
Tiny dev experience improvement
> chore: add hotwire livereload

- app/components/avo/index/grid_item_component.html.erb
- app/components/avo/index/table_row_component.html.erb
- app/views/avo/partials/_table_header.html.erb
- lib/avo/base_resource.rb
- spec/dummy/app/avo/resources/comment_resource.rb
- spec/features/avo/record_selector_spec.rb
Fixes https://github.com/avo-hq/avo/discussions/803
[Docs](https://docs.avohq.io/2.0/resources.html#hide-the-record-selector-checkbox)
> feature: hide record selector

- app/components/avo/fields/belongs_to_field/autocomplete_component.html.erb
- app/components/avo/fields/belongs_to_field/edit_component.rb
- lib/avo/fields/belongs_to_field.rb
- spec/dummy/app/avo/resources/comment_resource.rb
- spec/dummy/app/avo/resources/review_resource.rb
- spec/dummy/config/environments/development.rb
- spec/features/avo/allow_via_detaching_spec.rb
Fixes https://github.com/avo-hq/avo/discussions/806
[Docs](https://docs.avohq.io/2.0/associations.html#allow-detaching-via-the-association)
> feature: allow via detaching

- app/javascript/js/controllers/search_controller.js
Fixes https://github.com/avo-hq/avo/issues/815
> fix: unscrollable searchable belongs_to

- app/components/avo/panel_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/814
> fix: resource description truncated

- app/javascript/js/controllers/search_controller.js
We got a [heads up](https://github.com/lollipopai/avo) from our friends at lollipopai.
Description...
1. Step 1
1. Step 2
> fix: xss vulnerability in search

- .github/release-drafter.yml
- app/components/avo/index/field_wrapper_component.rb
- lib/avo/fields/base_field.rb
- spec/dummy/app/avo/resources/project_resource.rb
Fixes https://github.com/avo-hq/avo/issues/787
[Docs](https://docs.avohq.io/2.0/field-options.html#link-to-resource)
> feature: text-align right and center on index view

- lib/avo/reloader.rb
Fixes https://github.com/avo-hq/avo/issues/848
> fix: reloader broke the initializer

- CONTRIBUTING.MD
- Gemfile
- Gemfile.lock
- spec/dummy/app/models/comment.rb
- spec/dummy/app/models/course.rb
- spec/dummy/app/models/course/link.rb
- spec/dummy/app/models/fish.rb
- spec/dummy/app/models/person.rb
- spec/dummy/app/models/post.rb
- spec/dummy/app/models/project.rb
- spec/dummy/app/models/review.rb
- spec/dummy/app/models/spouse.rb
- spec/dummy/app/models/team.rb
- spec/dummy/app/models/team_membership.rb
- spec/dummy/app/models/user.rb
- spec/dummy/config/environments/development.rb
> chore: add annotate gem

- app/controllers/avo/base_controller.rb
- app/javascript/js/controllers/filter_controller.js
- app/javascript/js/controllers/multiple_select_filter_controller.js
- app/javascript/js/controllers/select_filter_controller.js
- app/views/avo/base/_boolean_filter.html.erb
- app/views/avo/base/_multiple_select_filter.html.erb
- app/views/avo/base/_select_filter.html.erb
- app/views/avo/base/_text_filter.html.erb
- lib/avo/filters/base_filter.rb
- lib/avo/filters/boolean_filter.rb
- lib/avo/filters/multiple_select_filter.rb
- lib/avo/filters/text_filter.rb
- spec/dummy/app/avo/filters/dummy_multiple_select_filter.rb
- spec/dummy/app/avo/filters/featured_filter.rb
- spec/dummy/app/avo/filters/is_admin.rb
- spec/dummy/app/avo/filters/members_filter.rb
- spec/dummy/app/avo/filters/people_2_filter.rb
- spec/dummy/app/avo/filters/post_status_filter.rb
- spec/dummy/app/avo/filters/published_filter.rb
- spec/dummy/app/avo/filters/user_names_filter.rb
- spec/dummy/app/avo/resources/user_resource.rb
- spec/dummy/app/models/user.rb
- spec/system/avo/filters/filter_keep_defaults_spec.rb
Fixes https://github.com/avo-hq/avo/issues/841
> fix: filter defaults not applied if more filters have values

- app/mailers/avo/application_mailer.rb
Fixes https://github.com/avo-hq/avo/issues/860
> fix: remove mailer

- app/assets/stylesheets/css/components/code.css
- app/components/avo/profile_item_component.html.erb
- app/components/avo/profile_item_component.rb
- app/components/avo/sidebar_component.html.erb
- app/components/avo/sidebar_profile_component.html.erb
- app/controllers/avo/application_controller.rb
- app/controllers/avo/debug_controller.rb
- app/javascript/js/controllers.js
- app/javascript/js/controllers/copy_to_clipboard_controller.js
- app/javascript/js/controllers/fields/code_field_controller.js
- app/views/avo/debug/index.html.erb
- app/views/avo/debug/report.html.erb
- config/routes.rb
- lib/avo/app.rb
- lib/avo/engine.rb
- lib/avo/fields/code_field.rb
- lib/avo/licensing/h_q.rb
- lib/avo/licensing/license.rb
- lib/avo/licensing/license_manager.rb
- lib/avo/version.rb
- lib/tasks/avo_tasks.rake
- spec/features/avo/destroy_record_spec.rb
- spec/features/avo/h_q_spec.rb
- spec/support/download_helpers.rb
This PR should make it easier to debug license issues and give the user the ability to refresh the license on their apps.
> fix: menu display, license cache & debug tools 

- app/views/avo/partials/_sidebar_extra.html.erb
- lib/generators/avo/eject_generator.rb
Fixes https://github.com/avo-hq/avo/issues/801
> fix: eject command broken for sidebar

- .github/workflows/reviewdog.yml
Fix the broken reviewdog/standardrb check
> chore: fix standardrb

- app/components/avo/paginator_component.html.erb
- app/components/avo/paginator_component.rb
- app/components/avo/views/resource_index_component.html.erb
- app/helpers/avo/url_helpers.rb
Fixes https://github.com/avo-hq/avo/issues/872
> fix: has many loses scope on per page change

- Gemfile
- Gemfile.lock
> chore: add bundler integrity

- app/components/avo/fields/belongs_to_field/autocomplete_component.html.erb
- app/controllers/avo/search_controller.rb
- app/javascript/js/controllers/search_controller.js
- lib/avo/hosts/association_scope_host.rb
- spec/dummy/app/avo/resources/team_membership_resource.rb
- spec/dummy/app/avo/resources/team_resource.rb
- spec/dummy/app/models/user.rb
- spec/dummy/config/initializers/avo.rb
- spec/system/avo/query_scope_spec.rb
Fixes https://github.com/avo-hq/avo/issues/904
Description...
1. Step 1
1. Step 2
> feature: initialize the parent and attach the grandparent in attach_scope

- lib/generators/avo/templates/initializer/avo.tt
I'd recommend removing the usage of gendered language here, as it can be off-putting to assume the users gender to be masculine.
https://writingcenter.unc.edu/tips-and-tools/gender-inclusive-language/
> Remove gendered language

- app/components/avo/views/resource_index_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/853
> fix: search broken for uncountable resources

- app/components/avo/card_component.html.erb
- lib/avo/base_card.rb
- lib/generators/avo/templates/cards/chartkick_card_sample.tt
- lib/generators/avo/templates/cards/metric_card_sample.tt
- spec/dummy/app/avo/cards/example_area_chart.rb
- spec/dummy/app/avo/cards/example_custom_partial.rb
- spec/dummy/app/views/avo/cards/_custom_card.html.erb
Fixes https://github.com/avo-hq/avo/issues/772
> refactor: enable range in all cards

- .github/publish-release-to-avo-hq-io.js
- .github/workflows/release-notes.yml
- .github/workflows/release.yml
> chore: ping avohq.io on a PR merge

- app/components/avo/sidebar/item_switcher_component.html.erb
- lib/avo/menu/base_item.rb
- lib/avo/menu/dashboard.rb
- lib/avo/menu/resource.rb
- spec/dummy/config/initializers/avo.rb
- spec/features/avo/app_spec.rb
Fixes https://github.com/avo-hq/avo/issues/942
1. Observe the `Fishies` label for fish
> feature: add label to some menu items

- .github/pr-labeler.yml
Fixes the PR labeler for contributions
> chore: pr-labeler

- app/components/avo/common_field_wrapper_component.html.erb
- lib/avo/fields/base_field.rb
- lib/avo/fields/concerns/is_required.rb
- lib/avo/hosts/view_record_host.rb
- spec/dummy/app/avo/resources/fish_resource.rb
- spec/features/avo/required_takes_a_block_spec.rb
Fixes https://github.com/avo-hq/avo/issues/946
1. Go to the fish resource
2. notice that on the create screen the name is required
3. notice that on the edit screen the name is not required
> feature: required takes a block

- lib/avo/engine.rb
- lib/generators/avo/install_generator.rb
- spec/dummy/config/environments/development.rb
- spec/dummy/config/environments/test.rb
Fixes https://github.com/avo-hq/avo/issues/959
> fix: load user translation files not Avo's

- lib/avo/base_resource.rb
- lib/avo/concerns/model_class_constantized.rb
- spec/dummy/app/avo/resources/membership_resource.rb
- spec/system/avo/date_spec.rb
Fixes https://github.com/avo-hq/avo/issues/994
> fix: model class with encryption broken

- lib/avo/fields/key_value_field.rb
Fixes https://github.com/avo-hq/avo/issues/1014
1. use the steps in the ticket
> fix: key value labels missing

- app/controllers/avo/application_controller.rb
Fixes https://github.com/avo-hq/avo/issues/1030
Fixes https://github.com/avo-hq/avo/issues/1024
> fix: root_path breaks avo on community

- .github/workflows/reviewdog.yml
Fixes this error https://github.com/avo-hq/avo/runs/7280031752?check_suite_focus=true
> fix: standardrb v1.x

- .github/workflows/merge-message.yml
- .github/workflows/stale.yml
- RELEASE.MD
Improvements and automation for releases and PRs.
> chore: stale bot improvements; release messages

- app/components/avo/fields/file_field/edit_component.html.erb
- app/components/avo/fields/files_field/edit_component.html.erb
- lib/avo/fields/file_field.rb
- lib/avo/fields/files_field.rb
- spec/dummy/app/avo/resources/post_resource.rb
- spec/dummy/app/avo/resources/project_resource.rb
Fixes #1043
1. go to a post
1. Create new post
1. choose file button click
> feature: add accept option for file/files field

- .github/workflows/merge-message.yml
Fixes https://github.com/avo-hq/avo/runs/7305120885?check_suite_focus=true
> chore: pr message permissions fix

- app/components/avo/fields/belongs_to_field/autocomplete_component.html.erb
- app/components/avo/referrer_params_component.html.erb
- app/components/avo/views/resource_edit_component.rb
- app/components/avo/views/resource_index_component.rb
- app/controllers/avo/base_controller.rb
- lib/avo/base_resource.rb
- spec/features/avo/belongs_to_polymorphic_spec.rb
- spec/features/avo/belongs_to_spec.rb
- spec/features/avo/create_through_record_spec.rb
- spec/features/avo/has_many_field_spec.rb
- spec/features/avo/search_spec.rb
- spec/system/avo/belongs_to_spec.rb
- spec/system/avo/tabs_spec.rb
> Revert "chore: rename via_relation_class->via_resource_class"

- app/components/avo/index/ordering/button_component.rb
- app/controllers/avo/reorder_controller.rb
- app/helpers/avo/url_helpers.rb
- config/routes.rb
Fixes https://github.com/avo-hq/avo/issues/1040
1. The re-ordering feature should work on course links
> fix: order routes clash

- app/components/avo/views/resource_index_component.html.erb
- spec/features/avo/search_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1042
Fixes https://github.com/avo-hq/avo/pull/1049
Fixes https://github.com/avo-hq/avo/pull/1050
1. The resource search should work for course links and fish
> fix: search with namespaced models broken

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pr-labeler.yml
- app/controllers/avo/base_controller.rb
- lib/avo/base_resource.rb
- lib/avo/services/uri_service.rb
- spec/dummy/app/avo/actions/dummy_action.rb
- spec/features/avo/search_spec.rb
> chore: tweaks; pr-labeler; resource name; search spec improv

- app/helpers/avo/application_helper.rb
- app/views/avo/partials/_javascript.html.erb
- spec/dummy/config.ru
- spec/dummy/config/application.rb
Fixes https://github.com/avo-hq/avo/issues/1052
1. Recreate the steps in the ticket and the search should work
> fix: search broken with relative_url_root

- app/controllers/avo/application_controller.rb
- spec/dummy/app/views/home/index.html.erb
Improved the way to force the locale for a request from the [docs](https://guides.rubyonrails.org/i18n.html).
> refactor: better force locale

- lib/avo/base_action.rb
- lib/avo/base_resource.rb
- lib/avo/has_context.rb
Fixes https://github.com/avo-hq/avo/issues/1068
> feature: add path helpers to actions

- .github/ISSUE_TEMPLATE/bug_report.md
- app/components/avo/sidebar/link_component.rb
- app/controllers/avo/base_controller.rb
- lib/generators/avo/templates/tool/sidebar_item.tt
- spec/dummy/app/controllers/avo/tools_controller.rb
- spec/dummy/app/views/avo/sidebar/items/_custom_tool.html.erb
- spec/dummy/app/views/avo/sidebar/items/_dashboard.html.erb
- spec/dummy/app/views/avo/tools/custom_tool.html.erb
- spec/dummy/config/initializers/avo.rb
- spec/dummy/config/routes.rb
- spec/features/avo/app_spec.rb
- spec/features/avo/breadcrumbs_spec.rb
- spec/features/avo/custom_tools_spec.rb
- spec/features/avo/h_q_spec.rb
- spec/features/avo/license_tinkering_in_application_controller_spec.rb
- spec/system/avo/avo_collapsable_menus_spec.rb
Fixes an issue where paths were wrongly detected as internal.
> fix: external path detector

- app/assets/stylesheets/avo.css
- app/assets/stylesheets/css/sidebar.css
- app/components/avo/sidebar_component.html.erb
- app/controllers/avo/application_controller.rb
- app/javascript/js/controllers.js
- app/javascript/js/controllers/mobile_controller.js
- app/javascript/js/controllers/sidebar_controller.js
- app/views/avo/partials/_javascript.html.erb
- app/views/avo/partials/_navbar.html.erb
- app/views/layouts/avo/application.html.erb
- lib/avo.rb
- package.json
- spec/support/helpers.rb
- spec/system/avo/avo_sidebars_spec.rb
- yarn.lock
Adds the ability to hide the sidebar on desktop screens.
1. Step 1
1. Step 2
<details>
<summary>Details</summary>
</details>
> feature: hide sidebar on desktop

- lib/avo/concerns/has_html_attributes.rb
- spec/dummy/app/avo/resources/review_resource.rb
- spec/system/avo/nullable_field_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1088
> fix: overriden data attributes should take precendence

- CONTRIBUTING.MD
- app/assets/stylesheets/avo.css
- app/assets/stylesheets/css/scrollbar.css
- app/components/avo/sidebar_component.html.erb
- app/components/avo/tab_switcher_component.html.erb
- app/components/avo/views/resource_index_component.html.erb
- app/javascript/avo.js
- spec/dummy/app/avo/resources/fish_resource.rb
Before:
After:
1. Go to a fish
2. see the long list of tabs
3. make the screen smaller than the tabs
4. observe you can scroll them horizontally
> fix: multiple tabs flow out of the screen

- CONTRIBUTING.MD
- README.md
- app/components/avo/fields/common/gravatar_viewer_component.html.erb
- app/components/avo/fields/date_field/edit_component.html.erb
- app/components/avo/fields/date_time_field/edit_component.html.erb
- app/components/avo/sidebar_component.html.erb
- app/views/layouts/avo/application.html.erb
- lib/avo/fields/date_field.rb
- lib/avo/fields/field_extensions/has_include_blank.rb
- lib/avo/fields/key_value_field.rb
- lib/avo/licensing/h_q.rb
- lib/avo/menu/builder.rb
- lib/generators/avo/templates/initializer/avo.tt
- spec/dummy/app/avo/resources/person_resource.rb
- spec/dummy/app/avo/resources/post_resource.rb
- spec/dummy/app/avo/resources/review_resource.rb
- spec/dummy/app/avo/resources/spouse_resource.rb
- spec/dummy/app/avo/resources/team_resource.rb
- spec/dummy/app/models/post.rb
- spec/features/avo/resource_description_spec.rb
- tailwind.config.js
Some tweaks and clean up tasks.
> chore: misc tweaks

- lib/generators/avo/templates/initializer/avo.tt
Just corrected a spelling mistake in the comments
N/A
> Corrected a typo in avo.rb

- app/components/avo/views/resource_show_component.html.erb
- app/components/avo/views/resource_show_component.rb
https://github.com/avo-hq/avo/issues/1113
> fix: redirect back to parent if deleted from parent

- app/components/avo/resource_component.rb
- app/components/avo/views/resource_edit_component.html.erb
- app/components/avo/views/resource_index_component.rb
- app/components/avo/views/resource_show_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/895
> fix: act_on policy applyed on show and edit views

- .github/workflows/label-pr.yml
Fixes an issue where PRs submitted from forks were not properly labeled.
> fix: attempt to fix permissions for PR labeler

- app/components/avo/base_component.rb
- app/components/avo/resource_component.rb
- app/components/avo/views/resource_edit_component.rb
Fixes https://github.com/avo-hq/avo/issues/1117
> fix: cancel button path when creating from has many

- spec/dummy/app/avo/actions/release_fish.rb
- spec/features/avo/release_fish_spec.rb
This PR adds tests to an Avo Action. This has been [requested](https://twitter.com/coorasse/status/1562718775392145408) but users.
[Docs](https://docs.avohq.io/2.0/testing.html)
> chore: add testing for the release fish action

- .github/workflows/stale.yml
- README.md
> chore: update readme

- app/components/avo/filters_component.html.erb
- app/components/avo/filters_component.rb
- app/components/avo/views/resource_index_component.html.erb
Fixes # https://github.com/avo-hq/avo/issues/1118
> fix: reset filters keep current location

- app/components/avo/sidebar_component.html.erb
- app/controllers/avo/debug_controller.rb
- app/views/avo/debug/index.html.erb
- app/views/avo/sidebar/_license_warnings.html.erb
- lib/avo/app.rb
- lib/avo/licensing/h_q.rb
- lib/avo/licensing/license_manager.rb
Fixes https://github.com/avo-hq/avo/issues/1143
1. Step 1
1. Step 2
> refactor: ensure better hq error handling

- app/components/avo/index/resource_table_component.rb
Fixes https://github.com/avo-hq/avo/issues/1196
> fix: to_sql crashes for models that live in different schemas

- app/views/layouts/avo/application.html.erb
- spec/dummy/app/javascript/avo.custom.js
- spec/dummy/app/views/avo/partials/_head.html.erb
> chore: minor assets refactor

- lib/generators/avo/templates/initializer/avo.tt
> chore: minor branding config fix

- app/views/layouts/avo/application.html.erb
- lib/avo/configuration/branding.rb
- lib/generators/avo/tailwindcss/install_generator.rb
- lib/generators/avo/templates/initializer/avo.tt
- lib/generators/avo/templates/tailwindcss/Procfile.dev
- lib/tasks/tailwindcss_rails.rake
Fixes a few small issues with the new custom asset commands.
> fix: minor fiexs around the asset settings

- app/components/avo/index/grid_item_component.html.erb
- app/components/avo/index/grid_item_component.rb
- app/components/avo/index/resource_grid_component.html.erb
- app/components/avo/index/resource_grid_component.rb
- app/components/avo/views/resource_index_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/1233
> fix: has_and_belongs_to_may grid view

- app/components/avo/fields/has_one_field/show_component.html.erb
- app/components/avo/fields/has_one_field/show_component.rb
- spec/dummy/app/policies/user_policy.rb
- spec/features/avo/create_has_one_spec.rb
Fixes https://github.com/avo-hq/avo/issues/659
> feature: create button on has one association

- app/components/avo/sidebar/item_switcher_component.html.erb
- app/components/avo/sidebar/link_component.html.erb
- app/components/avo/sidebar/link_component.rb
- lib/avo/menu/base_item.rb
- lib/avo/menu/builder.rb
- spec/dummy/config/initializers/avo.rb
Fixes https://github.com/avo-hq/avo/issues/1231
[Prerelease](https://rubygems.org/gems/avo/versions/2.15.3.pre.1.data.attrs.to.sidebar.items)
> feature: add data attributes to sidebar items

- app/components/avo/fields/trix_field/edit_component.html.erb
- app/controllers/avo/actions_controller.rb
- app/controllers/avo/application_controller.rb
- app/views/avo/actions/show.html.erb
- lib/avo/base_action.rb
- lib/avo/base_resource.rb
- lib/avo/fields/base_field.rb
- lib/avo/fields/belongs_to_field.rb
- spec/dummy/app/avo/actions/download_file.rb
- spec/dummy/app/avo/actions/release_fish.rb
- spec/dummy/app/avo/filters/photo_filter.rb
- spec/features/avo/release_fish_spec.rb
- spec/system/avo/has_many_spec.rb
- spec/system/avo/select_all_spec.rb
I'd like to use the trix field in an action, but it does not work right now because the resource does not have a model set by the actions controller. I've changed it to explicitly hydrated the resource like the resources controller does.
1. Check that a pre-existing action still works correctly
2. Create a new action that has a trix field and confirm that this works without errors.
> Made sure model is set on the resource for actions

- app/components/avo/base_component.rb
- app/controllers/avo/base_controller.rb
- spec/dummy/app/models/spouse.rb
- spec/system/recursive_resources_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1250
1. Do the steps in the repro repo but in the dummy app with a Person and a Spouse
> fix: recursive resources broken

- app/javascript/js/controllers/fields/date_field_controller.js
Fixes https://github.com/avo-hq/avo/issues/1256
1. Do the steps in the issue and make sure the filed works
> fix: date time broken on back action

- spec/dummy/config/initializers/avo.rb
> refactor: moved some things around in the initializer

- app/components/avo/base_component.rb
Fixes https://github.com/avo-hq/avo/issues/1250
> fix: recursive resources duplicated hydration

- .github/workflows/test.yml
We want to help GA run the tests faster and shorten the feedback loop, so we're going to try and separate the types of tests in different jobs.
> chore: separate tests

- README.md
> Fix a typo on Readme Doc

- app/components/avo/actions_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/1245
> fix: disable icon on disabled action

- lib/avo/reloader.rb
- lib/generators/avo/templates/initializer/avo.tt
Fixes a generator typo and fixes styling for a class.
> chore: minor style tweak

- lib/generators/avo/templates/locales/avo.nb.yml
- lib/generators/avo/templates/locales/avo.nn.yml
Fixes minor Norweigan translations.
> fix: Norwegian translations

- Gemfile.lock
- avo.gemspec
- gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
- gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
- gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
- gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
- gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
- gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
Fixes https://github.com/avo-hq/avo/issues/1270
> chore: unlock view_component

- Gemfile.lock
- gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
- gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
- gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
- gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
- gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
- gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
Fixes [this](https://nvd.nist.gov/vuln/detail/CVE-2022-2309) CVE
> chore: update nokogiri

- app/components/avo/index/resource_table_component.html.erb
- app/components/avo/panel_component.html.erb
- app/components/avo/views/resource_index_component.html.erb
- app/components/avo/views/resource_show_component.html.erb
Fixes an issue with shadows we introduced [here](https://github.com/avo-hq/avo/pull/1345).
> refactor: restore panel shadow and overflow

- app/controllers/avo/application_controller.rb
Fixes https://github.com/avo-hq/avo/issues/1367
Follow the steps in the issue.
> fix: include pundit if available

- app/components/avo/base_component.rb
- app/components/avo/fields/index_component.rb
- app/components/avo/index/grid_item_component.rb
- app/components/avo/index/resource_controls_component.rb
- app/components/avo/index/table_row_component.html.erb
- db/factories.rb
- lib/avo/base_resource.rb
- lib/avo/fields/has_base_field.rb
- spec/dummy/app/avo/resources/person_resource.rb
- spec/dummy/app/avo/resources/sibling_resource.rb
- spec/dummy/app/controllers/avo/siblings_controller.rb
- spec/dummy/app/models/sibling.rb
- spec/dummy/db/seeds.rb
- spec/features/avo/link_to_child_resource_spec.rb
- spec/features/avo/select_field_spec.rb
Single table inheritance  support. 
This PR implement a new field option `link_to_child_resource` to allow 
- configuration of which resource should be used for any has_many field.
- configuration at the resource level 
set this field option to true to enable child resources for a has_many field 
```ruby 
field :relatives, as: :has_many, link_to_child_resource: true 
```
set this field option to true to enable child resources for a resource
```ruby 
class PersonResource < Avo::BaseResource
self.link_to_child_resource = true
self.authorization_policy= SomePolicy
....
end
```
An example is available in the dummy app:
https://github.com/avo-hq/avo/blob/582caa726faf81bd2a7abccd61326ea34f5dd3c0/spec/dummy/app/avo/resources/person_resource.rb#L16
Assuming relatives is an association of peoples …
> feature: Extend field API with link_to_child_resource attribute

- lib/avo/fields/base_field.rb
Fixes #1370
1. Step 1
1. Step 2
> fix: readonly vulnerability

- app/components/avo/resource_component.rb
- lib/avo/sidebar.rb
Fixes #1353
1. Step 1
1. Step 2
> fix: sidebar field visibility block

- app/helpers/avo/application_helper.rb
Fixes https://github.com/avo-hq/avo/issues/1386
> fix: malformed root url for javascript

- app/components/avo/actions_component.html.erb
- app/components/avo/actions_component.rb
- app/components/avo/views/resource_show_component.html.erb
- spec/dummy/app/avo/resources/fish_resource.rb
- spec/features/avo/custom_resource_controls_spec.rb
Fix the issue of showing custom label for actionlist
Fixes #1330
> fix: issue of showing custom label for actionlist

- app/components/avo/fields/has_one_field/show_component.rb
Fixes Has one filed nil exception 
The wrong resource name was assigned instead of the model class name 
> Fix nil exception , wrong class name was assigned

- Gemfile
- Gemfile.lock
- lib/generators/avo/templates/resource/controller.tt
> chore: remove comment from tempalte file and remove manifester gem

- Gemfile
- Gemfile.lock
- gemfiles/rails_6.0_ruby_3.0.3.gemfile
- gemfiles/rails_6.0_ruby_3.1.0.gemfile
- gemfiles/rails_6.1_ruby_3.0.3.gemfile
- gemfiles/rails_6.1_ruby_3.1.0.gemfile
- gemfiles/rails_7.0_ruby_3.0.3.gemfile
- gemfiles/rails_7.0_ruby_3.1.0.gemfile
Fixes an issue where building for rubygems fails.
> chore: add rails to dummy deps

- app/components/avo/index/resource_table_component.rb
- app/controllers/avo/actions_controller.rb
- app/javascript/js/controllers/item_select_all_controller.js
Fixes #1255
1. Step 1
1. Step 2
> fix: select all when query can't be converted to_sql

- app/controllers/avo/application_controller.rb
- app/controllers/avo/associations_controller.rb
- app/controllers/avo/base_controller.rb
- lib/avo/base_action.rb
- lib/avo/base_resource.rb
- lib/avo/filters/base_filter.rb
- lib/avo/hosts/visibility_host.rb
Fixes #1444
1. Step 1
1. Step 2
> fix: resource getting wrong model

- app/controllers/avo/base_controller.rb
Fixes #1467
1. Step 1
1. Step 2
> fix: flash messages

- app/components/avo/fields/belongs_to_field/edit_component.rb
- app/components/avo/fields/boolean_field/edit_component.html.erb
- app/components/avo/fields/boolean_group_field/edit_component.html.erb
- app/components/avo/fields/code_field/edit_component.html.erb
- app/components/avo/fields/country_field/edit_component.html.erb
- app/components/avo/fields/date_field/edit_component.html.erb
- app/components/avo/fields/date_time_field/edit_component.html.erb
- app/components/avo/fields/edit_component.rb
- app/components/avo/fields/external_image_field/edit_component.html.erb
- app/components/avo/fields/file_field/edit_component.html.erb
- app/components/avo/fields/files_field/edit_component.html.erb
- app/components/avo/fields/has_one_field/show_component.html.erb
- app/components/avo/fields/markdown_field/edit_component.html.erb
- app/components/avo/fields/markdown_field/show_component.html.erb
- app/components/avo/fields/number_field/edit_component.html.erb
- app/components/avo/fields/password_field/edit_component.html.erb
- app/components/avo/fields/progress_bar_field/edit_component.html.erb
- app/components/avo/fields/select_field/edit_component.html.erb
- app/components/avo/fields/show_component.rb
- app/components/avo/fields/status_field/edit_component.html.erb
- app/components/avo/fields/tags_field/edit_component.html.erb
- app/components/avo/fields/text_field/edit_component.html.erb
- app/components/avo/fields/textarea_field/edit_component.html.erb
- app/components/avo/fields/time_field/edit_component.html.erb
- app/components/avo/fields/trix_field/edit_component.html.erb
- lib/avo/fields/base_field.rb
- lib/avo/fields/concerns/is_disabled.rb
- lib/generators/avo/templates/field/components/edit_component.html.erb.tt
- spec/dummy/app/components/avo/fields/color_picker_field/edit_component.html.erb
Fixes https://github.com/avo-hq/avo/discussions/1458
1. Step 1
1. Step 2
> feature: add disabled option

- spec/dummy/app/views/avo/resource_tools/_nested_fish_reviews.html.erb
> chore: minor refactor to nested  fish review

- spec/dummy/app/views/avo/resource_tools/_nested_fish_reviews.html.erb
Really fix the previous PR issue.
> chore: minor refactor to nested fish review

- app/controllers/avo/associations_controller.rb
- spec/dummy/app/policies/team_policy.rb
- spec/dummy/app/policies/user_policy.rb
- spec/features/avo/authorization_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1488
1. Use the steps from the issue
> fix: valid association authorization scope

- lib/avo/services/authorization_service.rb
Fixes https://github.com/avo-hq/avo/issues/1466#issuecomment-1332316631
> refactor: allow nil user in authorization service

- app/controllers/avo/search_controller.rb
The latest versions of avo introduced a regression for my app, where search would raise the following error:
ActiveRecord::StatementInvalid (PG::UndefinedFunction: ERROR:  function count(people, text) does not exist
LINE 1: SELECT COUNT(DISTINCT people.*, LOWER(UNACCENT(people...
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
):
avo (2.21.0) app/controllers/avo/search_controller.rb:54:in `search_resource'
avo (2.21.0) app/controllers/avo/search_controller.rb:34:in `block in search_resources'
avo (2.21.0) app/controllers/avo/search_controller.rb:28:in `map'
avo (2.21.0) app/controllers/avo/search_controller.rb:28:in `search_resources'
avo (2.21.0) app/controllers/avo/search_controller.rb:21:in `show'
This happens because I'm doing …
> Remove select from count in search

- app/helpers/avo/application_helper.rb
- app/javascript/js/controllers/search_controller.js
Fixes https://github.com/avo-hq/avo/issues/1502
> fix: JS root path without query param

- app/components/avo/fields/progress_bar_field/edit_component.html.erb
- app/components/avo/fields/progress_bar_field/edit_component.rb
- app/javascript/js/controllers.js
- app/javascript/js/controllers/fields/progress_bar_field_controller.js
- Fixes progress bar display value
- I prefer to add a manual ID for the input because rails API to define the input ID is hard
New code progress bar html code generated from Projects in dummy app 
```html
<div class="field-wrapper relative flex flex-col flex-grow pb-2 md:pb-0 leading-tight min-h-14 field-wrapper-layout-inline md:flex-row md:items-center field-wrapper-size-regular field-width-regular   " style=" " data-field-id="progress" data-field-type="progress_bar" data-resource-edit-target="progressProgressBarWrapper">
<div class="h-full  md:pt-0 md:h-14  pt-4 flex self-start items-center  w-48  md:w-64  px-6 uppercase font-semibold text-gray-500 text-sm" data-slot="label">
<label for="project_progress">Progress</label>
</div>
<div class="flex-1 flex flex-row md:min-h-inherit py-2 …
```
> :bug: Fixes progress bar display value js

- app/helpers/avo/application_helper.rb
Fixes https://github.com/avo-hq/avo/issues/1523
> feature: enable using field components without a form object

- lib/avo/fields/belongs_to_field.rb
Fixes https://github.com/avo-hq/avo/issues/1521
> fix: belongs to (non/)searchable uses same scoping

- lib/generators/avo/resource_generator.rb
> fix: resource generator several fixes

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.MD
- spec/dummy/app/avo/resources/post_resource.rb
- spec/dummy/app/helpers/home_helper.rb
- spec/dummy/config/initializers/avo.rb
This PR only adds an example on how to extend the `BaseField` class in order to have all the helper methods.
> chore: add helper example

- .github/PULL_REQUEST_TEMPLATE.md
- lib/avo/base_card.rb
Fixes https://github.com/avo-hq/avo/issues/1577
> refactor: enable card intermediate classes

- app/views/avo/partials/_footer.html.erb
- lib/avo/engine.rb
- spec/dummy/app/avo/concerns/application_controller_extensions.rb
- spec/dummy/app/avo/concerns/field_extensions.rb
- spec/dummy/app/models/current.rb
- spec/dummy/app/policies/team_policy.rb
- spec/dummy/config/initializers/avo.rb
- spec/features/avo/app_spec.rb
- spec/features/avo/authorization_spec.rb
- spec/helpers/test_buddy.rb
Moved the extension concerns to their own file.
> refactor: add Avo extensions and TestBuddy

- Gemfile
- Procfile
- bin/prod
- lib/avo/concerns/has_fields.rb
- lib/avo/concerns/visible_items.rb
- spec/dummy/config/database.yml
Fixes https://github.com/avo-hq/avo/issues/1586
Fixes https://github.com/avo-hq/avo/issues/1540
> fix: VisibleItems view gets wrongly memoized

- app/views/avo/partials/_footer.html.erb
> fix: remove current from footer

- README.md
Greenhats has been with us from the beginning.
They are working in the IT security / pen-testing industry and the decision to choose avo was also made by "the clean, secure code and lots of security implementations such as pundit".
Company: Greenhats
Website: https://greenhats.com
Thank you for your support @FLX-0x00!
> Add greenhats as a sponsor

- spec/dummy/app/avo/resources/user_resource.rb
- spec/dummy/config/environments/test.rb
Uses [this](https://twitter.com/5katkov/status/1628331293967810561) technique to make the tests faster.
> chore: create unlogged tables in test env

- .github/release-drafter.yml
- lib/avo/fields/date_field.rb
- spec/dummy/app/avo/resources/post_resource.rb
- spec/dummy/app/javascript/avo.custom.js
Enables the date field to work with strings.
> feature: date field support for string columns

- app/components/avo/fields/common/single_file_viewer_component.html.erb
- app/views/layouts/avo/application.html.erb
Fixes https://github.com/avo-hq/avo/issues/1645
> fix: attachment delete action does not respond

- app/components/avo/fields/belongs_to_field/edit_component.rb
- app/components/avo/fields/has_one_field/show_component.rb
- app/components/avo/referrer_params_component.html.erb
- app/components/avo/views/resource_index_component.rb
- app/controllers/avo/base_controller.rb
- lib/avo/base_resource.rb
- lib/avo/fields/has_one_field.rb
- spec/dummy/app/models/team.rb
- spec/dummy/app/models/user.rb
- spec/features/avo/create_has_one_spec.rb
Fixes https://github.com/avo-hq/avo/issues/1648
1. Go to teams
1. Click on create new admin
2. See the new user added and assigned as an admin for that team
> fix: failing to find record on has_one associations

- lib/generators/avo/resource_generator.rb
Fixes #1658
1. Step 1
1. Step 2
> fix: resource generator enum model class naming

- .github/workflows/codeball.yml
> chore: add codeball action

- Gemfile.lock
- gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
- gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
- gemfiles/rails_6.0_ruby_3.2.1.gemfile.lock
- gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
- gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
- gemfiles/rails_6.1_ruby_3.2.1.gemfile.lock
- gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
- gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
- gemfiles/rails_7.0_ruby_3.2.1.gemfile.lock
> security: update nokogiri

- lib/avo/configuration.rb
- lib/generators/avo/templates/initializer/avo.tt
> Revert "refactor: change default as false on cache_resources_on_index_view"

- lib/generators/avo/tailwindcss/install_generator.rb
- lib/generators/avo/templates/tailwindcss/Procfile.dev
The generator was broken. The wrong commands were being generated.
> fix: tailwindcss generator

- app/components/avo/index/resource_map_component.rb
- spec/dummy/app/avo/resources/city_resource.rb
Adds a better API for the `map_view` `record_marked` option.
> refactor: use Host for map view proc

- lib/avo/app.rb
Fixes an issue where the file store was improperly initialized.
> refactor: proper file store init

- lib/avo/app.rb
- lib/avo/concerns/fetches_things.rb
> chore: better memory store lookup

- lib/generators/avo/install_generator.rb
Fixes https://github.com/avo-hq/avo/issues/1719
1. Step 1
1. Step 2
> feature: when installing Avo detect if User model exists and create a resource for it

- lib/avo/base_action.rb
Fixes https://github.com/avo-hq/avo/issues/1754
> fix: default field option as a block in actions

- .github/ISSUE_TEMPLATE/blank_issue.md
- .github/ISSUE_TEMPLATE/bug_report.md
- app/components/avo/panel_component.html.erb
Fixes https://github.com/avo-hq/avo/issues/1767
> fix: sidebar broken on mobile view

- lib/avo/fields/belongs_to_field.rb
Fixes https://github.com/avo-hq/avo/issues/1778
> fix: broken non-poly belongs to

- app/controllers/avo/actions_controller.rb
Fixes an issue where multiple unpermitted param statements in the logs.
Fixes https://github.com/yshmarov/superails/issues/44
> fix: remove unpermitted param from action run method

- .editorconfig
- lib/avo/app.rb
- lib/avo/licensing/h_q.rb
- lib/avo/licensing/license.rb
- lib/avo/licensing/license_manager.rb
- lib/avo/licensing/nil_license.rb
- spec/features/avo/h_q_spec.rb
- spec/system/avo/filters/filters_spec.rb
It just saves a lot of resources.
> refactor: stop checking the license if in test env

- app/controllers/avo/base_controller.rb
- lib/avo/concerns/has_fields.rb
Fixes https://github.com/avo-hq/avo/issues/1823
> fix: updatable row inputs

- spec/dummy/app/avo/resources/attachment_resource.rb
- spec/dummy/app/avo/resources/post_resource.rb
- spec/dummy/app/avo/resources/project_resource.rb
- spec/dummy/app/controllers/avo/attachments_controller.rb
This PR adds the demo Attachment resource to the dummy app.
> chore: add the attachment resource as a demo

- app/components/avo/tab_switcher_component.rb
- lib/avo/fields/field_extensions/visible_in_different_views.rb
- lib/avo/tab.rb
- spec/system/avo/tabs_spec.rb
Fixes #1812
Tab header was wrongly showing buttons to not visible tabs
1. Step 1
1. Step 2
> fix: tab visibility

- app/controllers/avo/attachments_controller.rb
Fixes https://github.com/avo-hq/avo/issues/1582#issuecomment-1637505744
Fixes https://github.com/greenhats-gmbh/training.greenhats.com/issues/73
> fix: trix attachment broken for GCP

- yarn.lock
> chore: yarn audit fix

- app/components/avo/index/resource_controls_component.rb
- app/components/avo/resource_component.rb
- app/controllers/avo/associations_controller.rb
- spec/dummy/app/models/course/link.rb
- spec/dummy/app/models/person.rb
- spec/dummy/app/models/project.rb
- spec/dummy/app/models/spouse.rb
- spec/dummy/app/models/team.rb
- spec/dummy/app/models/user.rb
> fix: don't render detach button when can't detach record

- app/controllers/avo/actions_controller.rb
- spec/dummy/app/avo/actions/sub/dummy_action.rb
Fixes https://github.com/avo-hq/avo/issues/1864
> fix: action view set to new

- app/components/avo/modal_component.html.erb
update css of dialogs so they scroll if larger that the screen height
Fixes #1866
> make large dialogs scroll

- lib/avo/app.rb
Just a couple comment typo fixes.
> Avo typo fixes

- README.md
[Current demo link](https://avodemo.herokuapp.com/) points to a down Heroku app, updated with what I found [here](https://avohq.io/).
1. Check if the new link is ok.
> fix: broken readme demo link

- app/components/avo/field_wrapper_component.html.erb
- app/components/avo/fields/common/files/view_type/grid_item_component.html.erb
- spec/dummy/app/avo/resources/post_resource.rb
Fixes #1948 
1. Step 1
1. Step 2
> fix: variant resize image

- lib/avo/app.rb
Adds support for [`solid_cache`](https://github.com/rails/solid_cache)
Fixes #1971
> improvement: solid cache support

- spec/dummy/app/avo/actions/test/no_confirmation_redirect.rb
- spec/dummy/app/avo/resources/user_resource.rb
- spec/system/avo/actions_spec.rb
Fixes actions spec and remove `class_eval`
> chore: fix actions spec

- Gemfile.lock
- app/components/avo/field_wrapper_component.rb
- app/controllers/avo/actions_controller.rb
- app/views/avo/actions/show.html.erb
- lib/avo/base_action.rb
- lib/avo/base_resource.rb
- lib/avo/concerns/has_action_stimulus_controllers.rb
- lib/avo/concerns/has_resource_stimulus_controllers.rb
- lib/avo/fields/base_field.rb
- lib/avo/fields/concerns/has_html_attributes.rb
- spec/dummy/app/avo/actions/show_current_time.rb
- spec/dummy/app/avo/resources/course.rb
- spec/dummy/app/javascript/avo.custom.js
- spec/dummy/app/javascript/avo_custom/city_in_country_controller.js
- spec/dummy/app/models/course.rb
- spec/system/avo/stimulus_spec.rb
Copy of https://github.com/avo-hq/avo/pull/2039 authored by @bryszard
Slightly modified to apply on avo 3
> feature: assign stimulus to actions

- .eslintrc.json
- package.json
- yarn.lock
> chore: update eslint

- app/views/avo/home/_actions.html.erb
- app/views/avo/home/_dashboards.html.erb
- app/views/avo/home/_filters.html.erb
- app/views/avo/home/_resources.html.erb
- lib/avo/resources/resource_manager.rb
- spec/features/avo/resource_missing_model_spec.rb
> fix: links from 2.0 to 3.0

- lib/avo/concerns/has_items.rb
Fixes tab visibility on forms.
> fix: tabs visibility

- Gemfile
- avo.gemspec
- gemfiles/rails_6.0_ruby_3.0.3.gemfile
- gemfiles/rails_6.0_ruby_3.2.2.gemfile
- gemfiles/rails_6.1_ruby_3.0.3.gemfile
- gemfiles/rails_6.1_ruby_3.2.2.gemfile
- gemfiles/rails_7.0_ruby_3.0.3.gemfile
- gemfiles/rails_7.0_ruby_3.2.2.gemfile
- gemfiles/rails_7.1_ruby_3.0.3.gemfile
- gemfiles/rails_7.1_ruby_3.2.2.gemfile
Fixes https://github.com/avo-hq/avo/issues/2192
> chore: unlock turbo_power version lock

- .github/release-drafter.yml
- spec/system/avo/date_time_fields/date_spec.rb
Fixes a flaky test
1. Step 1
1. Step 2
> fix: flaky date test

- app/javascript/js/custom-stream-actions.js
#2196 was merged and released by mistake. It was reverted on #2259 but not entirely. This PR revert what's missing.
> fix: custom_streams_actions.js

- config/initializers/pagy.rb
- lib/generators/avo/templates/locales/avo.ja.yml
- spec/features/avo/generators/locales_generator_spec.rb
Hi!
I am developing using Avo in Japan.
I created a locale file for Japanese. 
Thank you for developing such a great product.
> create ja locale

- app/components/avo/views/resource_index_component.rb
- lib/generators/avo/templates/scope.tt
Enables https://github.com/avo-hq/avo/discussions/2274
Related PR: https://github.com/avo-hq/avo-pro/pull/56
1. Try the recipe code
> chore: expose query to scopes

- Gemfile
- Gemfile.lock
- gemfiles/rails_6.0_ruby_3.0.3.gemfile
- gemfiles/rails_6.0_ruby_3.2.2.gemfile
- gemfiles/rails_6.1_ruby_3.0.3.gemfile
- gemfiles/rails_6.1_ruby_3.2.2.gemfile
- gemfiles/rails_7.0_ruby_3.0.3.gemfile
- gemfiles/rails_7.0_ruby_3.2.2.gemfile
- gemfiles/rails_7.1_ruby_3.0.3.gemfile
- gemfiles/rails_7.1_ruby_3.2.2.gemfile
We are using [spektr](https://spektrhq.com/).
> chore: remove brakeman

- app/views/avo/partials/_logo.html.erb
- app/views/avo/partials/_navbar.html.erb
Fixes https://github.com/avo-hq/avo/issues/2060
> fix: bad navbar display on firefox

- .github/workflows/test-tailwindcss-integration.yml
Improves our testing strategy.
> chore: add tailwindcss integration test

- Appraisals
I accidentally remove the appraisals file.
> chore: bring back appraisals file

- lib/avo/fields/concerns/has_html_attributes.rb
- lib/avo/html/builder.rb
- lib/tasks/avo_tasks.rake
- scripts/export-tailwind-safelist.js
- spec/dummy/app/avo/resources/project.rb
- spec/dummy/config/environments/test.rb
Fixes https://github.com/avo-hq/avo/issues/2390
> fix: return valid attributes for html options

- lib/avo/tools/tool_manager.rb
- spec/dummy/app/avo/actions/export_csv.rb
Adds a new method on the tool manager.
> refactor: tool-manager-tweaks

- lib/tasks/tailwindcss_rails.rake
Fixes https://github.com/avo-hq/avo/issues/2351
> fix: double defined constanta in CI

- .github/workflows/remove-old-artifacts.yml
I'm getting annoying emails every night because I have the repo forked
Only run remove artifacts in the github repo is avo's main repo
> 💚  Turn off remove old artifacts

- lib/avo/configuration/branding.rb
- scripts/export-tailwind-safelist.js
We updated the default color palette so the colors are more variate and easier to distinguish.
> chore: new dashboard colors

- app/views/avo/associations/new.html.erb
- spec/features/avo/fields_methods_for_views_spec.rb
Fixes #2403
Related to #2403 (fixed detach) but this PR fixes attach action
1. Step 1
1. Step 2
> fix: attach when using *_fields API

- app/components/avo/panel_component.html.erb
- app/components/avo/panel_component.rb
- app/components/avo/views/resource_index_component.html.erb
- app/components/avo/views/resource_index_component.rb
- lib/avo/fields/concerns/reload_icon.rb
- lib/avo/fields/has_base_field.rb
- spec/dummy/app/avo/resources/team.rb
> Change reload_button to reloadable

- package.json
- yarn.lock
Fixes an issue that appear when updating `@yaireo/tagify` to versions bigger than `4.18.3`
This issue seems to be present only on apps that have done css tailwind integration.
We're working on a permanent solution but until then `@yaireo/tagify` will be reverted to version `4.18.3`
This happens on versions bigger than `4.18.3`
[21.webm](https://github.com/avo-hq/avo/assets/69730720/b930d7c9-7d6f-41f4-a727-df5dfe8d20ce)
> fix: tags with custom tailwind integration issue

- app/components/avo/fields/hidden_field/edit_component.html.erb
Implements a fix from avo3 https://github.com/avo-hq/avo/pull/2078
> fix: actions hidden fields value not being passed

- app/components/avo/fields/common/files/view_type/grid_item_component.html.erb
- avo.gemspec
- spec/dummy/app/avo/resources/post.rb
Fixes https://github.com/avo-hq/avo/issues/2473
> fix: image in file field stretched

- app/components/avo/filters_component.rb
- app/helpers/avo/resources_helper.rb
- app/javascript/js/controllers/filter_controller.js
- lib/avo/concerns/filters_session_handler.rb
- lib/avo/filters/base_filter.rb
- spec/dummy/db/seeds.rb
- spec/rails_helper.rb
- spec/system/avo/filters/filters_spec.rb
Fixes https://github.com/avo-hq/avo/issues/2270
Upgrade guide (breaking change): https://docs.avohq.io/3.0/upgrade.html
> fix: standard and dynamic filters work together

- lib/tasks/avo_tasks.rake
Reported here https://discord.com/channels/740892036978442260/740892037640880180/1212166791116234812
Fixes the `avo:update` task
> fix: avo:update task

- app/views/avo/partials/_header.html.erb
- spec/dummy/app/views/avo/partials/_header.html.erb
Fixes https://github.com/avo-hq/avo/pull/2508/files#r1508825112
> fix: header partial

- lib/generators/avo/templates/resource/controller.tt
- spec/dummy/app/controllers/avo/active_record_attachments_controller.rb
- spec/dummy/app/controllers/avo/compact_users_controller.rb
fix Avo version referenced in the code
1. Step 1
1. Step 2
> fix: doc version

- app/components/avo/sidebar_component.html.erb
Fixes #2557 
Revert regression introduced by #2507
> fix: routes

- app/views/layouts/avo/application.html.erb
- lib/avo/plugin_manager.rb
Adds a string with the current plugins to the layout in order to debug some issues easier.
> chore: add plugins to the layout

- app/controllers/avo/base_controller.rb
One breadcrumb was missing in associations.
> chore: add missing breadcrumb

- app/controllers/avo/search_controller.rb
Fixes #2535 
Use `to_s` on the search title before trying to highlight it.
> fix: search item title

- lib/avo/fields/boolean_group_field.rb
Fixes #2566. Inspired by the implementation in select box, I have no idea what is happening under the hood :) If I should add any tests / edit the dummy app as well, just say so.
> Enable boolean group computed options

- app/components/avo/fields/textarea_field/show_component.html.erb
- spec/dummy/app/avo/resources/comment.rb
- spec/dummy/app/avo/resources/photo_comment.rb
- spec/system/avo/date_time_fields/date_time_eastern_spec.rb
- spec/system/avo/date_time_fields/date_time_utc_spec.rb
- spec/system/avo/date_time_fields/date_time_western_spec.rb
> Render text area newlines

- Gemfile
- Gemfile.lock
- spec/dummy/app/avo/resources/comment.rb
- spec/dummy/app/avo/resources/event.rb
- spec/dummy/app/models/event.rb
Preparing for https://rubygems.org/gems/avo-record_link_field
> chore: prepare for record_link field

- app/controllers/avo/actions_controller.rb
- app/controllers/avo/application_controller.rb
- app/controllers/avo/associations_controller.rb
- spec/system/avo/reload_button_spec.rb
Fixes action layout when not turbo request (same approach as associations)
> fix: actions layout

- app/components/avo/sidebar/base_item_component.rb
- app/components/avo/sidebar/group_component.html.erb
- app/components/avo/sidebar/section_component.html.erb
- app/javascript/js/controllers/menu_controller.js
This brings a nice quality of life improvement.
> feature: add sidebar collapse animation

- app/components/avo/resource_component.rb
- app/controllers/avo/base_controller.rb
- lib/avo/concerns/hydration.rb
- lib/avo/fields/belongs_to_field.rb
- lib/avo/resources/resource_manager.rb
Trying out a few performance improvements.
1. Step 1
1. Step 2
> performance: memoize a few things

- gemfiles/rails_6.1_ruby_3.1.4.gemfile
- gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
- gemfiles/rails_6.1_ruby_3.2.2.gemfile
- gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock
- gemfiles/rails_6.1_ruby_3.3.0.gemfile
- gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
- gemfiles/rails_7.1_ruby_3.1.4.gemfile
- gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
- gemfiles/rails_7.1_ruby_3.2.2.gemfile
- gemfiles/rails_7.1_ruby_3.2.2.gemfile.lock
- gemfiles/rails_7.1_ruby_3.3.0.gemfile
- gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
I forgot to add it to the `Gemfiles`
> chore: add record_link field to gemfile

- lib/avo.rb
Eager load `Avo::Actions` namespace only if defined.
> fix: actions eager loader

- app/components/avo/index/resource_controls_component.html.erb
- app/components/avo/views/resource_index_component.html.erb
- tailwind.preset.js
Fixes https://github.com/avo-hq/avo/issues/2739
> fix: resource controls spacing issue

- .github/release-drafter.yml
- lib/avo.rb
Fixes https://github.com/avo-hq/avo/issues/2748
> chore: require ostruct

- app/components/avo/base_component.rb
- app/controllers/avo/associations_controller.rb
- app/controllers/avo/base_controller.rb
- app/controllers/avo/search_controller.rb
> security: prevent SQL injection in sorting param

- app/javascript/js/controllers/sidebar_controller.js
Fixes https://github.com/avo-hq/avo/issues/2728
> fix: active sidebar menu js error with custom menu

- bin/dev
- spec/dummy/config/environments/development.rb
I don't think we need this symlink here with the single repo.
> chore: remove symlink from dev script

- app/components/avo/fields/belongs_to_field/edit_component.html.erb
> Add data polymorphic type

- app/components/avo/index/resource_controls_component.rb
> Update svg for eye

- app/components/avo/actions_component.html.erb
- app/components/avo/actions_component.rb
- app/components/avo/resource_component.rb
- lib/avo/resources/controls/actions_list.rb
Fixes #[2801](https://github.com/avo-hq/avo/issues/2801)
1. Step 1
1. Step 2
> Add icon to actions_list

- app/components/avo/fields/textarea_field/edit_component.html.erb
- app/javascript/js/application.js
- package.json
- yarn.lock
Added autogrow functionality to textarea fields.
Fixes https://github.com/avo-hq/avo/issues/2795
https://github.com/avo-hq/avo/assets/83423182/234483ab-9042-404d-8364-a55f829e2663
1. Step 1
1. Step 2
> Add textarea autogrow

- app/components/avo/index/grid_item_component.html.erb
- app/components/avo/index/resource_grid_component.html.erb
- app/components/avo/index/resource_table_component.html.erb
- app/components/avo/index/table_row_component.html.erb
- app/helpers/avo/resources_helper.rb
This brings a refactor which will help us do some other work down the line.
Related: https://github.com/avo-hq/avo-pro/pull/72
> refactor: reorder data attributes

- Gemfile
> fix: gemfile bad quotes

- app/components/avo/alert_component.html.erb
- lib/avo/configuration.rb
- lib/generators/avo/templates/initializer/avo.tt
- spec/dummy/config/initializers/avo.rb
> Add alert_dismiss_time to configuration

- app/components/avo/actions_component.rb
- lib/avo/resources/controls/actions_list.rb
Fixes [# (issue)](https://github.com/avo-hq/avo/issues/2835)
1. Step 1
1. Step 2
> fix: Add default icon for action list

- spec/dummy/db/seeds.rb
Well, Unsplash is [down](https://source.unsplash.com) so just a little rescue in the seeds script…
> Make database seed work if Unsplash down

- lib/avo/fields/base_field.rb
- spec/dummy/app/avo/resources/event.rb
- spec/features/avo/fields_meta_spec.rb
Fixes https://github.com/avo-hq/avo/issues/2143
> feature: add meta to field

- app/controllers/avo/application_controller.rb
- app/controllers/avo/associations_controller.rb
Fixes an issue where the `for_attribute` was not taken into consideration.
> fix: wrong for_attribute selection

- Gemfile
- Gemfile.lock
- lib/avo/resources/controls/actions_list.rb
- spec/dummy/db/schema.rb
- spec/system/avo/tabs_spec.rb
Using https://github.com/widefix/actual_db_schema to ensure the schema is correct throughout branches.
> chore: add actual_db_schema

- lib/avo/fields/base_field.rb
- lib/avo/fields/tags_field.rb
Extending the `update_using` option for the tags field.
> feature: extend `update_using` on tags

- spec/system/avo/date_time_fields/date_spec.rb
> chore: fix date flaky test

- Gemfile
- Gemfile.lock
- app/views/layouts/avo/application.html.erb
Tiny PR to add the CSV dependency
> chore: add CSV dep

- app/views/avo/partials/_confirm_dialog.html.erb
We refactored the confirm modal to look a bit better.
> refactor: confirm modal

- app/components/avo/views/resource_index_component.html.erb
- tailwind.preset.js
Closes https://github.com/avo-hq/avo/pull/2831
> chore: add index view type tailwind variant

- app/components/avo/fields/files_field/index_component.html.erb
- app/components/avo/fields/files_field/index_component.rb
- app/components/avo/filters_component.html.erb
- lib/generators/avo/templates/locales/avo.ar.yml
- lib/generators/avo/templates/locales/avo.en.yml
- lib/generators/avo/templates/locales/avo.es.yml
- lib/generators/avo/templates/locales/avo.fr.yml
- lib/generators/avo/templates/locales/avo.ja.yml
- lib/generators/avo/templates/locales/avo.nb.yml
- lib/generators/avo/templates/locales/avo.nn.yml
- lib/generators/avo/templates/locales/avo.pt-BR.yml
- lib/generators/avo/templates/locales/avo.pt.yml
- lib/generators/avo/templates/locales/avo.ro.yml
- lib/generators/avo/templates/locales/avo.tr.yml
- spec/dummy/config/locales/avo.en.yml
Fixes #2864
Add missing translation for applied filters and files counter.
> fix: missing translations

- Appraisals
- RELEASE.MD
- gemfiles/rails_6.1_ruby_3.1.4.gemfile
- gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
- gemfiles/rails_6.1_ruby_3.2.2.gemfile
- gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock
- gemfiles/rails_6.1_ruby_3.3.0.gemfile
- gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
- gemfiles/rails_7.1_ruby_3.1.4.gemfile
- gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
- gemfiles/rails_7.1_ruby_3.2.2.gemfile
- gemfiles/rails_7.1_ruby_3.2.2.gemfile.lock
- gemfiles/rails_7.1_ruby_3.3.0.gemfile
- gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
- gemfiles/rails_8.0_ruby_3.1.4.gemfile
- gemfiles/rails_8.0_ruby_3.1.4.gemfile.lock
- gemfiles/rails_8.0_ruby_3.2.2.gemfile
- gemfiles/rails_8.0_ruby_3.2.2.gemfile.lock
- gemfiles/rails_8.0_ruby_3.3.0.gemfile
- gemfiles/rails_8.0_ruby_3.3.0.gemfile.lock
- spec/rails_helper.rb
- spec/system/avo/tags_spec.rb
Fixes a spec that somehow passed un-noticed.
> test: fix bad validation test

- app/views/avo/base/_text_filter.html.erb
- config/i18n-tasks.yml
- lib/generators/avo/templates/locales/avo.ar.yml
- lib/generators/avo/templates/locales/avo.en.yml
- lib/generators/avo/templates/locales/avo.es.yml
- lib/generators/avo/templates/locales/avo.fr.yml
- lib/generators/avo/templates/locales/avo.ja.yml
- lib/generators/avo/templates/locales/avo.nb.yml
- lib/generators/avo/templates/locales/avo.nn.yml
- lib/generators/avo/templates/locales/avo.pt-BR.yml
- lib/generators/avo/templates/locales/avo.pt.yml
- lib/generators/avo/templates/locales/avo.ro.yml
- lib/generators/avo/templates/locales/avo.tr.yml
Fixes #2848
Adds missing filter translations.
> fix: missing filter translations

- lib/avo/photo_object.rb
- spec/dummy/app/avo/resources/event.rb
Fixes an issue where the cover and profile photos were not being shown on the proper views.
> fix: cover photo visible_on broken

- app/assets/stylesheets/css/pagination.css
Fixes #2344
[Peek 2024-07-02 11-25.webm](https://github.com/avo-hq/avo/assets/69730720/bab58cc7-887b-4a94-82b3-baeeba7a5008)
> fix: mobile pagination style

- app/components/avo/resource_component.rb
Fixes #2878 
Apply `edit_{association}?` policy.
> fix: apply `edit_{association}?` policy

- app/controllers/avo/base_controller.rb
- lib/avo/base_resource.rb
- lib/generators/avo/templates/resource/resource.tt
- spec/dummy/app/avo/resources/post.rb
- spec/dummy/app/avo/resources/project.rb
- spec/dummy/app/avo/resources/user.rb
This PR adds the `attachments` option which will add a new way to eager load attachments on a list of records.
This also adds `single_includes` and `single_attachments` that are being applied to those times a single record is being teched from the DB.
Another way to do this would be to optionally turn `includes` and `attachments` into callables and have an `if/else` statement to check if the view is `index` or `show/forms`.
By default they would be applied only to `index`, but in the block can be added to `show/forms` as well.
Implements changes from https://github.com/minthesize/avo/pull/3/
1. Go to the products index page
1. observe that comments have been eager loaded
2. go to the product show page
3. observe that the reviews have been eager loaded
Manual reviewer: please leave a …
> feature: add attachments to record

- app/controllers/avo/debug_controller.rb
Fixes a syntax error on the `DebugController`
> fix: debug_controller syntax error

- app/components/avo/index/table_row_component.html.erb
Fixes #2940
Before:
After:
1. Step 1
1. Step 2
> Fix margin for index row controls

- lib/avo/base_resource.rb
- lib/avo/concerns/pagination.rb
- spec/system/avo/app_spec.rb
Fixes a security issue that permitted XSS in pagination path helpers.
> security: prevent xss in pagination params

- app/components/avo/fields/boolean_group_field/edit_component.rb
- spec/dummy/app/models/user.rb
- spec/system/avo/boolean_group_field_spec.rb
This PR adds tests for the broken boolean group fix PR. 
It also makes sure such boolean group's check boxes are correctly checked in the edit view.
1. Step 1
1. Step 2
> Write tests for boolean group broken

- app/components/avo/resource_component.rb
Fixes #2917 
1. Step 1
1. Step 2
> Render action controls without adding to actions method

- spec/dummy/app/models/user.rb
I still couldn't push directly @adrianthedev so created a pr for this one.
> Add comment and lint

- lib/avo.rb
Fixes #3003
1. Step 1
1. Step 2
> fix: uninitialized constant Net::HTTP error

- lib/generators/avo/templates/locales/avo.de.yml
- lib/generators/avo/templates/locales/avo.it.yml
- lib/generators/avo/templates/locales/avo.nl.yml
- lib/generators/avo/templates/locales/avo.pl.yml
- lib/generators/avo/templates/locales/avo.ru.yml
- lib/generators/avo/templates/locales/avo.uk.yml
- lib/generators/avo/templates/locales/avo.zh.yml
- Add German Translations
- Add dutch translations
- Add russian translations
- Add chineze translations
- Add italian translations
- Add polish translations
- Add ukranian translations
Fixes #3019
1. Step 1
1. Step 2
> feature: Add translations for different languages

- spec/dummy/app/avo/resources/user.rb
- spec/system/avo/tabs_spec.rb
> chore: fix tests for #2985

- lib/avo/fields/date_time_field.rb
- lib/avo/fields/time_field.rb
> fix: model assignment

- app/components/avo/field_wrapper_component.html.erb
- app/components/avo/field_wrapper_component.rb
- app/components/avo/fields/boolean_field/edit_component.html.erb
- app/components/avo/index/field_wrapper_component.html.erb
- app/components/avo/index/field_wrapper_component.rb
Fixes https://github.com/avo-hq/avo/pull/2997#issuecomment-2243760277
> fix: boolean dash when false

- lib/avo/fields/belongs_to_field.rb
- lib/avo/fields/date_time_field.rb
- lib/avo/fields/files_field.rb
- lib/avo/fields/has_one_field.rb
- lib/avo/fields/key_value_field.rb
- lib/avo/fields/location_field.rb
- lib/avo/fields/time_field.rb
Rename `model` to `record` in `fill_field` methods
> refactor: rename `model` to `record` in `fill_field` methods

- app/components/avo/paginator_component.rb
- config/initializers/pagy.rb
Fixes https://github.com/avo-hq/avo/pull/3046#issuecomment-2248039233
1. Step 1
1. Step 2
> fix: check for pagy version

- app/controllers/avo/search_controller.rb
Fixes search issues introduced in https://github.com/avo-hq/avo/pull/3034
> fix: search

- spec/dummy/config/environments/test.rb
Fixing tests for https://github.com/avo-hq/avo/actions/runs/10214064399/job/28260721323?pr=3007
> chore: check if defined `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter`

- spec/dummy/config/initializers/avo.rb
> fix: menu test on `avo_warining_spec.rb`

- Gemfile.lock
- app/components/avo/paginator_component.rb
- app/components/avo/views/resource_index_component.html.erb
- config/initializers/pagy.rb
- spec/system/avo/filters/filters_spec.rb
> fix: pagy 9 support

- spec/system/sidebar_spec.rb
Write tests for sidebar.
1. Step 1
1. Step 2
> Chore: Test Sidebar

- gemfiles/rails_6.1_ruby_3.1.4.gemfile
- gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
- gemfiles/rails_6.1_ruby_3.3.0.gemfile
- gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
- gemfiles/rails_7.1_ruby_3.1.4.gemfile
- gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
- gemfiles/rails_7.1_ruby_3.3.0.gemfile
- gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
- gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile
- gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile.lock
- gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile
- gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile.lock
- gemfiles/rails_8.0_ruby_3.1.4.gemfile
- gemfiles/rails_8.0_ruby_3.1.4.gemfile.lock
- gemfiles/rails_8.0_ruby_3.3.0.gemfile
- gemfiles/rails_8.0_ruby_3.3.0.gemfile.lock
Fixes tests for https://github.com/avo-hq/avo/pull/3122
> chore: appraisal amazing_print

- tailwind.preset.js
Add properties to the `kanban-dragging` variant.
> chore: tweak tailwind variants

- app/components/avo/modal_component.html.erb
- app/components/avo/modal_component.rb
- spec/dummy/app/avo/resources/store.rb
- spec/dummy/app/avo/resources/team.rb
- spec/dummy/db/schema.rb
We sometimes need the modal body to not have that overflow behavior.
> refactor: add modal component overflow option

- lib/tasks/avo_tasks.rake
> fix: `avo:sym_link`

- app/controllers/avo/search_controller.rb
Fixes #3111
Related PR https://github.com/avo-hq/avo-pro/pull/87
https://github.com/user-attachments/assets/ed366afb-23c1-4337-8476-916e018448f2
> dx: information on global search

- app/components/avo/profile_item_component.rb
- app/components/avo/sidebar/base_item_component.rb
- app/components/avo/sidebar/group_component.html.erb
- app/components/avo/sidebar/heading_component.rb
- app/components/avo/sidebar/section_component.html.erb
Fixes https://github.com/avo-hq/avo-menu/issues/26
Related PR https://github.com/avo-hq/avo-menu/pull/30
> chore: drop dry-initializer dependency

- app/javascript/js/controllers/table_row_controller.js
Fixes https://github.com/avo-hq/avo/issues/3150
> feature: command+click opens url in a new tab

- app/assets/config/avo_manifest.js
Just a small prep PR.
Rhino comes in it's on gem.
> chore: prep for rhino field

- app/assets/config/avo_manifest.js
- app/helpers/avo/application_helper.rb
- lib/avo/svg_finder.rb
Reverts https://github.com/avo-hq/avo/pull/3177 and https://github.com/avo-hq/avo/pull/3178
> refactor: revert inline_svg optimization

- .github/workflows/feature-tests.yml
- .github/workflows/i18n-tests.yml
- .github/workflows/system-tests.yml
- .github/workflows/test-tailwindcss-integration.yml
> chore: update actions version

- Gemfile.lock
- gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
- gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
- gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
- gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
- gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile.lock
- gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile.lock
- gemfiles/rails_8.0_ruby_3.1.4.gemfile.lock
- gemfiles/rails_8.0_ruby_3.3.0.gemfile.lock
Update `view_component` to `3.15.1`
> chore: update `view_component` to `3.15.1`

- lib/avo/plugin_manager.rb
> chore: remove unused methods

- CONTRIBUTING.MD
- Gemfile
- app/components/avo/fields/boolean_group_field/edit_component.rb
- app/components/avo/index/resource_controls_component.rb
- app/components/avo/resource_component.rb
- app/javascript/avo.base.js
- app/javascript/js/controllers/copy_to_clipboard_controller.js
- app/javascript/js/controllers/sidebar_controller.js
- lib/tasks/avo_tasks.rake
> Fix typographical errors from app directory

- package.json
- yarn.lock
Update `tagify` to reflect this fix https://github.com/yairEO/tagify/issues/1391
> chore: update tagify

- app/views/avo/debug/status.html.erb
- lib/avo/licensing/h_q.rb
- lib/avo/services/debug_service.rb
Fixes an issue where the cache store was not properly displayed and a few metadata information not being sent.
> chore: fix cache store display

- config/i18n-tasks.yml
- lib/generators/avo/templates/locales/avo.de.yml
- lib/generators/avo/templates/locales/avo.it.yml
- lib/generators/avo/templates/locales/avo.nl.yml
- lib/generators/avo/templates/locales/avo.pl.yml
- lib/generators/avo/templates/locales/avo.ru.yml
- lib/generators/avo/templates/locales/avo.uk.yml
- lib/generators/avo/templates/locales/avo.zh.yml
Update the list of locales on i18n-tasks
> chore: update locales on i18n-tasks

- lib/generators/avo/templates/locales/avo.de.yml
- lib/generators/avo/templates/locales/avo.it.yml
- lib/generators/avo/templates/locales/avo.nl.yml
- lib/generators/avo/templates/locales/avo.pl.yml
- lib/generators/avo/templates/locales/avo.ru.yml
- lib/generators/avo/templates/locales/avo.uk.yml
- lib/generators/avo/templates/locales/avo.zh.yml
Executed `i18n-tasks normalize`
> chore: normalize i18n

- lib/avo/wait_for_loaded.rb
- spec/system/avo/actions_spec.rb
Fixes a flaky tests on actions
> chore: actions flaky test

- .gitignore
- db/factories.rb
- lib/avo/mappings.rb
- lib/generators/avo/resource_generator.rb
- spec/dummy/db/schema.rb
https://github.com/avo-hq/avo/pull/3466
Refactoring the mapping on a module to reuse it on meta feature
> refactor: fields mapping refactor

- spec/system/avo/date_time_fields/date_time_spec.rb
- spec/system/avo/date_time_fields/time_spec.rb
- spec/system/avo/date_time_fields/timezone_spec.rb
> chore: fix time flaky tests

- app/components/avo/asset_manager/javascript_component.html.erb
- app/controllers/avo/media_library_controller.rb
- app/javascript/js/controllers/fields/trix_field_controller.js
- app/views/avo/partials/_javascript.html.erb
- app/views/layouts/avo/application.html.erb
- lib/avo/media_library/configuration.rb
Fixes an issue where the Media Library wasn't disabled by default.
> chore: media library and asset tweaks

- app/components/avo/sidebar_component.html.erb
This PR moves the media library as the last sidebar entry
> chore: move media library menu entry

- lib/avo/resources/array_resource.rb
Fixes #3629 
Fixing the authorization application in the context of array resources.
> fix: array resource authorization

- lib/generators/avo/action_generator.rb
Enhancing the action generator to properly generate namespaced actions.
This command `bin/rails generate avo:action admin/approve_user` will generate an action file `app/avo/actions/admin/approve_user.rb`:
```ruby
class Avo::Actions::Admin::ApproveUser < Avo::BaseAction
self.name = "Admin/Approve User"
def handle(query:, fields:, current_user:, resource:, **args)
query.each do |record|
end
end
end
```
> enhancement: namespaced actions generator

- .github/pr-labeler.yml
- spec/dummy/config/environments/test.rb
Updates pr-labeler to include Enhancement section
> chore: update pr-labeler

- spec/dummy/config/environments/test.rb
- spec/system/avo/tabs_spec.rb
> chore: fix tabs_spec.rb

- lib/avo/fields/concerns/nested.rb
> fix: allow `nested: false`

- lib/generators/avo/concerns/parent_controller.rb
- lib/generators/avo/resource_generator.rb
- lib/generators/avo/templates/resource/resource.tt
This PR includes the Http resource and controller generator
> refactor: http generator

- spec/dummy/app/avo/resources/team.rb
Fixes #3768 
Migrating `logo.clearbit` to `logo.dev`
> refactor: migrate `logo.clearbit` to `logo.dev`

- .github/release-drafter.yml
> chore: maintenance last in release notes

- app/views/avo/partials/_table_header.html.erb
- lib/avo/fields/base_field.rb
- lib/avo/fields/belongs_to_field.rb
- lib/avo/fields/file_field.rb
- lib/avo/fields/frame_base_field.rb
- spec/dummy/app/avo/resources/post.rb
Fixing the `belongs_to` field when using `for_attribute`
> fix: `belongs_to` when using `for_attribute`

- app/components/avo/discreet_information_component.rb
- lib/avo/discreet_information.rb
- spec/dummy/app/avo/resources/project.rb
Adds the `visible` option to discreet information.
> enhancement: discreet_information visible setting

- spec/dummy/app/avo/resources/city.rb
- spec/dummy/config/environments/test.rb
- spec/system/avo/alert_backtrace_spec.rb
> chore: fix tests

- Gemfile
- gemfiles/rails_6.1_ruby_3.1.4.gemfile
- gemfiles/rails_6.1_ruby_3.3.0.gemfile
- gemfiles/rails_7.1_ruby_3.1.4.gemfile
- gemfiles/rails_7.1_ruby_3.3.0.gemfile
- gemfiles/rails_8.0_ruby_3.3.0.gemfile
> chore: add dotenv gem for test env

- .github/workflows/i18n-tests.yml
- lib/generators/avo/templates/locales/avo.ar.yml
- lib/generators/avo/templates/locales/avo.de.yml
- lib/generators/avo/templates/locales/avo.en.yml
- lib/generators/avo/templates/locales/avo.es.yml
- lib/generators/avo/templates/locales/avo.fr.yml
- lib/generators/avo/templates/locales/avo.it.yml
- lib/generators/avo/templates/locales/avo.ja.yml
- lib/generators/avo/templates/locales/avo.nb.yml
- lib/generators/avo/templates/locales/avo.nl.yml
- lib/generators/avo/templates/locales/avo.nn.yml
- lib/generators/avo/templates/locales/avo.pl.yml
- lib/generators/avo/templates/locales/avo.pt-BR.yml
- lib/generators/avo/templates/locales/avo.pt.yml
- lib/generators/avo/templates/locales/avo.ro.yml
- lib/generators/avo/templates/locales/avo.ru.yml
- lib/generators/avo/templates/locales/avo.tr.yml
- lib/generators/avo/templates/locales/avo.uk.yml
- lib/generators/avo/templates/locales/avo.zh-TW.yml
- lib/generators/avo/templates/locales/avo.zh.yml
Add i18n tests to 4-dev branch
> Add i18n tests to 4-dev branch

- lib/tasks/avo_tasks.rake
Fixes `syml_link` task based on the changes that were made on [this PR](https://github.com/avo-hq/avo/pull/3971)
> fix: adjust sym_link to the new assets approach

- avo.gemspec
Includes JS builds on release.
> ship application.js and application.js.map

- lib/generators/avo/templates/locales/avo.de.yml
- lib/generators/avo/templates/locales/avo.en.yml
- lib/generators/avo/templates/locales/avo.es.yml
- lib/generators/avo/templates/locales/avo.fr.yml
- lib/generators/avo/templates/locales/avo.it.yml
- lib/generators/avo/templates/locales/avo.nb.yml
- lib/generators/avo/templates/locales/avo.nl.yml
- lib/generators/avo/templates/locales/avo.nn.yml
- lib/generators/avo/templates/locales/avo.pl.yml
- lib/generators/avo/templates/locales/avo.pt-BR.yml
- lib/generators/avo/templates/locales/avo.pt.yml
- lib/generators/avo/templates/locales/avo.ro.yml
- lib/generators/avo/templates/locales/avo.ru.yml
- lib/generators/avo/templates/locales/avo.tr.yml
- lib/generators/avo/templates/locales/avo.uk.yml
> Fix locales extra commas

- lib/avo/fields/code_field.rb
Fixes `pretty_generated` when the code field is submitted empty
> fix: pretty_generated

- lib/avo/resources/resource_manager.rb
> chore: pass resource_class to authz
